---
- name: Install configuration.yaml
  ansible.builtin.template:
    src: ../templates/configuration.yaml.j2
    dest: "{{ home_assistant_docker_data_dir }}/configuration.yaml"
    mode: "0660"

# - name: Install include files
#   ansible.builtin.copy:
#     src: "../files/{{ item }}"
#     dest: "{{ home_assistant_docker_data_dir }}/includes"
#     mode: "0660"
#   loop:
#     - "inputs.yaml"
#     - "sensors.yaml"
#     - "templates.yaml"

# - name: Install Lovelace UI files
#   ansible.builtin.copy:
#     src: "../files/{{ item }}"
#     dest: "{{ home_assistant_docker_data_dir }}/lovelace"
#   loop:
#     - "weather.yaml"