---
- name: "Get info on {{ __navidrome_docker_network_name }} network"
  community.docker.docker_network_info:
    name: "{{ __navidrome_docker_network_name }}"
  register: __navidrome_docker_netinfo

- name: "Verify {{ __navidrome_docker_network_name }} network exists"
  ansible.builtin.assert:
    that: __navidrome_docker_netinfo.exists

- name: "Verify {{ __navidrome_docker_network_name }} is attached to container"
  ansible.builtin.assert:
    that:
      - __navidrome_docker_netinfo['network']['Containers'][__container_id] is defined
      - __navidrome_docker_netinfo['network']['Containers'][__container_id]['Name'] is defined
