###
### Glances
###
glances_host_domain: "{{ inventory_hostname }}.{{ veggie_nas_domain_name }}"

###
### Logrotate
###
logrotate_scripts:
  - name: rclone
    path: "/var/log/rclone.log"
    options:
      - daily
      - rotate 7
      - missingok
      - compress
      - delaycompress
      - copytruncate

###
### Plex
###
plex_docker_claim: "{{ plex_claim }}"
plex_docker_db_path: "/mnt/nas/plex"
plex_docker_transcode_path: "/tmp/plex/transcode"

###
### RClone
###
rclone_configs:
  - name: AwsS3Remote
    properties:
      type: s3
      provider: AWS
      env_auth: false
      region: us-west-2
      location_constraint: us-west-2
      acl: private
      server_side_encryption: AES256
      storage_class: STANDARD
      access_key_id: "{{ aws_s3_rclone_access_key }}"
      secret_access_key: "{{ aws_s3_rclone_secret_key }}"
veggie_rclone_s3_bucket: "{{ veggie_nas_rclone_s3_bucket }}"
veggie_rclone_config_path: /root/.config/rclone/rclone.conf

###
### Samba
###
samba_users:
  - name: "{{ veggie_nas_admin_username }}"
    password: "{{ veggie_nas_admin_samba_passwd }}"
  # - name: "plex"
  #   password: "{{ veggie_nas_plex_password }}"
  - name: "retropie"
    password: "{{ veggie_nas_retropie_password }}"
veggie_nas_samba_groups:
  - book_writer
  - doc_writer
  - media_writer
  - music_writer
  - photo_writer
  - rom_writer
  - source_writer
veggie_nas_users_passwords:
  retropie: "*"

###
### TimeMachine
###
timemachine_data_directory: "/mnt/nas/time-machine"
timemachine_volume_size_limit: "512000"
timemachine_share_name: "nas-time-machine"