###
### Glances
###
glances_host_domain: "{{ inventory_hostname }}.{{ veggie_nas_domain_name }}"

###
### Plex
###
plex_docker_claim: "{{ plex_claim }}"
plex_docker_db_path: "/mnt/nas/plex"
plex_docker_transcode_path: "/mnt/nas/plex/transcode"

###
### RClone
###
rclone_configs:
  - name: AwsS3Remote
    properties:
      type: s3
      provider: AWS
      env_auth: false
      region: us-west-2
      location_constraint: us-west-2
      acl: private
      server_side_encryption: AES256
      storage_class: STANDARD
      access_key_id: "{{ aws_s3_rclone_access_key }}"
      secret_access_key: "{{ aws_s3_rclone_secret_key }}"

###
### Samba
###
samba_users:
  - name: "{{veggie_nas_admin_username}}"
    password: "{{veggie_nas_admin_samba_passwd}}"
  - name: "plex"
    password: "{{veggie_nas_plex_password}}"
  - name: "retropie"
    password: "{{veggie_nas_retropie_password}}"
veggie_nas_samba_groups:
  - book_writer
  - doc_writer
  - media_writer
  - music_writer
  - photo_writer
  - rom_writer
  - source_writer
veggie_nas_users_passwords:
  retropie: "*"

###
### TimeMachine
###
timemachine_data_directory: "/mnt/nas/time-machine"
timemachine_volume_size_limit: "512000"