###
### Calibre
###
calibre_available_externally: "true"
calibre_data_directory: "/virtpool/calibre"
calibre_books_root: "/mnt/nas/books"
calibre_host_domain: "{{ veggie_base_domain_name }}"
calibre_extra_groups:
  - "book_writer"
calibre_user_id: "2100"
calibre_group_id: "2000"

###
### Common
###
veggie_hostname: "{{ veggie_virt_domain_name }}"
veggie_admin_username: "{{ veggie_nas_admin_username }}"
veggie_admin_passwd: "{{ veggie_nas_admin_passwd }}"

###
### Docker
###
docker_home: /virtpool/docker
docker_admin_user: "{{ veggie_admin_username }}"
veggie_virt_iot_network_parent: "bond0.40" # VLAN 40

###
### Glances
###
glances_host_domain: "{{ veggie_virt_domain_name }}"

###
### Grafana
###
grafana_docker_data_dir: "/virtpool/grafana/lib"
grafana_docker_log_dir: "/virtpool/grafana/log"
grafana_docker_conf_dir: "/virtpool/grafana/etc"
grafana_docker_zfs_filesystems:
  - "virtpool/grafana"
  - "virtpool/grafana/etc"
  - "virtpool/grafana/lib"
  - "virtpool/grafana/log"
grafana_docker_host_domain: "{{ veggie_virt_domain_name }}"

###
### Home Assistant
###
home_assistant_docker_data_dir: "/virtpool/home-assistant"
home_assistant_docker_zfs_filesystems:
  - "virtpool/home-assistant"
home_assistant_docker_hostname: "hass"
home_assistant_docker_host_domain: "{{ veggie_base_domain_name }}"
home_assistant_docker_memory: "3G"
hass_home_latitude: "{{ home_latitude }}"
hass_home_longitude: "{{ home_longitude }}"
hass_home_timezone: "{{ home_timezone }}"
hass_url: "http://{{ veggie_home_assistant_hostname }}"
hass_db_user: "{{ veggie_hass_db_user }}"
hass_db_password: "{{ veggie_hass_db_password }}"

###
### NFS mounts
###
nfs_mounts:
  - src: "{{ veggie_nas_domain_name }}:/mnt/nas/data/books"
    path: "/mnt/nas/books"
    fstype: "nfs4"
    opts: "auto,noatime,nolock,bg,nfsvers=4,intr,tcp,actimeo=1800"

###
### PgAdmin
###
pgadmin_docker_dir: "/virtpool/pgadmin/lib"
pgadmin_docker_conf_dir: "/virtpool/pgadmin/conf"
pgadmin_default_email: "{{ primary_email_address }}"
pgadmin_docker_host_domain: "{{ veggie_virt_domain_name }}"
pgadmin_default_password: "{{ veggie_postgres_admin_password }}"
pgadmin_docker_email_server: "email-smtp.us-west-2.amazonaws.com"
pgadmin_docker_email_port: "587"
pgadmin_docker_email_use_ssl: "False"
pgadmin_docker_email_user_tls: "True"
pgadmin_docker_email_username: "{{ aws_ses_usw2_access_key }}"
pgadmin_docker_email_password: "{{ aws_ses_usw2_secret_key }}"
pgadmin_docker_servers:
  "pg_hass":
    Name: "Hass Postgres"
    Group: "Servers"
    Port: "5432"
    Username: "postgres"
    Host: "postgres"
    SSLMode: "prefer"
    MaintenanceDB: "postgres"

###
### Pip
###
pip_install_packages:
  - docker

###
### Portainer
###
portainer_available_externally: "true"
portainer_admin_password: "{{ vault_portainer_admin_password }}"
portainer_host_domain: "{{ veggie_virt_domain_name }}"

###
### PostgreSQL
###
postgresql_docker_home_dir: "/virtpool/{{ postgresql_docker_name }}"
postgresql_docker_conf_dir: "{{ postgresql_docker_home_dir }}/conf"
postgresql_docker_data_dir: "{{ postgresql_docker_home_dir }}/data"
postgresql_docker_admin_password: "{{ veggie_postgres_admin_password }}"

###
### Traefik
###
traefik_hostname: "traefik.{{ veggie_virt_domain_name }}"
traefik_confkey_api:
  dashboard: true # use this for enabling the dashboard
# traefik_confkey_log:
#   level: DEBUG
#   filePath: /var/log/traefik.log
traefik_qs_https: "true"
traefik_qs_https_redirect: "true"
traefik_qs_https_le: "true"
traefik_qs_https_le_mail: "{{ letsencrypt_email }}"
traefik_qs_log_level: INFO
# Defined dynamically in roles/veggie_virt/tasks/docker.yml
# traefik_extra_networks:
traefik_ports:
  - "192.168.25.20:80:80"
  - "192.168.25.20:443:443"
  - "192.168.25.20:1400:1400" # Home Assistant: Sonos
  - "192.168.25.20:4199:4199" # Ecowitt
  - "192.168.25.20:5432:5432" # Postgres
  - "192.168.25.20:3000:3000" # zwavejs2mqtt
traefik_labels:
  traefik.enable: "true"
  traefik.http.routers.traefik.service: "api@internal"
  traefik.http.routers.traefik.entrypoints: "https"
  traefik.http.routers.traefik.tls.certresolver: "letsencrypt"
  traefik.http.routers.traefik.tls.domains[0].main: "*.{{ veggie_virt_domain_name }}"
traefik_confkey_providers:
  docker:
    defaultRule: "Host(`{{ traefik_hostname }}`)"
traefik_le_ca_server: "https://acme-v02.api.letsencrypt.org/directory"
# traefik_le_ca_server: "https://acme-staging-v02.api.letsencrypt.org/directory"
traefik_confkey_certificatesResolvers:
  letsencrypt:
    acme:
      caServer: "{{ traefik_le_ca_server }}"
      dnsChallenge:
        provider: route53
traefik_confkey_entryPoints:
  ecowitt:
    address: ":4199"
  postgres:
    address: ":5432"
  sonos:
    address: ":1400"
  zwavejs2:
    address: ":3000"
traefik_confkey_serversTransport:
  insecureSkipVerify: "true"
traefik_container_environment:
  AWS_HOSTED_ZONE_ID: "{{ acme_route53_hosted_zone_id }}"
  AWS_ACCESS_KEY_ID: "{{ letsencrypt_aws_access_key }}"
  AWS_SECRET_ACCESS_KEY: "{{ letsencrypt_aws_secret_key }}"

###
### UniFi Controiller
###
unific_available_externally: "true"
unific_host_domain: "{{ veggie_virt_domain_name }}"
unific_cpus: "2"
unific_memory: "2GB"
unific_network_mode: "{{ traefik_network_name }}"
unific_dir_data: "/virtpool/unific/data"
unific_dir_log: "/virtpool/unific/log"
unific_dir_cert: "/virtpool/unific//cert"

###
### zwavejs2mqtt
###
zwavejs2mqtt_docker_network: "{{ home_assistant_docker_network }}"
zwavejs2mqtt_timezone: "{{ home_timezone }}"
zwavejs2mqtt_host_domain: "{{ veggie_base_domain_name }}"
