---
- alias: "Espresso Machine - On"
  trigger:
  - platform: time
    at: "07:00"
  condition:
  - condition: template
    value_template: "{{ not(bool(states('binary_sensor.is_commute_day'))) }}"
  - condition: template
    value_template: "{{ not(bool(states('binary_sensor.is_vacation_mode'))) }}"
  action:
  - type: turn_on
    device_id: "088ea18fbcde9a76b68d841f475dde7e"
    entity_id: "switch.plug_in_appliance_module_espresso"
    domain: "switch"
  mode: "single"

- alias: "Espresso Machine - Off (Weekend)"
  trigger:
  - platform: time
    at: "14:00"
  condition:
  - condition: template
    value_template: "{{ bool(states('binary_sensor.is_weekend')) }}"
  - condition: template
    value_template: "{{ not(bool(states('binary_sensor.is_vacation_mode'))) }}"
  action:
  - type: turn_off
    device_id: "088ea18fbcde9a76b68d841f475dde7e"
    entity_id: "switch.plug_in_appliance_module_espresso"
    domain: "switch"
  mode: "single"

- alias: "Espresso Machine - On (Commute Days)"
  trigger:
  - platform: time
    at: "06:00"
  condition:
  - condition: template
    value_template: "{{ bool(states('binary_sensor.is_commute_day')) }}"
  - condition: template
    value_template: "{{ not(bool(states('binary_sensor.is_vacation_mode'))) }}"
  action:
  - type: turn_on
    device_id: "088ea18fbcde9a76b68d841f475dde7e"
    entity_id: "switch.plug_in_appliance_module_espresso"
    domain: "switch"
  mode: "single"

- alias: "Espresso Machine - Off (Commute Days)"
  trigger:
  - platform: time
    at: "07:45"
  condition:
  - condition: template
    value_template: "{{ bool(states('binary_sensor.is_commute_day')) }}"
  - condition: template
    value_template: "{{ not(bool(states('binary_sensor.is_vacation_mode'))) }}"
  action:
  - type: turn_off
    device_id: "088ea18fbcde9a76b68d841f475dde7e"
    entity_id: "switch.plug_in_appliance_module_espresso"
    domain: "switch"
  mode: "single"

- alias: "Espresso Machine - Off (Workday)"
  trigger:
  - platform: time
    at: "12:00"
  condition:
  - condition: template
    value_template: "{{ bool(states('binary_sensor.is_weekday')) }}"
  - condition: template
    value_template: "{{ not(bool(states('binary_sensor.is_commute_day'))) }}"
  - condition: template
    value_template: "{{ not(bool(states('binary_sensor.is_vacation_mode'))) }}"
  action:
  - type: turn_off
    device_id: "088ea18fbcde9a76b68d841f475dde7e"
    entity_id: "switch.plug_in_appliance_module_espresso"
    domain: "switch"
  mode: "single"