---
- name: Build restic repository URL
  ansible.builtin.set_fact:
    restic_repo_url: "rest:https://{{ restic_client_user }}:{{ restic_client_passwd }}@{{ restic_server_name }}/{{ restic_repo_name }}"

- name: Create restic config folder
  ansible.builtin.file:
    dest: "{{ restic_config_folder }}"
    state: "directory"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: 0770

- name: Create repository location file
  ansible.builtin.copy:
    content: "{{ restic_repo_url }}"
    dest: "{{ restic_config_location_file }}"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: 0640

- name: Create repository location shell script
  ansible.builtin.copy:
    content: >
      #!/bin/sh

      export RESTIC_REPOSITORY='{{ restic_repo_url }}'
    dest: "{{ restic_config_location_script_file }}"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: 0640

- name: Create repository password file
  ansible.builtin.copy:
    content: "{{ restic_repo_password }}"
    dest: "{{ restic_config_password_file }}"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: 0640

- name: Create backup includes file
  ansible.builtin.template:
    src: "../templates/include_exclude.j2"
    dest: "{{ restic_config_folder }}/includes"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: 0640
  vars:
    restic_client_file_paths: "{{ restic_client_include_paths }}"

- name: Create backup excludes file
  ansible.builtin.template:
    src: "../templates/include_exclude.j2"
    dest: "{{ restic_config_folder }}/excludes"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: 0640
  vars:
    restic_client_file_paths: "{{ restic_client_exclude_paths }}"