---
- name: Create Systemd services
  ansible.builtin.template:
    src: "../templates/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: "root"
    group: "root"
    mode: 0644
  loop:
    - "restic-backup.service"
    - "restic-prune.service"
