- name: "Configure media storage"
  hosts: nas
  remote_user: "sean"
  become: yes

  pre_tasks:
    - name: "Create top-level ZFS datasets"
      community.general.zfs:
        name: "{{ item }}"
        state: present
      loop:
        - "nas/data/videos"
        - "nas/data/videos/movies"
        - "nas/data/videos/movies/1080p"
        - "nas/data/videos/movies/2160p"
        - "nas/data/videos/movies/unmonitored"
        - "nas/data/videos/tv"
        - "nas/data/videos/tv/1080p"
        - "nas/data/videos/tv/2160p"
        - "nas/data/videos/tv/unmonitored"
    
  tasks:
    - name: "Create ZFS datasets for 1080p movies"
      import_tasks: "zfs-alpha-datasets.yml"
      vars:
        _zfs_dataset_desc: "1080p movies"
        _zfs_dataset_base: "nas/data/videos/movies/1080p"

    - name: "Create ZFS datasets for 2160p movies"
      import_tasks: "zfs-alpha-datasets.yml"
      vars:
        _zfs_dataset_desc: "2160p movies"
        _zfs_dataset_base: "nas/data/videos/movies/2160p"

    - name: "Create ZFS datasets for unmonitored movies"
      import_tasks: "zfs-alpha-datasets.yml"
      vars:
        _zfs_dataset_desc: "unmonitored movies"
        _zfs_dataset_base: "nas/data/videos/movies/unmonitored"
