---
- name: "Create ZFS datasets for {{ _zfs_dataset_desc }}"
  community.general.zfs:
    name: "{{ _zfs_dataset_base }}/{{ item }}"
    state: present
  loop:
    - "A"
    - "B"
    - "C"
    - "D"
    - "E"
    - "F"
    - "G"
    - "H"
    - "I"
    - "J"
    - "K"
    - "L"
    - "M"
    - "N"
    - "O"
    - "P"
    - "Q"
    - "R"
    - "S"
    - "T"
    - "U"
    - "V"
    - "W"
    - "X"
    - "Y"
    - "Z"