- name: Modify InfluxDB hostname
  ansible.builtin.replace:
    dest: /etc/influxdb/influxdb.conf
    regexp: 'hostname = "localhost"'
    replace: 'hostname = "{{ ansible_hostname }}"'
    backup: yes
  notify:
    - Restart InfluxDB