---
- name: "Create overseerr Docker config volume"
  community.docker.docker_volume:
    name: "{{ overseerr_docker_volume_config_name }}"

- name: "Set Docker mount list for volume mounts"
  ansible.builtin.set_fact:
    _overseerr_docker_mount_list:
      - source: "{{ overseerr_docker_volume_config_name }}"
        target: "/app/config"
        type: "volume"

- name: "Build container FQDN"
  ansible.builtin.set_fact:
    _overseerr_docker_fqdn: "{{ overseerr_docker_host_name }}.{{ overseerr_docker_host_domain }}"

- name: "Create placeholder array for default network"
  ansible.builtin.set_fact:
    _overseerr_docker_default_networks:
      - name: "{{ overseerr_docker_network }}"
        aliases: "{{ overseerr_docker_network_aliases | default(omit) }}"

- name: "Define all Docker networks for this container"
  ansible.builtin.set_fact:
    _overseerr_docker_all_networks: >
      {{ _overseerr_docker_default_networks + overseerr_docker_extra_networks }}

- name: "Define Docker labels with Traefik disabled"
  ansible.builtin.set_fact:
    _overseerr_docker_labels: "{{ _overseerr_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  with_items:
    - key: "traefik.enable"
      value: "{{ overseerr_available_externally }}"
  when: "not overseerr_docker_available_externally"

- name: "Define Docker labels with Traefik enabled"
  ansible.builtin.set_fact:
    _overseerr_docker_labels: "{{ _overseerr_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  with_items:
    - key: "traefik.enable"
      value: "{{ overseerr_docker_available_externally }}"
    - key: "traefik.docker.network"
      value: "{{ servarr_docker_network }}"
    - key: "traefik.http.routers.overseerr.rule"
      value: "Host(`{{ _overseerr_docker_fqdn }}`)"
    - key: "traefik.http.routers.overseerr.entrypoints"
      value: "http,https"
    - key: "traefik.http.routers.overseerr.tls.certresolver"
      value: "letsencrypt"
    - key: "traefik.http.routers.overseerr.tls.domains[0].main"
      value: "*.{{ overseerr_docker_host_domain }}"
    - key: "traefik.http.services.overseerr.loadbalancer.server.port"
      value: "{{ overseerr_docker_web_port }}"
  when: "overseerr_docker_available_externally"

- name: "Define user-supplied extra Docker labels"
  ansible.builtin.set_fact:
    _overseerr_docker_labels: "{{ _overseerr_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  loop: "{{ overseerr_docker_extra_labels | dict2items }}"

- name: "overseerr Docker Container"
  community.docker.docker_container:
    name: "{{ overseerr_docker_name }}"
    image: "{{ overseerr_docker_image }}:{{ overseerr_docker_image_version }}"
    pull: true
    env:
      "LOG_LEVEL": "{{ overseerr_docker_log_level }}"
      "PORT": "{{ overseerr_docker_web_port }}"
      "TZ": "{{ overseerr_docker_timezone }}"
    mounts: "{{ _overseerr_docker_mount_list }}"
    network_mode: "{{ overseerr_docker_network }}"
    networks: "{{ _overseerr_docker_all_networks }}"
    etc_hosts: "{{ overseerr_docker_extra_hosts | default(omit) }}"
    restart_policy: unless-stopped
    memory: "{{ overseerr_docker_memory }}"
    cpus: "{{ overseerr_docker_cpus }}"
    container_default_behavior: no_defaults
    auto_remove: no
    detach: yes
    init: no
    interactive: no
    paused: no
    privileged: no
    read_only: no
    tty: no
    labels: "{{ _overseerr_docker_labels }}"
