---
- name: "Install configuration yaml"
  ansible.builtin.template:
    src: "../templates/diun.yml.j2"
    dest: "{{ diun_config_file }}"
    owner: "{{ diun_user }}"
    group: "{{ diun_group }}"
    mode: "0660"

- name: "Install file provider yaml"
  ansible.builtin.template:
    src: "../templates/provider.yml.j2"
    dest: "{{ diun_provider_file_name }}"
    owner: "{{ diun_user }}"
    group: "{{ diun_group }}"
    mode: "0660"
