---
- name: Diun Docker Volume
  community.docker.docker_volume:
    name: "{{ diun_docker_volume_name }}"

- name: Diun Docker Container
  community.docker.docker_container:
    name: diun
    image: crazymax/diun:latest
    pull: true
    mounts:
      - source: "{{ diun_docker_volume_name }}"
        target: "/data"
        type: "volume"
      - source: "{{ diun_config_file }}"
        target: "/diun.yml"
        type: "bind"
        read_only: "true"
      - source: "{{ diun_provider_file_name }}"
        target: "/provider.yml"
        type: "bind"
        read_only: "true"
      - source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
        type: "bind"
    network_mode: "{{ diun_docker_network_name }}"
    networks:
      - name: "{{ diun_docker_network_name }}"
    restart_policy: unless-stopped
    memory: "{{ diun_docker_memory }}"
    cpus: "{{ diun_docker_cpus }}"
    container_default_behavior: no_defaults
    auto_remove: no
    detach: yes
    init: yes
    interactive: no
    paused: no
    privileged: no
    read_only: no
    tty: no
