---
- name: Create ZFS file systems
  community.general.zfs:
    name: "{{ item }}"
    state: present
  loop: "{{ diun_zfs_filesystems }}"

- name: Create diun group
  ansible.builtin.group:
    name: "{{ diun_group }}"

- name: Create diun user
  ansible.builtin.user:
    name: "{{ diun_user }}"
    uid: "{{ diun_uid | default(omit) }}"
    group: "{{ diun_group }}"
    append: "true"
    create_home: "false"
    groups: "{{ diun_extra_groups | default(omit) }}"
    password: "!"

- name: Create diun directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ diun_user }}"
    group: "{{ diun_group }}"
    mode: "0770"
  with_items:
    - "{{ diun_data_dir }}"
    - "{{ diun_config_dir }}"
