---
# defaults file for r740xd

###
### Admin
###
nas_admin_passwd: null
nas_admin_user: null

###
### Calibre Web
###
nas_calibre_web_book_dir: null
nas_calibre_web_gid: null
nas_calibre_web_host_domain: null
nas_calibre_web_hostname: "calibre-web"
nas_calibre_web_uid: null

###
### Diun
###
nas_diun_config_dir: "/etc/diun"
nas_diun_network_name: "diun"
nas_diun_notify_mail_host: null
nas_diun_notify_mail_port: null
nas_diun_notify_mail_username: null
nas_diun_notify_mail_password: null
nas_diun_notify_mail_from: null
nas_diun_notify_mail_to: null

nas_diun_regopts_dockerio_user: null
nas_diun_regopts_dockerio_passwd: null

###
### Docker macvlan network
###

# IPv4 gateway for the macvlan network.
nas_docker_macvlan_gateway: null

# IPv4 range set aside for the macvlan network in subnet format.
# Example: "192.168.1.240/28"
nas_docker_macvlan_iprange: null

# Name of the macvlan network.
nas_docker_macvlan_network_name: "nas_macvlan"

# Name of the parent interface on the host for the macvlan network.
# Examples: "eth0", "eno1"
nas_docker_macvlan_network_parent: null

# IPv4 subnet for the macvlan network.
nas_docker_macvlan_subnet: null

##########

# Base domain name for machine and containers running on it.
nas_domain_name: "host.subdomain.example.com"

# Base domain the entire site / location.
nas_site_domain: "subdomain.example.com"

###
### Glances
###
nas_glances_config_data: null

# List of dictionaries of Linux groups to create. Each entry in the list should be a dictionary
# in the form to match ansible.builtin.group.
# Example:
#   nas_groups:
#     - name: "group1"
#     - name: "group2"
#       gid: 4200
#     - name: "group3"
#       system: true
nas_groups: []

###
### Home Assistant
###
nas_hass_ecowitt_hass_auth_token: null
nas_hass_ecowitt_hass_webhook_id: null
nas_hass_host_domain: null
nas_hass_host_name: "hass"
nas_hass_latitude: null
nas_hass_longitude: null
nas_hass_pgsql_admin_password: null
nas_hass_pgsql_init_tempates_dir: null
nas_hass_timezone: null
nas_hass_zwave_device: null

###
### Kometa
###
nas_kometa_cpus: "2"
nas_kometa_memory: "2G"
nas_kometa_libraries: null 
nas_kometa_mdblist_apikey: null
nas_kometa_plex_token: null
nas_kometa_plex_url: null
nas_kometa_run_once_only: false
nas_kometa_tautulli_apikey: null
nas_kometa_tmdb_apikey: null
nas_kometa_trakt: null

###
### Lidarr
###
nas_lidarr_cpus: null
nas_lidarr_host_domain: null

###
### Navidrome
###
nas_navidrome_host_name: "navi"
nas_navidrome_host_domain: null
nas_navidrome_lastfm_apikey: null
nas_navidrome_lastfm_secret: null
nas_navidrome_music_folder: null
nas_navidrome_spotify_client_id: null
nas_navidrome_spotify_client_secret: null

###
### Overseerr
###
nas_overseerr_host_domain: null

###
### Plex
###
nas_plex_container_name: "plex"
nas_plex_claim: null
nas_plex_cpus: 8
nas_plex_memory: "4GB"
nas_plex_network_name: null
nas_plex_network_ipv4: null
nas_plex_music_path: null
nas_plex_old_music_path: null
nas_plex_videos_path: null

###
### Prowlarr
###
nas_prowlarr_host_domain: null

###
### Radarr
###
nas_radarr_cpus: "2"
nas_radarr_movie_source_path: null
nas_radarr_web_port: null # optional
nas_radarr1080_api_key: null
nas_radarr1080_host_domain: null
nas_radarr4k_api_key: null
nas_radarr4k_host_domain: null

###
### Readarr
###
nas_readarr_api_key: null
nas_readarr_host_domain: null

###
### Sabnzbd
###
nas_sabnzbd_host_domain: null

###
### Samba
###
# List of group names for Samba groups. The admin user will automatically be added to these
# groups.
nas_samba_group_names: []
nas_samba_admin_username: "admin"
nas_samba_admin_password: "password"

###
### Servarr
###
nas_servarr_cloudflared_token: null
nas_servarr_path: null
nas_servarr_tv_source_path: null
nas_servarr_zfs_dataset: null

###
### Sonarr
###
nas_sonarr_cpus: "2"
nas_sonarr_web_port: null # optional
nas_sonarr1080_api_key: null
nas_sonarr1080_host_domain: null
nas_sonarr4k_api_key: null
nas_sonarr4k_host_domain: null

###
### SyncThing
###
nas_syncthing_host_domain: null

###
### Tautulli
###
mas_tautulli_container_name: "tautulli"
nas_tautulli_hostname: "tautulli"

###
### TimeMachine
###
nas_time_machine_data_directory: null
nas_time_machine_hostname: "time-machine"
nas_time_machine_groupname: "time-machine"
nas_time_machine_gid: 1311
nas_time_machine_password: null
nas_time_machine_username: "time-machine"
nas_time_machine_uid: 1311
nas_time_machine_zfs_dataset: null

###
### UniFi Controller
###
nas_unific_cpus: "2"
nas_unific_hostname: "unific"
nas_unific_host_domain: null
nas_unific_memory: "2G"


##########

nas_timezone: "America/New_York"

# List of dictionaries of Linux users to create. Each entry in the list should be a dictionary
# in the form to match ansible.builtin.user.
nas_users: []