---
# defaults file for r740xd

###
### Admin
###
r740xd_admin_passwd: null
r740xd_admin_user: null

###
### AWS: Route53
###
r740xd_aws_route53_access_key_id: null
r740xd_aws_route53_hosted_zone_id: null
r740xd_aws_route53_region: "us-east1"
r740xd_aws_route53_secret_access_key: null

###
### Bazarr
###
r740xd_bazarr_cpus: "2"
r740xd_bazarr_memory: "1GB"
r740xd_bazarr_movie_source_path: null
r740xd_bazarr_web_port: null # optional
r740xd_bazarr1080_host_domain: null
r740xd_bazarr4k_host_domain: null

###
### Calibre Web
###
r740xd_calibre_web_book_dir: null
r740xd_calibre_web_gid: null
r740xd_calibre_web_host_domain: null
r740xd_calibre_web_hostname: "calibre-web"
r740xd_calibre_web_uid: null

###
### Cross-Seed
###
r740xd_cross_seed_api_key: null
r740xd_cross_seed_match_mode: "strict"
r740xd_cross_seed_prowlarr_api_key: null
r740xd_cross_seed_prowlarr_indexer_ids: []
r740xd_cross_seed_qbittorrrent_url: null
r740xd_cross_seed_radarr1080_apikey: null
r740xd_cross_seed_radarr4k_apikey: null
r740xd_cross_seed_sonarr1080_apikey: null
r740xd_cross_seed_sonarr4k_apikey: null

###
### Docker
###

# List of users who should be added to the docker group.
r740xd_docker_users: []

##########

# Base domain name for machine and containers running on it.
r740xd_domain_name: "host.subdomain.example.com"

# Base domain the entire site / location.
r740xd_site_domain: "subdomain.example.com"

###
### EMQX
###
r740xd_emqx_admin_username: null
r740xd_emqx_admin_password: null
r740xd_emqx_docker_name: "emqx"
r740xd_emqx_hass_password: null
r740xd_emqx_host_domain: null
r740xd_emqx_http_port: "18083"
r740xd_emqx_prometheus_username: null
r740xd_emqx_prometheus_password: null
r740xd_emqx_tcp_port: "1883"
r740xd_emqx_ws_port: "9001"
r740xd_emqx_zigbee2mqtt_password: null

# List of dictionaries of Linux groups to create. Each entry in the list should be a dictionary
# in the form to match ansible.builtin.group.
# Example:
#   r740xd_groups:
#     - name: "group1"
#     - name: "group2"
#       gid: 4200
#     - name: "group3"
#       system: true
r740xd_groups: []

###
### Home Assistant
###
r740xd_hass_ecowitt_hass_auth_token: null
r740xd_hass_ecowitt_hass_webhook_id: null
r740xd_hass_host_domain: null
r740xd_hass_host_name: "hass"
r740xd_hass_latitude: null
r740xd_hass_longitude: null
r740xd_hass_matter_device: null
r740xd_hass_otbr_auto_update_firmware: false
r740xd_hass_otbr_device_baudrate: "460800"
r740xd_hass_otbr_device_flow_control: false
r740xd_hass_otbr_enable_firewall: true
r740xd_hass_otbr_enable_nat64: true
r740xd_hass_otbr_enable_thread_1_4: false
r740xd_hass_otbr_enable_webui: true
r740xd_hass_otbr_iface: "eth0"
r740xd_hass_otbr_log_level: "info"
r740xd_hass_zigbee_device: null
r740xd_hass_timezone: null
r740xd_hass_zwave_device: null

###
### Kometa
###
r740xd_kometa_cpus: "2"
r740xd_kometa_memory: "2G"
r740xd_kometa_libraries: null 
r740xd_kometa_mdblist_apikey: null
r740xd_kometa_plex_token: null
r740xd_kometa_plex_url: null
r740xd_kometa_run_once_only: false
r740xd_kometa_tautulli_apikey: null
r740xd_kometa_tmdb_apikey: null
r740xd_kometa_trakt: null

###
### Lidarr
###
r740xd_lidarr_cpus: "3"
r740xd_lidarr_host_domain: null

###
### Navidrome
###
r740xd_navidrome_host_name: "navi"
r740xd_navidrome_host_domain: null
r740xd_navidrome_lastfm_apikey: null
r740xd_navidrome_lastfm_secret: null
r740xd_navidrome_music_folder: null
r740xd_navidrome_spotify_client_id: null
r740xd_navidrome_spotify_client_secret: null

###
### Network
###
r740xd_network_vlan_address:
  default: null
  servers: null

###
### Plex
###
r740xd_plex_container_name: "plex"
r740xd_plex_claim: null
r740xd_plex_cpus: 8
r740xd_plex_memory: "4GB"
r740xd_plex_network_name: null
r740xd_plex_network_ipv4: null
r740xd_plex_music_path: null
r740xd_plex_old_music_path: null
r740xd_plex_videos_path: null

###
### Prometheus
###
r740xd_prometheus_host_domain: null

###
### Prowlarr
###
r740xd_prowlarr_host_domain: null

###
### Radarr
###
r740xd_radarr_cpus: "3"
r740xd_radarr_movie_source_path: null
r740xd_radarr_web_port: null # optional
r740xd_radarr1080_api_key: null
r740xd_radarr1080_host_domain: null
r740xd_radarr4k_api_key: null
r740xd_radarr4k_host_domain: null

###
### Readarr
###
r740xd_readarr_api_key: null
r740xd_readarr_host_domain: null
r740xd_readarr_library_path: null

###
### Sabnzbd
###
r740xd_sabnzbd_host_domain: null

###
### Samba
###
# Dictionary of user names to comma separated lists of additional group names.
# See documentation for samba_docker_extra_user_groups.
r740xd_samba_extra_user_groups: {}

# Dictionary of group names to GIDs.
# See documentation for samba_docker_gids
r740xd_samba_group_ids: {}

# Comma separated list of subnets to allow access to the Samba server.
r740xd_samba_hosts_allow: null

# IPv4 address of the Samba server.
r740xd_samba_network_ipv4: null

# Dictionary of unique share ids to Samba share details.
# See documentation for samba_docker_shares
r740xd_samba_shares:
  "books": |
    [books]
    path = "/shares/books"
    browsable = yes
    guest ok = no
    valid users = +book_writer
    write list = +book_writer
  "documents": |
    [documents]
    path = "/shares/documents"
    browsable = yes
    guest ok = no
    valid users = +doc_writer
    write list = +doc_writer
  "music": |
    [music]
    path = "/shares/music"
    browsable = yes
    guest ok = no
    valid users = +music_writer
    write list = +music_writer
  "musicold": |
    [music old]
    path = "/shares/music-old"
    browsable = yes
    guest ok = no
    valid users = +music_writer
    write list = +music_writer
  "musictodo": |
    [music todo]
    path = "/shares/music-todo"
    browsable = yes
    guest ok = no
    valid users = +music_writer
    write list = +music_writer
  "photos": |
    [photos]
    path = "/shares/photos"
    browsable = yes
    guest ok = no
    valid users = +photo_writer
    write list = +photo_writer
  "roms": |
    [roms]
    path = "/shares/roms"
    browsable = yes
    guest ok = no
    valid users = +rom_writer
    write list = +rom_writer
  "videos": |
    [videos]
    path = "/shares/videos"
    browsable = yes
    guest ok = no
    valid users = +media_writer
    write list = +media_writer

# Dictionary mapping source folders on the host to mount points in the container.
r740xd_samba_share_mounts:
  "/nas-mirror/books": "/shares/books"
  "/nas-mirror/documents": "/shares/documents"
  "/nas-mirror/music": "/shares/music"
  "/nas-mirror/music-old": "/shares/music-old"
  "/nas-mirror/music-todo": "/shares/music-todo"
  "/nas-mirror/photos": "/shares/photos"
  "/nas-mirror/roms": "/shares/roms"
  "/data/servarr/downloads/torrents/": "/shares/torrentz"
  "/data/videos": "/shares/videos"

# Dictionary of user names to create and the associated passwords.
# See documentation for samba_docker_accounts
r740xd_samba_user_acounts: {}

# Dictionary of user names to UIDs.
# See documentation for samba_docker_uids
r740xd_samba_user_ids: {}

###
### Saurron
###
r740xd_saurron_docker_name: "saurron"
r740xd_saurron_host_domain: null
r740xd_saurron_http_api_port: "8080"

###
### Seerr
###
r740xd_seerr_host_domain: null

###
### Servarr
###
r740xd_servarr_cloudflared_token: null
r740xd_servarr_path: null
r740xd_servarr_tv_source_path: null
r740xd_servarr_zfs_dataset: null

###
### Sonarr
###
r740xd_sonarr_cpus: "3"
r740xd_sonarr_web_port: null # optional
r740xd_sonarr1080_api_key: null
r740xd_sonarr1080_host_domain: null
r740xd_sonarr4k_api_key: null
r740xd_sonarr4k_host_domain: null

###
### SyncThing
###
r740xd_syncthing_host_domain: null

###
### Tautulli
###
r740xd_tautulli_container_name: "tautulli"
r740xd_tautulli_hostname: "tautulli"
r740xd_tautulli_host_domain: null

###
### TimeMachine
###
r740xd_time_machine_data_directory: null
r740xd_time_machine_hostname: "time-machine"
r740xd_time_machine_groupname: "time-machine"
r740xd_time_machine_gid: 1311
r740xd_time_machine_password: null
r740xd_time_machine_username: "time-machine"
r740xd_time_machine_uid: 1311
r740xd_time_machine_zfs_dataset: null

###
### Traefik
###
r740xd_traefik_letsencrypt_ca_server: "{{ letsencrypt_ca_server_prod }}"
r740xd_traefik_letsencrypt_email: null
r740xd_traefik_data_volume_name: "traefik-data"

###
### Traefik3 Controller
###

# List of middleware names 
r740xd_traefik3_dashboard_middleware_names: null

# Map of label names to values
r740xd_traefik3_dashboard_middleware_labels: {}

# Include a global redirect to https
r740xd_traefik3_redirect_http: true

# Dictionary of Provider options.
# https://doc.traefik.io/traefik/reference/install-configuration/providers/overview/
r740xd_traefik3_conf_providers: 
  docker:
    defaultRule: "Host(`traefik.r740xd.home.bealetech`)"
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    constraints: "Label(`org.opencontainers.image.title`, `Traefik`) && LabelRegex(`org.opencontainers.image.version`, `^v3.*`)"

# Dictionary of TLS certificate resolver options.
# https://doc.traefik.io/traefik/reference/install-configuration/tls/certificate-resolvers/overview/
r740xd_traefik3_conf_cert_resolvers:
  letsencrypt:
    acme:
      caServer: "{{ letsencrypt_ca_server_prod }}"
      dnsChallenge:
        provider: "route53"
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53" # Use external DNS to verify TXT record changes

###
### UniFi Controller
###
r740xd_unific_cpus: "2"
r740xd_unific_hostname: "unific"
r740xd_unific_host_domain: null
r740xd_unific_memory: "2G"


##########

r740xd_timezone: "America/New_York"

# List of dictionaries of Linux users to create. Each entry in the list should be a dictionary
# in the form to match ansible.builtin.user.
r740xd_users: []