---
- name: Install avahi
  apt:
    name: "avahi-daemon"
    state: present
  register: result
  until: result is succeeded

- name: Setup timemachine service for avahi
  template:
    src: timemachine.service
    dest: "/etc/avahi/services/timemachine.service"
    mode: 0644

- name: Reload avahi configuration
  service:
    name: avahi-daemon
    state: reloaded