---
- name: Create time-machine group
  ansible.builtin.group:
    name: "{{ timemachine_group }}"
    gid: "{{ timemachine_gid }}"
    state: present

- name: Create time-machine user
  ansible.builtin.user:
    name: "{{ timemachine_user }}"
    uid: "{{ timemachine_uid }}"
    state: present
    password: "*"
    update_password: always
    create_home: no
    group: "{{ timemachine_group }}"

- name: Time Machine Directories
  file:
    path: "{{ timemachine_data_directory }}"
    state: directory
    mode: 0750

- name: Time Machine Docker Container
  docker_container:
    name: timemachine
    image: awlnx/samba-timemachine:latest
    pull: true
    ports:
      - "{{ timemachine_port }}:445"
    env:
      TMSIZE: "{{ timemachine_volume_size_limit }}"
      PASS: "{{ timemachine_password }}"
      SHARENAME: "{{ timemachine_share_name }}"
      USERID: "{{ timemachine_uid }}"
      GROUPID: "{{ timemachine_gid }}"
    volumes:
      - "{{ timemachine_data_directory }}/data:/backups"
    ulimits:
      - "nofile:1048576:1048576"
    network_mode: bridge
    restart_policy: unless-stopped
    memory: 1g
    container_default_behavior: no_defaults
    auto_remove: no
    detach: yes
    init: no
    interactive: no
    paused: no
    privileged: no
    read_only: no
    tty: no
