---
telegraf_influxdb_url: "http://influxdb.example.com:8086"
telegraf_influxdb_token: "secret-token"
telegraf_influxdb_org: "my-org"

telegraf_tags:

telegraf_agent_interval: 10s
telegraf_round_interval: "true"
telegraf_metric_batch_size: "1000"
telegraf_metric_buffer_limit: "10000"

telegraf_collection_jitter: 0s
telegraf_flush_interval: 10s
telegraf_flush_jitter: 0s
telegraf_debug: "false"
telegraf_quiet: "false"
telegraf_hostname:
telegraf_omit_hostname: "false"

telegraf_logging_debug: false
telegraf_logging_file: ""
telegraf_logfile_rotation_interval: ""
telegraf_logfile_rotation_max_size: ""
telegraf_logfile_rotation_max_archives: 5

telegraf_snmp_firewall: "host1.example.com"
telegraf_snmp_firewall_community: "secret"
telegraf_snmp_firewall_interval: "30s"

telegraf_snmp_net: ["192.168.1.1"]
telegraf_snmp_net_community: "secret"
telegraf_snmp_net_interval: "30s"

telegraf_plugin_docker: false
telegraf_plugin_influxdb2_v2_port: "8086"
telegraf_plugin_influxdb2_v2_tls_cert: "/etc/telegraf/cert.pem"
telegraf_plugin_influxdb2_v2_tls_key: "/etc/telegraf/key.pem"
telegraf_plugin_influxdb2_v2_token: "some-long-shared-secret-token"
telegraf_plugin_smartctl: false
telegraf_plugin_zfs_pool_sizes: false

telegraf_plugins_base:
  - name: mem
  - name: system
  - name: cpu
    options:
      percpu: "true"
      totalcpu: "true"
      fielddrop:
        - "time_*"
  - name: temp
  # - name: disk
  #   options:
  #     mountpoints:
  #       - "/"
  - name: diskio
    options:
      skip_serial_number: "true"
  # - name: procstat
  #   options:
  #     exe: "influxd"
  #     prefix: "influxdb"
  # - name: net
  #   options:
  #     interfaces:
  #       - "eth0"

telegraf_plugins: "{{ telegraf_plugins_base }} + {{ telegraf_plugins_extra | default([]) }}"
