- import_tasks: setup.yml
  tags:
    - grafana
    - grafana:setup
    - grafana_docker
    - grafana_docker:setup

- import_tasks: docker.yml
  tags:
    - grafana
    - grafana:docker
    - grafana_docker
    - grafana_docker:docker