---
- name: Create ZFS file systems
  community.general.zfs:
    name: "{{ item }}"
    state: present
  loop: "{{ grafana_docker_zfs_filesystems }}"

- name: Create Grafana user
  ansible.builtin.user:
    name: "{{ grafana_docker_username }}"
    uid: "{{ grafana_docker_uid | default(omit) }}"
    create_home: "false"
    password: "!"

- name: Create Grafana directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ grafana_docker_username }}"
    group: "root"
    mode: "0770"
    state: "directory"
  loop:
    - "{{ grafana_docker_config_dir }}"

- name: Set ZFS FS ownership
  ansible.builtin.file:
    path: "/mnt/{{ item }}"
    owner: "{{ grafana_docker_username }}"
    group: "root"
    mode: "0770"
  loop: "{{ grafana_docker_zfs_filesystems }}"

- name: Create Grafana config
  ansible.builtin.template:
    src: ../templates/grafana.ini.j2
    dest: "{{ grafana_docker_config_dir }}/grafana.ini"
  notify:
    - Restart Grafana
