---
###
### Docker
###
nas_docker_zfs_dataset: "nas/data/docker"
nas_docker_home: "/mnt/{{ nas_docker_zfs_dataset }}"

###
### Veggie Common
###
veggie_base_domain_name: "{{ veggie_domain }}"
veggie_domain: "{{ vault_veggie_domain }}"
veggie_fqdn: "{{ veggie_hostname }}.{{ veggie_domain }}"
veggie_hostname: "{{ vault_veggie_hostname }}"
veggie_nas_domain_name: "{{ veggie_fqdn }}"
