---
- name: Configure Home Assistant
  hosts: homeassistant
  remote_user: pi
  become: yes

  tasks:
    - name: Synchronize config files
      ansible.posix.synchronize:
        src: ~/src/hass-config/
        dest: /var/lib/hass-config/
        archive: no
        delete: yes
        group: no
        owner: no
        partial: yes
        recursive: yes
        times: yes
        rsync_opts:
          - "--exclude=.cloud"
          - "--exclude=.DS_Store"
          - "--exclude=.git"
          - "--exclude=.google.token"
          - "--exclude=.HA_VERSION"
          - "--exclude=.storage"
          - "--exclude=deps"
          - "--exclude=google_calendars.yaml"
          - "--exclude=harmony_*.conf"
          - "--exclude=home-assistant_v2.db"
          - "--exclude=OZW_Log.txt"
          - "--exclude=options.xml"
          - "--exclude=tts"
          - "--exclude=zwcfg*.xml"
          - "--exclude=zwscene.xml"
          - "--exclude=__pycache__"
          - "--exclude=*.log"
          - "--exclude=*.pyc"
          - "--exclude=*.sqlite"
