all:
  hosts:  
    r720xd.350mva.xyz:
    r740xd:
      ansible_host: r740xd.350mva.xyz
    z690:

desktop:
  hosts:
    z690:
dev_env:
  hosts:
    z690:
nfs:
  hosts:
    r740xd:
      ansible_host: r740xd.350mva.xyz
nfs_server:
  hosts:
    r740xd:
      ansible_host: r740xd.350mva.xyz
r720:
  hosts:
    r720xd.350mva.xyz:
veggie_nas:
  hosts:
    r720xd.350mva.xyz:
    r740xd:
      ansible_host: r740xd.350mva.xyz
