all:
  hosts:  
    desktop:
    r720xd.350mva.xyz:
    r740xd:
    speedtest:
    z690:

desktop:
  hosts:
    desktop:
dev_env:
  hosts:
    z690:
nfs:
  hosts:
    r740xd:
nfs_server:
  hosts:
    r740xd:
r720:
  hosts:
    r720xd.350mva.xyz:
speedtests:
  hosts:
    speedtest:
  vars:
    ansible_user: pi
veggie_nas:
  hosts:
    r720xd.350mva.xyz:
    r740xd:

veggie_server:
  children:
    nfs_server:
    r720:
    veggie_nas: