all:
  hosts:  
    desktop:
    r720xd:
    r740xd:
    speedtest:
    z690:

desktop:
  hosts:
    desktop:
dev_env:
  hosts:
    z690:
nfs:
  hosts:
    r740xd:
nfs_server:
  hosts:
    r740xd:
speedtests:
  hosts:
    speedtest:
  vars:
    ansible_user: pi
veggie_nas:
  hosts:
    r720xd:
    r740xd:
