all:
  hosts:  
    dock
    nas
    speedtest
    desktop
    z690
  children:
    desktop:
      hosts:
        desktop:
    dev_env:
      hosts:
        z690:
    nfs:
      hosts:
        nas:
        dock:
    nfs_server:
      hosts:
        nas:
    nfs_client:
      hosts:
        dock:
    speedtests:
      hosts:
        speedtest:
      vars:
        ansible_user: pi
    veggie_nas:
      hosts:
        nas:
    veggie_virt:
      hosts:
        dock: