---
- name: Setup Veggie NAS
  hosts: veggie_nas
  remote_user: sean
  become: yes
  vars_files:
    - vars/user_groups
    - vars/users
  roles:
    - role: groupadd
    - role: organicveggie.ansible-users
      tags:
        - users
        - skip_ansible_lint
    - role: organicveggie.folders
      tags:
        - folders
        - skip_ansible_lint
    - role: geerlingguy.pip
      tags:
        - pip
    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint
    - role: veggie_common
    - role: docker_networks
    - role: veggie_nas
    - role: bertvv.samba
      tags:
        - samba
        - skip_ansible_lint
    - role: geerlingguy.nfs
      tags:
        - nfs_server
        - skip_ansible_lint
    - role: portainer
    - role: glances
    - role: time_machine
    - role: influxdb_docker
    - role: plex_docker
    - role: stefangweichinger.ansible_rclone
      tags:
        - rclone
        - skip_ansible_lint
    - role: nickhammond.logrotate
      tags:
        - logrotate
        - skip_ansible_lint
    - role: veggie_nas_rclone
    - role: organicveggie.certbot-route53
    - role: restic_rest_server
    - role: nodered
    - role: diun
    - role: calibre_web
    - role: grafana_docker
    - role: photoprism
    - role: organicveggie.unific
      tags:
        - unific
    # - role: postgresl_docker
    # - role: pgadmin_docker
    # - role: zwavejs2mqtt
    - role: organicveggie.ansible-traefik
      tags:
        - traefik
    - role: telegraf
