---
- name: "Setup Veggie NAS"
  hosts: "veggie_nas"
  become: yes
  # roles:
    # - role: stefangweichinger.ansible_rclone
    #   tags:
    #     - rclone
    #     - skip_ansible_lint
    # - role: veggie_nas_rclone
    # - role: organicveggie.certbot-route53
    # - role: restic_rest_server
    # - role: grafana_docker
    # - role: photoprism
    # - role: organicveggie.unific
    #   tags:
    #     - unific
    # - role: telegraf

- ansible.builtin.import_playbook: "playbooks/nas-users-groups.yml"
  tags: ["users", "groups"]

- ansible.builtin.import_playbook: "playbooks/common.yml"
  tags: ["common"]

- ansible.builtin.import_playbook: "playbooks/docker.yml"
  tags: ["docker", "portainer"]

- ansible.builtin.import_playbook: "playbooks/diun.yml"
  tags: ["diun"]

- ansible.builtin.import_playbook: "playbooks/glances.yml"
  tags: ["glances"]

- ansible.builtin.import_playbook: "playbooks/hass.yml"
  tags: ["hass", "homeassistant", "home-assistant"]

- ansible.builtin.import_playbook: "playbooks/node-red.yml"
  tags: ["nodered", "node-red"]

- ansible.builtin.import_playbook: "playbooks/influxdb.yml"
  tags: ["influxdb"]

##########
# Traefik - Needs to be last so all of the networks exist
##########
- ansible.builtin.import_playbook: "playbooks/traefik.yml"
  tags: ["traefik"]
