---
- name: Setup Veggie NAS
  hosts: veggie_nas
  remote_user: sean
  become: yes
  roles:
    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint
    - role: geerlingguy.pip
      tags:
        - pip
    - role: veggie_nas
    - role: bertvv.samba
      tags:
        - samba
        - skip_ansible_lint
    - role: arillso.traefik
      tags:
        - traefik
    - role: shelleg.ansible_role_portainer
      tags:
        - portainer
        - skip_ansible_lint
    - role: glances
    - role: time_machine
    - role: plex_docker
    - role: stefangweichinger.ansible_rclone
      tags:
        - rclone
        - skip_ansible_lint
    - role: nickhammond.logrotate
      tags:
        - logrotate
        - skip_ansible_lint
    - role: veggie_nas_rclone
    - role: restic_rest_server
