---
- name: "Setup Veggie NAS"
  hosts: "veggie_nas"
  become: yes
  # roles:
    # - role: stefangweichinger.ansible_rclone
    #   tags:
    #     - rclone
    #     - skip_ansible_lint
    # - role: veggie_nas_rclone
    # - role: organicveggie.certbot-route53
    # - role: restic_rest_server
    # - role: grafana_docker
    # - role: photoprism
    # - role: organicveggie.unific
    #   tags:
    #     - unific
    # - role: telegraf

- ansible.builtin.import_playbook: "nas-users-groups.yml"
  tags: ["users", "groups"]

- ansible.builtin.import_playbook: "common.yml"
  tags: ["common"]

- ansible.builtin.import_playbook: "docker.yml"
  tags: ["docker", "portainer"]

- ansible.builtin.import_playbook: "samba.yml"
  tags: ["samba"]

- ansible.builtin.import_playbook: "time-machine.yml"
  tags: ["time-machine", "timemachine", "tim"]

# - ansible.builtin.import_playbook: "playbooks/media-storage/media-storage.yml"
#   tags: ["media", "media-storage"]

- ansible.builtin.import_playbook: "playbooks/calibre-web.yml"
  tags: ["calibre", "calibre-web", "calibre-web"]

- ansible.builtin.import_playbook: "playbooks/diun.yml"
  tags: ["diun"]

- ansible.builtin.import_playbook: "playbooks/glances.yml"
  tags: ["glances"]

- ansible.builtin.import_playbook: "playbooks/hass.yml"
  tags: ["hass", "homeassistant", "home-assistant"]

- ansible.builtin.import_playbook: "playbooks/navidrome.yml"
  tags: ["navidrome"]

- ansible.builtin.import_playbook: "playbooks/node-red.yml"
  tags: ["nodered", "node-red"]

- ansible.builtin.import_playbook: "playbooks/plex.yml"
  tags: ["plex", "pms", "plex-docker", "plex_docker"]

- ansible.builtin.import_playbook: "playbooks/kometa.yml"
  tags: ["kometa", "pmm", "plex-media-manager"]

- ansible.builtin.import_playbook: "playbooks/tautulli.yml"
  tags: ["tautulli"]

- ansible.builtin.import_playbook: "playbooks/servarr.yml"
  tags: ["servarr"]

- ansible.builtin.import_playbook: "playbooks/influxdb.yml"
  tags: ["influxdb"]

##########
# Traefik - Needs to be last so all of the networks exist
##########
- ansible.builtin.import_playbook: "traefik.yml"
  tags: ["traefik"]
