---
- name: "Setup Veggie NAS"
  hosts: "veggie_nas"
  become: yes
  vars_files:
    - "vars/user_groups"
    - "vars/users"
  roles:
    - role: groupadd
    - role: organicveggie.ansible-users
      tags:
        - users
        - skip_ansible_lint
    - role: organicveggie.folders
      tags:
        - folders
        - skip_ansible_lint
    - role: geerlingguy.pip
      tags:
        - pip
    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint
    - role: veggie_common
    - role: docker_networks
    - role: veggie_nas
    - role: vladgh.samba.server
      tags:
        - samba
        - skip_ansible_lint
    - role: geerlingguy.nfs
      tags:
        - nfs_server
        - skip_ansible_lint
    - role: portainer
    - role: glances
    - role: time_machine
    - role: influxdb_docker
    - role: plex_docker
    - role: stefangweichinger.ansible_rclone
      tags:
        - rclone
        - skip_ansible_lint
    - role: nickhammond.logrotate
      tags:
        - logrotate
        - skip_ansible_lint
    - role: veggie_nas_rclone
    - role: organicveggie.certbot-route53
    - role: restic_rest_server
    - role: nodered
    - role: diun
    - role: calibre_web
    - role: grafana_docker
    - role: photoprism
    - role: organicveggie.unific
      tags:
        - unific
    # - role: postgresl_docker
    # - role: pgadmin_docker
    # - role: zwavejs2mqtt
    - role: organicveggie.tautulli_docker
    - role: organicveggie.pmm_docker

    # Resilio Sync
    - role: "groupadd"
      tags: ["resilio", "groups"]
      vars:
        user_groups:
          - name: "{{ resilio_docker_group_name }}"
            gid: "{{ resilio_docker_gid }}"
            system: "false"
            state: "present"
    - role: "organicveggie.ansible-users"
      tags: ["resilio", "users"]
      vars:
        users:
          - username: "{{ resilio_docker_user_name }}"
            uid: "{{ resilio_docker_uid }}"
            group: "{{ resilio_docker_group_name }}"
            password: "*"
            groups: ["media_writer"]
            append: yes
            home_create: no
            system: no
            authorized_keys: []
            authorized_keys_exclusive: yes
            shell: "/bin/false"
    - role: "organicveggie.folders"
      tags: ["resilio", "folders"]
      vars:
        organicveggie_folders_create:
          - path: "{{ resilio_docker_torrentz_dir }}"
            state: "directory"
            mode: "0775"
            owner: "resilio"
            group: "media_writer"
    - role: docker_networks
      tags: ["resilio", "docker"]
      vars:
        organicveggie_docker_networks:
          - name: "{{ resilio_docker_network }}"
            enable_ipv6: "no"
            internal: "no"
            scope: "local"
            subnet: "{{ resilio_docker_network_subnet }}"
            gateway: "{{ resilio_docker_network_gateway }}"
    - role: "organicveggie.resilio_sync_docker"
      tags: ["resilio"]

    # Traefik
    - role: organicveggie.ansible-traefik
      tags:
        - traefik

    # Telegraf
    - role: telegraf
