---
- name: "Setup Veggie NAS"
  hosts: "veggie_nas"
  become: yes
  vars_files:
    - "vars/user_groups"
    - "vars/users"
  roles:
    - role: groupadd
    - role: organicveggie.ansible-users
      tags:
        - users
        - skip_ansible_lint
    - role: organicveggie.folders
      tags:
        - folders
        - skip_ansible_lint
    - role: geerlingguy.pip
      tags:
        - pip
    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint
    - role: veggie_common
    - role: docker_networks
    - role: veggie_nas
    - role: vladgh.samba.server
      tags:
        - samba
        - skip_ansible_lint
    - role: geerlingguy.nfs
      tags:
        - nfs_server
        - skip_ansible_lint
    - role: portainer
    - role: time_machine
    - role: influxdb_docker
    - role: stefangweichinger.ansible_rclone
      tags:
        - rclone
        - skip_ansible_lint
    - role: nickhammond.logrotate
      tags:
        - logrotate
        - skip_ansible_lint
    - role: veggie_nas_rclone
    - role: organicveggie.certbot-route53
    - role: restic_rest_server
    - role: grafana_docker
    - role: photoprism
    - role: organicveggie.unific
      tags:
        - unific

    - role: organicveggie.tautulli_docker
    - role: organicveggie.pmm_docker

    # Telegraf
    - role: telegraf

- ansible.builtin.import_playbook: "playbooks/media-storage/media-storage.yml"
  tags: ["media", "media-storage"]

- ansible.builtin.import_playbook: "playbooks/calibre-web.yml"
  tags: ["calibre", "calibre-web", "calibre-web"]

- ansible.builtin.import_playbook: "playbooks/diun.yml"
  tags: ["diun"]

- ansible.builtin.import_playbook: "playbooks/glances.yml"
  tags: ["glances"]

- ansible.builtin.import_playbook: "playbooks/hass.yml"
  tags: ["hass", "homeassistant", "home-assistant"]

- ansible.builtin.import_playbook: "playbooks/node-red.yml"
  tags: ["nodered", "node-red"]

- ansible.builtin.import_playbook: "playbooks/plex.yml"
  tags: ["plex", "pms", "plex-docker", "plex_docker"]

- ansible.builtin.import_playbook: "playbooks/resilio-sync.yml"
  tags: ["resilio"]

- ansible.builtin.import_playbook: "playbooks/servarr.yml"
  tags: ["servarr"]

##########
# Traefik - Needs to be last so all of the networks exist
##########
- ansible.builtin.import_playbook: "playbooks/traefik.yml"
  tags: ["traefik"]
