---
- name: Setup Veggie NAS
  hosts: nas
  remote_user: sean
  become: yes
  roles:
    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint
    - role: veggie_nas
    - role: bertvv.samba
      tags:
        - samba
        - skip_ansible_lint
    - role: heimdall
    - role: glances