---
- name: Setup Speed Test
  hosts: speedtest
  remote_user: pi
  become: yes
  roles:
    # - snmp_mibs
    - role: telegraf
      vars:
        telegraf_snmp_net: ["192.168.25.3:161", "192.168.25.4:161", "192.168.25.180:161", "192.168.25.181:161"]
    - speedtest_cli
    - speedtest_telegraf

  vars:
    telegraf_logging_debug: false
    telegraf_logging_file: "/var/log/telegraf/telegraf.log"
    telegraf_logfile_rotation_max_size: "20MB"
    telegraf_collection_jitter: 1s
    telegraf_plugins_extra:
     - name: ping
       options:
        urls: ["{{ telegraf_ping_host1 }}", "{{ telegraf_ping_host2 }}", "www.google.com", "8.8.8.8", "75.75.75.75"]
        method: "exec"
        interval: "120s"
        count: 10
        ping_interval: 1.0
        timeout: 3.0
        deadline: 10
        binary: "/usr/bin/ping"
     - name: snmp_trap
       options:
        service_address: "udp://:{{ telegraf_snmp_trap_port }}"
