---
- name: Setup Veggie Virt
  hosts: veggie_virt
  remote_user: sean
  become: yes
  vars_files:
    - vars/user_groups
    - vars/users
  roles:
    - role: groupadd
    - role: organicveggie.ansible-users
      tags:
        - users
        - skip_ansible_lint
    - role: nfs_client
    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint
    - role: geerlingguy.pip
      tags:
        - pip
    - role: veggie_common
    - role: veggie_docker
    - role: veggie_virt
    - role: organicveggie.ansible-traefik
      tags:
        - traefik
    - role: portainer
    - role: glances
    - role: organicveggie.unific
      tags:
        - unific
    - role: calibre_web
    - role: grafana_docker
    - role: postgresql_docker
    - role: pgadmin_docker
    - role: homeassistant_docker
    - role: nickhammond.logrotate
      tags:
        - logrotate
        - skip_ansible_lint
