---
#####
# Container settings
#####

# Name of the Docker container.
overseerr_docker_name: "overseerr"

# Base name of the Docker image to use for the container.
overseerr_docker_image: "sctx/overseerr"

# Specific Docker image version to use for the container.
overseerr_docker_image_version: "latest"

# Timezone to use inside the container.
overseerr_docker_timezone: "America/New_York"

overseerr_docker_volume_config_name: "overseerr-config"

# Number of vCPUs to allocate to the container.
overseerr_docker_cpus: "1"

# Amount of memory to allocate to the container.
overseerr_docker_memory: "512M"

# TCP port number to expose to handle HTTP traffic for overseerr desktop gui.
overseerr_docker_web_port: "5055"

# Dictionary of extra key value pairs to set as labels on the Docker container.
overseerr_docker_extra_labels: {}

# Dict of host-to-IP mappings, where each host name is a key in the dictionary. Each host name will
# be added to the container’s /etc/hosts file.
overseerr_docker_extra_hosts: {}

# Default Docker network.
overseerr_docker_network: "servarr"

# List of additional networks the container should attach to. Elements should be dictionaries like
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-networks.
overseerr_docker_extra_networks: []

# List of aliases for this container in the default network. These names can be used in the default
# network to reach this container.
overseerr_docker_network_aliases: []

overseerr_docker_log_level: "INFO"

#####
# Traefik
#####

# Enable use of Traefik as a proxy.
overseerr_docker_available_externally: "true"

# Host name to use for the Traefik endpoint. Combined with [overseerr_docker_host_domain] to form the
# FQDN for the endpoint.
overseerr_docker_host_name: "overseerr"

# Domain name to use for the Traefik endpoint. Combined with [overseerr_docker_host_name] to form the
# FQDN for the endpoint. Also used by Traefik to create the necessary Let's Encrypt certificate.
overseerr_docker_host_domain: "example.com"
