---
- src: https://github.com/organicveggie/ansible.traefik
  name: organicveggie.ansible-traefik
  version: "master"

- src: bertvv.samba
  version: v2.7.1

- src: geerlingguy.docker
  version: 3.0.0

- src: geerlingguy.nfs
  version: 2.0.0

- src: stefangweichinger.ansible_rclone

- src: nickhammond.logrotate
