---
- src: "https://github.com/organicveggie/ansible.traefik"
  name: "organicveggie.ansible-traefik"
  version: "2.0.0"

- src: "https://github.com/organicveggie/ansible-role-certbot-route53"
  name: "organicveggie.certbot-route53"
  version: "1.0.0"

- src: "https://github.com/organicveggie/ansible-role-folders"
  name: "organicveggie.folders"
  version: "1.0.0"
  # version: "2.0.0"

- src: "https://github.com/organicveggie/ansible.unific"
  name: "organicveggie.unific"
  version: "2.1"

- src: "gantsign.visual-studio-code"
  version: "6.10.0"

- src: "geerlingguy.docker"
  version: "6.0.4"

- src: "geerlingguy.nfs"
  version: "2.0.0"

- src: "geerlingguy.pip"
  version: "2.2.0"

- src: "https://github.com/organicveggie/ansible.calibre_web_docker"
  name: "organicveggie.calibre_web_docker"
  version: "1.0.2"

- src: "https://github.com/organicveggie/ansible.home_assistant_docker"
  name: "organicveggie.home_assistant_docker"
  version: "1.0.6"

- src: "organicveggie.pgadmin_docker"
  version: "1.0.3"

- src: "https://github.com/organicveggie/ansible.pmm_docker"
  name: "organicveggie.pmm_docker"
  version: "1.1.0"

- src: "organicveggie.postgres_docker"
  version: "1.0.2"

- src: "https://github.com/organicveggie/ansible.resilio_sync_docker"
  name: "organicveggie.resilio_sync_docker"
  version: "1.0.2"

- src: "organicveggie.tautulli_docker"
  version: "1.0.2"

- src: "organicveggie.vagrant"
  version: "1.0.0"

- src: "https://github.com/organicveggie/ansible.zwavejsui"
  name: "organicveggie.zwavejsui"
  version: "1.0.1"

- src: "stefangweichinger.ansible_rclone"

- src: "nickhammond.logrotate"

- src: "https://github.com/organicveggie/ansible.users"
  name: "organicveggie.ansible-users"
  version: "master"
