---
- src: bertvv.samba
  version: v2.7.1

- src: geerlingguy.docker
  version: 3.0.0

- src: geerlingguy.nfs
  version: 2.0.0

- src: shelleg.ansible_role_portainer

- src: stefangweichinger.ansible_rclone

- src: nickhammond.logrotate
