---
- name: Create PgAdmin group
  ansible.builtin.group:
    name: "{{ pgadmin_docker_group }}"
    gid: "{{ pgadmin_docker_guid }}"
    state: present

- name: Create PgAdmin user
  ansible.builtin.user:
    name: "{{ pgadmin_docker_user }}"
    uid: "{{ pgadmin_docker_uid }}"
    shell: /usr/bin/false
    state: present
    password: "*"
    update_password: always
    create_home: no
    group: "{{ pgadmin_docker_group }}"

- name: Create PgAdmin directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ pgadmin_docker_user }}"
    group: "{{ pgadmin_docker_group }}"
    mode: "0770"
    state: directory
  loop:
    - "{{ pgadmin_docker_dir }}"
    - "{{ pgadmin_docker_conf_dir }}"

- name: Define servers
  ansible.builtin.set_fact:
    pgadmin_docker_servers_yaml:
        Servers:
            "{{ pgadmin_docker_servers }}"

- name: Define servers json
  ansible.builtin.set_fact:
    pgadmin_docker_servers_json: "{{ pgadmin_docker_servers_yaml | to_nice_json(indent=2) }}"

# - name: Debug stuff
#   ansible.builtin.debug:
#     msg: "{{ pgadmin_docker_servers_json }}"

- name: Create servers.json
  ansible.builtin.template:
    src: "../templates/servers.json.j2"
    dest: "{{ pgadmin_docker_conf_dir }}/servers.json"
    owner: "{{ pgadmin_docker_user }}"
    group: "{{ pgadmin_docker_group }}"
    mode: "0660"
  when: pgadmin_docker_servers is defined
