---
#####
# Container settings
#####

# Name of the Docker container.
radarr_docker_name: "radarr"

# Base name of the Docker image to use for the container.
radarr_docker_image: "lscr.io/linuxserver/radarr"

# Specific Docker image version to use for the container.
radarr_docker_image_version: "latest"

# Group ID to use inside the container.
radarr_docker_gid: "1000"

# User ID to use inside the container.
radarr_docker_uid: "1000"

# Timezone to use inside the container.
radarr_docker_timezone: "America/New_York"

radarr_docker_data_source_path: "/data"
radarr_docker_movie_source_path: "/data/media/movies"

radarr_docker_volume_config_name: "radarr-config"

# Number of vCPUs to allocate to the container.
radarr_docker_cpus: "2"

# Amount of memory to allocate to the container.
radarr_docker_memory: "2GB"

# TCP port number to expose to handle HTTP traffic for radarr desktop gui.
radarr_docker_web_port: "7878"

# Dictionary of extra key value pairs to set as labels on the Docker container.
radarr_docker_extra_labels: {}

# Default Docker network.
radarr_docker_network: "servarr"

# List of additional networks the container should attach to. Elements should be dictionaries like
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-networks.
radarr_docker_extra_networks: []

# List of aliases for this container in the default network. These names can be used in the default
# network to reach this container.
radarr_docker_network_aliases: []

#####
# Traefik
#####

# Enable use of Traefik as a proxy.
radarr_docker_available_externally: "true"

# Host name to use for the Traefik endpoint. Combined with [radarr_docker_host_domain] to form the
# FQDN for the endpoint.
radarr_docker_host_name: "radarr"

# Domain name to use for the Traefik endpoint. Combined with [radarr_docker_host_name] to form the
# FQDN for the endpoint. Also used by Traefik to create the necessary Let's Encrypt certificate.
radarr_docker_host_domain: "example.com"

#####
# Ansible
#####

radarr_docker_role_label: "radarr-docker"