---
- name: "{{ hass_docker_role_label }} | Build container FQDN"
  ansible.builtin.set_fact:
    _hass_docker_fqdn: "{{ hass_docker_host_name }}.{{ hass_docker_host_domain }}"

- name: "{{ hass_docker_role_label }} | Build Home Assistant URL"
  ansible.builtin.set_fact:
    _hass_docker_url: "http://{{ hass_docker_host_name }}:{{ hass_docker_web_port }}"

- name: "{{ hass_docker_role_label }} |  Include Home Assistant tasks"
  ansible.builtin.import_tasks: "hass.yml"

- name: "{{ hass_docker_role_label }} |  Include Home Assistant Ecowitt Proxy tasks"
  ansible.builtin.import_tasks: "ecowitt.yml"