---
- name: "Create Lidarr Docker config volume"
  community.docker.docker_volume:
    name: "{{ lidarr_docker_volume_config_name }}"

- name: "Set Docker mount list for volume mounts"
  ansible.builtin.set_fact:
    _lidarr_docker_mount_list:
      - source: "{{ lidarr_docker_volume_config_name }}"
        target: "/config"
        type: "volume"
      - source: "{{ lidarr_docker_data_source_path }}"
        target: "/data"
        type: "bind"

- name: "Build container FQDN"
  ansible.builtin.set_fact:
    _lidarr_docker_fqdn: "{{ lidarr_docker_host_name }}.{{ lidarr_docker_host_domain }}"

- name: "Create placeholder array for default network"
  ansible.builtin.set_fact:
    _lidarr_docker_default_networks:
      - name: "{{ lidarr_docker_network }}"
        aliases: "{{ lidarr_docker_network_aliases | default(omit) }}"

- name: "Define all Docker networks for this container"
  ansible.builtin.set_fact:
    _lidarr_docker_all_networks: >
      {{ _lidarr_docker_default_networks + lidarr_docker_extra_networks }}

- name: "Define placeholder map for Docker labels"
  ansible.builtin.set_fact:
    _lidarr_docker_labels: {}

- name: "Define Docker labels with Traefik disabled"
  ansible.builtin.set_fact:
    _lidarr_docker_labels: "{{ _lidarr_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  with_items:
    - key: "traefik.enable"
      value: "{{ lidarr_available_externally }}"
  when: "not lidarr_available_externally"

- name: "Define Docker labels with Traefik enabled"
  ansible.builtin.set_fact:
    _lidarr_docker_labels: "{{ _lidarr_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  with_items:
    - key: "traefik.enable"
      value: "{{ lidarr_available_externally }}"
    - key: "traefik.docker.network"
      value: "{{ servarr_docker_network }}"
    - key: "traefik.http.routers.lidarr.rule"
      value: "Host(`{{ _lidarr_docker_fqdn }}`)"
    - key: "traefik.http.routers.lidarr.entrypoints"
      value: "http,https"
    - key: "traefik.http.routers.lidarr.tls.certresolver"
      value: "letsencrypt"
    - key: "traefik.http.routers.lidarr.tls.domains[0].main"
      value: "*.{{ lidarr_docker_host_domain }}"
    - key: "traefik.http.services.lidarr.loadbalancer.server.port"
      value: "{{ lidarr_docker_web_port }}"
  when: "lidarr_available_externally"

- name: "Define user-supplied extra Docker labels"
  ansible.builtin.set_fact:
    _lidarr_docker_labels: "{{ _lidarr_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  loop: "{{ lidarr_docker_extra_labels | dict2items }}"

- name: "Lidarr Docker Container"
  community.docker.docker_container:
    name: "{{ lidarr_docker_name }}"
    image: "{{ lidarr_docker_image }}:{{ lidarr_docker_image_version }}"
    pull: true
    env:
      "PUID": "{{ lidarr_docker_uid }}"
      "PGID": "{{ lidarr_docker_gid }}"
      "TZ": "{{ lidarr_docker_timezone }}"
    mounts: "{{ _lidarr_docker_mount_list }}"
    network_mode: "{{ lidarr_docker_network }}"
    networks: "{{ _lidarr_docker_all_networks }}"
    restart_policy: unless-stopped
    memory: "{{ lidarr_docker_memory }}"
    cpus: "{{ lidarr_docker_cpus }}"
    container_default_behavior: no_defaults
    auto_remove: no
    detach: yes
    init: false
    interactive: no
    paused: no
    privileged: no
    read_only: no
    tty: no
    labels: "{{ _lidarr_docker_labels }}"
