---
# vars file for r740xd
r740xd_extra_packages:
  - "smartmontools"
  - "htop"
  - "zfsutils-linux"
  - "bonnie++"
  - "unzip"
  - "lm-sensors"
  # TODO: https://github.com/bcicen/ctop?tab=readme-ov-file#install
  # - "ctop"
  - "mbuffer"
  - "net-tools"
  - "screen"
  - "tmux"

###
### Bazarr
### 1
r740xd_bazarr1080_config_volume_name: "bazarr1080-config"
r740xd_bazarr1080_container_name: "bazarr1080"
r740xd_bazarr1080_host_name: "bazarr1080"
r740xd_bazarr1080_network_aliases:
  - "bazarr1080"
r740xd_bazarr4k_config_volume_name: "bazarr4k-config"
r740xd_bazarr4k_container_name: "bazarr4k"
r740xd_bazarr4k_host_name: "bazarr4k"
r740xd_bazarr4k_network_aliases:
  - "bazarr4k"

###
### Calibre Web
###
r740xd_calibre_web_username: "calibre"
r740xd_calibre_web_groupname: "calibre"

###
### Diun
###
r740xd_diun_group: "diun"
r740xd_diun_uid: 2450
r740xd_diun_user: "diun"

###
### Docker
###
r740xd_docker_bridge_network_gateway: "172.17.0.1"

###
### Home Assistant
###
r740xd_hass_pgsql_image: "postgres:15-bullseye"
r740xd_hass_pgsql_name: "hass-pgsql"
r740xd_hass_pgsql_volume_conf_name: "hass-pgsql-conf"
r740xd_hass_pgsql_volume_data_name: "hass-pgsql-data"
r740xd_hass_pgsql_volume_init_name: "hass-pgsql-initscripts"

###
### InfluxDB
###
r740xd_influxdb_config_volume_name: "influxdb27-config"
r740xd_influxdb_data_volume_name: "influxdb27-data"

###
### Kometa
###
r740xd_kometa_mdblist_cache_expiration: "60"
r740xd_kometa_plex_db_cache: "2048" # MB
r740xd_kometa_run_time: "02:00"
r740xd_kometa_tmdb_language: "en"
r740xd_kometa_tmdb_region: "US"

###
### Navidrome
###
r740xd_navidrome_image_cache_size: "500MB"

###
### Plex
###
r740xd_plex_gid: 32400
r740xd_plex_groupname: "plex"
r740xd_plex_port: 32400
r740xd_plex_uid: 32400
r740xd_plex_username: "plex"

###
### Radarr
###
r740xd_radarr1080_config_volume_name: "radarr1080-config"
r740xd_radarr1080_container_name: "radarr1080"
r740xd_radarr1080_host_name: "radarr1080"
r740xd_radarr1080_network_aliases:
  - "radarr1080"
r740xd_radarr4k_config_volume_name: "radarr4k-config"
r740xd_radarr4k_container_name: "radarr4k"
r740xd_radarr4k_host_name: "radarr4k"
r740xd_radarr4k_network_aliases:
  - "radarr4k"

###
### Readarr
###
r740xd_readarr_host_name: "readarr"
r740xd_readarr_web_port: "8787"
  
###
### Servarr
###
r740xd_servarr_cloudflared_container_name: "servarr-cloudflared"
r740xd_servarr_gid: 4200
r740xd_servarr_groupname: "servarr"
r740xd_servarr_uid: 4200
r740xd_servarr_username: "servarr" # TODO: fixme

###
### Sonarr
###
r740xd_sonarr1080_config_volume_name: "sonarr1080-config"
r740xd_sonarr1080_container_name: "sonarr1080"
r740xd_sonarr1080_host_name: "sonarr1080"
r740xd_sonarr1080_network_aliases:
  - "sonarr1080"
r740xd_sonarr4k_config_volume_name: "sonarr4k-config"
r740xd_sonarr4k_container_name: "sonarr4k"
r740xd_sonarr4k_host_name: "sonarr4k"
r740xd_sonarr4k_network_aliases:
  - "sonarr4k"

###
### Tautulli
###
r740xd_tautulli_web_port: "8181"

###
### TimeMachine
###
r740xd_time_machine_docker_name: "time-machine"
r740xd_time_machine_workgroup: "TMWORKGROUP"

###
### Traefik
###
r740xd_traefik_http_ports:
  - '80:80'
  - '443:443'
r740xd_traefik_zwavejsui_entrypoints:
  zwavejsui:
    address: ":3000"
r740xd_traefik_emqx_entrypoints:
  emqx:
    address: ":1883"
  emqx_ws:
    address: ":9001"
r740xd_traefik_syncthings_entrypoints:
  syncthing_tcp:
    address: ":22000"
  syncthing_udp:
    address: ":22000/udp"
r740xd_traefik_syncthings_ports:
  - "22000:22000"
r740xd_traefik_unific_entrypoints:
  java_http:
    address: ":8080"
  unific_speed_test:
    address: ":6789"
  unific_stun:
    address: ":3478/udp"
  unific_dev_discovery:
    address: ":10001/udp"
  unific_controller_discovery:
    address: ":19000/udp"
r740xd_traefik_unific_ports:
  - "3478:3478"     # unific stun
  - "8080:8080"     # unific java http
  - "10001:10001"   # unific dev discovery
  - "19000:19000"   # unific controller discovery
