---
# defaults file for r720xd

##########
# Docker
##########

# Main folder for Docker files.
r720xd_docker_home: "/var/lib/docker"

r720xd_docker_users: []

##########
# Host
##########

r720xd_admin_username: "admin"
r720xd_admin_passwd: "password"

# Base domain name for machine and containers running on it.
r720xd_fqdn: "host.subdomain.example.com"

# Base domain for the entire site / location.
r720xd_site_domain: "subdomain.example.com"

r720xd_timezone: "America/New_York"

# List of dictionaries of Linux users to create. Each entry in the list should be a dictionary
# in the form to match ansible.builtin.user.
r720xd_users: []

##########
# Manyfold
##########

r720xd_manyfold_groupname: "manyfold"
r720xd_manyfold_username: "manyfold"

r720xd_manyfold_gid: 2500
r720xd_manyfold_uid: 2500

r720xd_manyfold_pgsql_admin_user: "manyfold"
r720xd_manyfold_pgsql_admin_passwd: "manyfold-password"
r720xd_manyfold_pgsql_name: "manyfold-pgsql"

r720xd_manyfold_redis_name: "manyfold-redis"
r720xd_manyfold_redis_volume_config: "manyfold-redis-config"
r720xd_manyfold_redis_volume_data: "manyfold-redis-data"

##########
# Traefik
##########

r720xd_traefik_https_redirect: true
r720xd_traefik_letsencrypt_email: "user@example.com"
r720xd_traefik_letsencrypt_use_prod: false
r720xd_traefik_trusted_ips: null

##########
# AWS Route53
##########

r720xd_route53_access_key_id: "access-key-id"
r720xd_route53_secret_access_key: "secret-access-key"
r720xd_route53_region: "region"
r720xd_route53_hosted_zone_id: "hosted-zone-id"
r720xd_route53_polling_interval: "15"
r720xd_route53_propagation_timeout: "900"
r720xd_route53_ttl: "60"
