---
#####
# Container settings
#####

# Name of the Docker container.
plex_docker_name: "plex"

# Base name of the Docker image to use for the container.
plex_docker_image: "plexinc/pms-docker"

# Specific Docker image version to use for the container.
plex_docker_image_version: "latest"

# User name and id to use inside the container.
plex_docker_username: "plex"
plex_docker_uid: "32400"

# Group name and id to use inside the container.
plex_docker_groupname: "plex"
plex_docker_gid: "32400"

# Timezone to use inside the container.
plex_docker_timezone: "America/New York"

# Number of vCPUs to allocate to the container.
plex_docker_cpus: "1"

# Amount of memory to allocate to the container.
plex_docker_memory: "1GB"

# Full FQDN for the Plex server.
plex_docker_fqdn: "plex.example.com"

#####
# Network
#####

plex_docker_extra_networks: null
plex_docker_network_aliases: null
plex_docker_network_name: null
plex_docker_network_ipv4: null

#####
# Volumes
#####

# Name of the volume which will hold the main Plex data.
plex_docker_volume_name_home: "plex-home"

# Name of the volume which will be used by Plex for transcoding operations.
plex_docker_volume_name_transcode: "plex-transcode"

# List of dictionaries of additional folders to bind mount into the container.
#
# Example:
#
# plex_docker_additional_bind_mounts:
#   - source: "/mnt/music"
#     target: "/media/music"
#   - source: "/mnt/videos/movies"
#     target: "/media/movies"
#
plex_docker_additional_bind_mounts: []

#####
# Plex settings
#####

plex_docker_claim: "ABCD1234"

