---
###
### Docker
###
nas_docker_zfs_dataset: "data/docker"
nas_docker_home: "/{{ nas_docker_zfs_dataset }}"

###
### Glances
###
glances_host_domain_name: "{{ veggie_fqdn }}"
glances_config_data:
  diskio:
    "hide": "loop.*,md0,sd[b-z][0-9]"
  folders:
    "folder_1_path": "/nas-mirror/books"
    "folder_2_path": "/nas-mirror/documents"
    "folder_3_path": "/nas-mirror/music"
    "folder_4_path": "/nas-mirror/photos"
    "folder_5_path": "/nas-mirror/time=machine"
    "folder_6_path": "/data/videos/movies/1080p"
    "folder_7_path": "/data/videos/movies/2160p"
    "folder_8_path": "/data/videos/tv/1080p"
    "folder_9_path": "/data/videos/tv/2160p"
  fs:
    "hide": "/etc.*"
  network:
    "disabled": "true"
    "hide": "docker.*,lo,veth.*"
glances_extra_bind_mounts:
    - source: "/nas-mirror/books"
      target: "/nas-mirror/books"
      type: "bind"
      read_only: true
    - source: "/nas-mirror/documents"
      target: "/nas-mirror/documents"
      type: "bind"
      read_only: true
    - source: "/nas-mirror/music"
      target: "/nas-mirror/music"
      type: "bind"
      read_only: true
    - source: "/nas-mirror/photos"
      target: "/nas-mirror/photos"
      type: "bind"
      read_only: true
    - source: "/nas-mirror/time-machine"
      target: "/nas-mirror/time-machine"
      type: "bind"
      read_only: true
    - source: "/data/videos/movies/1080p"
      target: "/data/videos/movies/1080p"
      type: "bind"
      read_only: true
    - source: "/data/videos/movies/2160p"
      target: "/data/videos/movies/2160p"
      type: "bind"
      read_only: true
    - source: "/data/videos/tv/1080p"
      target: "/data/videos/tv/1080p"
      type: "bind"
      read_only: true
    - source: "/data/videos/tv/2160p"
      target: "/data/videos/tv/2160p"
      type: "bind"
      read_only: true

###
### Home Assistant
###
hass_ecowitt_hass_auth_token: "{{ vault_hass_ecowitt_hass_auth_token }}"
hass_ecowitt_hass_webhook_id: "{{ vault_hass_ecowitt_hass_webhook_id }}"
hass_zwave_device: "{{ vault_hass_zwave_device }}"

###
### Navidrome
###
navidrome_base_url: "https://navidrome"

###
### NodeRED
###
nodered_credential_secret: "{{ vault_nodered_credential_secret }}"

###
### Plex
###
# See https://www.plex.tv/claim
plex_docker_claim: "{{ vault_plex_docker_claim }}"

###
### Radarr
###
radarr1080_docker_api_key: "{{ vault_radarr1080_docker_api_key }}"
radarr4k_docker_api_key: "{{ vault_radarr4k_docker_api_key }}"

###
### Readarr
###
readarr_api_key: "{{ vault_readarr_api_key }}"

###
### Sonarr
###
sonarr1080_docker_api_key: "{{ vault_sonarr1080_docker_api_key }}"
sonarr4k_docker_api_key: "{{ vault_sonarr4k_docker_api_key }}"

###
### Time Machine
###
time_machine_data_directory: "{{ vault_time_machine_data_directory }}"
time_machine_hostname: "{{ vault_time_machine_hostname }}"
time_machine_network_parent: "{{ vault_time_machine_network_parent }}"
time_machine_network_ipv4: "{{ vault_time_machine_network_ipv4 }}"
nas_time_machine_data_directory: "{{ vault_time_machine_data_directory }}"
nas_time_machine_hostname: "{{ vault_time_machine_hostname }}"

###
### Veggie Common
###
veggie_domain: "{{ vault_veggie_domain }}"
veggie_fqdn: "{{ veggie_hostname }}.{{ veggie_domain }}"
veggie_hostname: "{{ vault_veggie_hostname }}"
veggie_nas_domain_name: "{{ veggie_fqdn }}"