---
###
### Docker
###
r740xd_docker_zfs_dataset: "data/docker"
r740xd_docker_home: "/{{ r740xd_docker_zfs_dataset }}"

###
### Glances
###
glances_host_domain_name: "{{ veggie_fqdn }}"
glances_config_data:
  diskio:
    "hide": "loop.*,md0,sd[b-z][0-9]"
  folders:
    "folder_1_path": "/nas-mirror/books"
    "folder_2_path": "/nas-mirror/documents"
    "folder_3_path": "/nas-mirror/music"
    "folder_4_path": "/nas-mirror/photos"
    "folder_5_path": "/nas-mirror/time=machine"
    "folder_6_path": "/data/videos/movies/1080p"
    "folder_7_path": "/data/videos/movies/2160p"
    "folder_8_path": "/data/videos/tv/1080p"
    "folder_9_path": "/data/videos/tv/2160p"
  fs:
    "hide": "/etc.*"
  network:
    "disabled": "true"
    "hide": "docker.*,lo,veth.*"
glances_extra_bind_mounts:
    - source: "/nas-mirror/books"
      target: "/nas-mirror/books"
      type: "bind"
      read_only: true
    - source: "/nas-mirror/documents"
      target: "/nas-mirror/documents"
      type: "bind"
      read_only: true
    - source: "/nas-mirror/music"
      target: "/nas-mirror/music"
      type: "bind"
      read_only: true
    - source: "/nas-mirror/photos"
      target: "/nas-mirror/photos"
      type: "bind"
      read_only: true
    - source: "/nas-mirror/time-machine"
      target: "/nas-mirror/time-machine"
      type: "bind"
      read_only: true
    - source: "/data/videos/movies/1080p"
      target: "/data/videos/movies/1080p"
      type: "bind"
      read_only: true
    - source: "/data/videos/movies/2160p"
      target: "/data/videos/movies/2160p"
      type: "bind"
      read_only: true
    - source: "/data/videos/tv/1080p"
      target: "/data/videos/tv/1080p"
      type: "bind"
      read_only: true
    - source: "/data/videos/tv/2160p"
      target: "/data/videos/tv/2160p"
      type: "bind"
      read_only: true

###
### Home Assistant
###
hass_ecowitt_hass_auth_token: "{{ vault_hass_ecowitt_hass_auth_token }}"
hass_ecowitt_hass_webhook_id: "{{ vault_hass_ecowitt_hass_webhook_id }}"
hass_zwave_device: "{{ vault_hass_zwave_device }}"

###
### Kometa
###
kometa_cpus: "4"
kometa_memory: "4G"
kometa_timezone: "{{ home_timezone }}"

kometa_global_save_report: true
kometa_mdblist_apikey: "{{ vault_kometa_mdblist_apikey }}"
kometa_mdblist_cache_expiration: "60"
kometa_plex_db_cache: "2048" # MB
kometa_plex_token: "{{ vault_kometa_plex_token }}"
kometa_tmdb_apikey: "{{ vault_kometa_tmdb_apikey }}"
kometa_tmdb_language: "en"
kometa_tmdb_region: "US"
kometa_tautulli_apikey: "{{ vault_kometa_tautulli_apikey }}"
kometa_libraries: |2
    Movies:
      schedule: weekly(sunday)
      report_path: /config/reports/Movies-1080p.yml
      template_variables:
        language: "en"
      collection_files:
        - pmm: actor
        - pmm: basic
        - pmm: bafta
        - pmm: cannes
        - pmm: decade
        - pmm: director
        - pmm: franchise
          template_variables:
            data:
              visible_home: true
        - pmm: genre
          template_variables:
            data:
              visible_home: true
        - pmm: imdb
        - pmm: oscars
          template_variables:
            data:
              starting: current_year-10
              ending: current_year
        - pmm: seasonal
          template_variables:
            data:
              visible_home: true
        - pmm: streaming
        - pmm: sundance
        - pmm: tmdb
        - pmm: universe
        - pmm: year
      overlay_files:
        - remove_overlays: false
        - pmm: resolution
        - pmm: audio_codec
        - pmm: streaming
        - pmm: video_format
        - pmm: ratings
          template_variables:
            rating1: critic
            rating1_image: imdb
            # rating1_font: config/metadata/fonts/Impact.ttf
            # rating1_font_size: 70

            rating2: audience
            rating2_image: rt_popcorn
            # rating2_font: config/metadata/fonts/Adlib.ttf
            # rating2_font_size: 63

            rating3: user
            rating3_image: tmdb
            # rating3_font: config/metadata/fonts/Avenir_95_Black.ttf
            # rating3_font_size: 70
        - pmm: ribbon
      operations:
        mass_user_rating_update: mdb_tomatoes   # Update user ratings with mdb_tomatoes
        mass_critic_rating_update: imdb         # Update critic ratings with imdb
        mass_audience_rating_update: tmdb       # Update audience ratings with tmdb
    Movies (4K):
      schedule: weekly(monday)
      report_path: /config/reports/Movies-4K.yml
      template_variables:
        language: "en"
      collection_files:
        - pmm: actor
        - pmm: basic
        - pmm: bafta
        - pmm: cannes
        - pmm: decade
        - pmm: director
        - pmm: franchise
          template_variables:
            data:
              visible_home: true
        - pmm: genre
          template_variables:
            data:
              visible_home: true
        - pmm: imdb
        - pmm: oscars
          template_variables:
            data:
              starting: current_year-10
              ending: current_year
        - pmm: seasonal
          template_variables:
            data:
              visible_home: true
        - pmm: streaming
        - pmm: sundance
        - pmm: tmdb
        - pmm: universe
        - pmm: year
      overlay_files:
        - remove_overlays: false
        - pmm: resolution
        - pmm: audio_codec
        - pmm: streaming
        - pmm: video_format
        - pmm: ratings
          template_variables:
            rating1: critic
            rating1_image: imdb
            # rating1_font: config/metadata/fonts/Impact.ttf
            # rating1_font_size: 70

            rating2: audience
            rating2_image: rt_popcorn
            # rating2_font: config/metadata/fonts/Adlib.ttf
            # rating2_font_size: 63

            rating3: user
            rating3_image: tmdb
            # rating3_font: config/metadata/fonts/Avenir_95_Black.ttf
            # rating3_font_size: 70
        - pmm: ribbon
      operations:
        mass_user_rating_update: mdb_tomatoes   # Update user ratings with mdb_tomatoes
        mass_critic_rating_update: imdb         # Update critic ratings with imdb
        mass_audience_rating_update: tmdb       # Update audience ratings with tmdb
    TV Shows:
      schedule: weekly(tuesday)
      report_path: /config/reports/TV_Shows-1080p.yml
      template_variables:
        language: en
      collection_files:
        - pmm: basic
        - pmm: franchise
        - pmm: genre
        - pmm: network
        - pmm: year
      overlay_files:
        - remove_overlays: false
        - pmm: resolution
        - pmm: resolution
          template_variables:
            builder_level: season
        - pmm: resolution
          template_variables:
            builder_level: episode
        - pmm: audio_codec
        - pmm: audio_codec
          template_variables:
            builder_level: season
        - pmm: audio_codec
          template_variables:
            builder_level: episode
        - pmm: streaming
        - pmm: video_format
        - pmm: video_format
          template_variables:
            builder_level: season
        - pmm: video_format
          template_variables:
            builder_level: episode
        - pmm: episode_info
          template_variables:
            builder_level: episode
        - pmm: runtimes
          template_variables:
            builder_level: episode
        - pmm: ribbon
        - pmm: ratings
          template_variables:
            rating1: critic
            rating1_image: imdb
            # rating1_font: config/metadata/fonts/Impact.ttf
            # rating1_font_size: 70

            rating2: audience
            rating2_image: rt_popcorn
            # rating2_font: config/metadata/fonts/Adlib.ttf
            # rating2_font_size: 63

            rating3: user
            rating3_image: tmdb
            # rating3_font: config/metadata/fonts/Avenir_95_Black.ttf
            # rating3_font_size: 70
        - pmm: ratings
          template_variables:
            builder_level: episode
            rating1: critic
            rating1_image: imdb
            # rating1_font: config/metadata/fonts/Impact.ttf
            # rating1_font_size: 70

            rating2: audience
            rating2_image: tmdb
            # rating2_font: config/metadata/fonts/Avenir_95_Black.ttf
            # rating2_font_size: 70
      operations:
        mass_user_rating_update: mdb_tomatoes   # Update user ratings with mdb_tomatoes
        mass_critic_rating_update: imdb         # Update critic ratings with imdb
        mass_audience_rating_update: tmdb       # Update audience ratings with tmdb
        mass_episode_critic_rating_update: imdb
        mass_episode_audience_rating_update: tmdb
    TV Shows (4K):
      schedule: weekly(wednesday)
      report_path: /config/reports/TV_Shows-4K.yml
      template_variables:
        language: en
      collection_files:
        - pmm: basic
        - pmm: franchise
        - pmm: genre
        - pmm: network
        - pmm: year
      overlay_files:
        - remove_overlays: false
        - pmm: resolution
        - pmm: resolution
          template_variables:
            builder_level: season
        - pmm: resolution
          template_variables:
            builder_level: episode
        - pmm: audio_codec
        - pmm: audio_codec
          template_variables:
            builder_level: season
        - pmm: audio_codec
          template_variables:
            builder_level: episode
        - pmm: streaming
        - pmm: video_format
        - pmm: video_format
          template_variables:
            builder_level: season
        - pmm: video_format
          template_variables:
            builder_level: episode
        - pmm: episode_info
          template_variables:
            builder_level: episode
        - pmm: runtimes
          template_variables:
            builder_level: episode
        - pmm: ribbon
        - pmm: ratings
          template_variables:
            rating1: critic
            rating1_image: imdb
            # rating1_font: config/metadata/fonts/Impact.ttf
            # rating1_font_size: 70

            rating2: audience
            rating2_image: rt_popcorn
            # rating2_font: config/metadata/fonts/Adlib.ttf
            # rating2_font_size: 63

            rating3: user
            rating3_image: tmdb
            # rating3_font: config/metadata/fonts/Avenir_95_Black.ttf
            # rating3_font_size: 70
        - pmm: ratings
          template_variables:
            builder_level: episode
            rating1: critic
            rating1_image: imdb
            # rating1_font: config/metadata/fonts/Impact.ttf
            # rating1_font_size: 70

            rating2: audience
            rating2_image: tmdb
            # rating2_font: config/metadata/fonts/Avenir_95_Black.ttf
            # rating2_font_size: 70
      operations:
        mass_user_rating_update: mdb_tomatoes   # Update user ratings with mdb_tomatoes
        mass_critic_rating_update: imdb         # Update critic ratings with imdb
        mass_audience_rating_update: tmdb       # Update audience ratings with tmdb
        mass_episode_critic_rating_update: imdb
        mass_episode_audience_rating_update: tmdb
    Anime Movies:
      schedule: weekly(thursday)
      report_path: /config/reports/Anime_Movies.yml
      template_variables:
        language: en
      collection_files:
        - pmm: anilist
        - pmm: basic
        - pmm: myanimelist
    Anime Series:
      schedule: weekly(friday)
      report_path: /config/reports/Anime_Series.yml
      template_variables:
        language: en
      collection_files:
        - pmm: anilist
        - pmm: basic
        - pmm: myanimelist

# See https://replit.com/@chazlarson/TraktAuth to generate the auth data.
kometa_trakt: |2
    client_id: {{ vault_kometa_trakt_client_id }}
    client_secret: {{ vault_kometa_trakt_client_secret }}
    pin:
    authorization:
      access_token: {{ vault_kometa_trakt_access_token }}
      token_type: {{ vault_kometa_trakt_token_type }}
      expires_in: {{ vault_kometa_trakt_expires_in }}
      refresh_token: {{ vault_kometa_trakt_refresh_token }}
      scope: {{ vault_kometa_trakt_scope }}
      created_at: {{ vault_kometa_trakt_created_at }}

###
### Navidrome
###
navidrome_base_url: "https://navidrome"

###
### Network
###
docker_macvlans:
  mgmnt:
    name: "mgmt"
    network_parent: "{{ vault_docker_macvlan_mgmt.parent }}"
    enable_ipv6: false
    internal: false
    scope: "local"
    ipam_config:
      - subnet: "{{ vault_docker_macvlan_mgmt.subnet }}"
        gateway: "{{ vault_docker_macvlan_mgmt.gateway }}"
        iprange: "{{ vault_docker_macvlan_mgmt.iprange }}"
  iot:
    name: "iot"
    network_parent: "{{ vault_docker_macvlan_iot.parent }}"
    enable_ipv6: false
    internal: false
    scope: "local"
    ipam_config:
      - subnet: "{{ vault_docker_macvlan_iot.subnet }}"
        gateway: "{{ vault_docker_macvlan_iot.gateway }}"
        iprange: "{{ vault_docker_macvlan_iot.iprange }}"
  nas_macvlan:
    name: "nas_macvlan"
    network_parent: "{{ vault_docker_macvlan_default.parent }}"
    enable_ipv6: false
    internal: false
    scope: "local"
    ipam_config:
      - subnet: "{{ vault_docker_macvlan_default.subnet }}"
        gateway: "{{ vault_docker_macvlan_default.gateway }}"
        iprange: "{{ vault_docker_macvlan_default.iprange }}"

###
### NodeRED
###
nodered_credential_secret: "{{ vault_nodered_credential_secret }}"

###
### Plex
###
# See https://www.plex.tv/claim
r740xd_plex_cpus: 16
r740xd_plex_memory: "16GB"
plex_docker_claim: "{{ vault_plex_docker_claim }}"

###
### Radarr
###
radarr1080_docker_api_key: "{{ vault_radarr1080_docker_api_key }}"
radarr4k_docker_api_key: "{{ vault_radarr4k_docker_api_key }}"

###
### Readarr
###
readarr_api_key: "{{ vault_readarr_api_key }}"

###
### Sonarr
###
sonarr1080_docker_api_key: "{{ vault_sonarr1080_docker_api_key }}"
sonarr4k_docker_api_key: "{{ vault_sonarr4k_docker_api_key }}"

###
### Time Machine
###
time_machine_data_directory: "{{ vault_time_machine_data_directory }}"
time_machine_hostname: "{{ vault_time_machine_hostname }}"
time_machine_network_parent: "{{ vault_time_machine_network_parent }}"
time_machine_network_ipv4: "{{ vault_time_machine_network_ipv4 }}"
r740xd_time_machine_data_directory: "{{ vault_time_machine_data_directory }}"
r740xd_time_machine_hostname: "{{ vault_time_machine_hostname }}"

###
### Veggie Common
###
veggie_domain: "{{ vault_veggie_domain }}"
veggie_fqdn: "{{ veggie_hostname }}.{{ veggie_domain }}"
veggie_hostname: "{{ vault_veggie_hostname }}"
veggie_nas_domain_name: "{{ veggie_fqdn }}"