calibre_available_externally: "false"
calibre_data_directory: "{{ docker_home }}/calibre"
calibre_books_root: "/mnt/books"

calibre_username: "calibre"
calibre_extra_groups: []
calibre_user_id: "0"
calibre_group_id: "0"

calibre_network_name: "calibre"
calibre_hostname: "calibre"
calibre_host_domain: "example.com"

calibre_timezone: "America/Los_Angeles"

# To disable ebook conversion set calibre_ebook_conversion to "". To enable it set it to "linuxserver/calibre-web:calibre"
calibre_ebook_conversion: "linuxserver/calibre-web:calibre"