###
### Calibre
###
calibre_books_root: "{{ vault_calibre_books_root }}"
calibre_host_domain: "{{ veggie_base_domain_name }}"
calibre_extra_groups:
  - "book_writer"
calibre_user_id: "{{ vault_calibre_user_id }}"
calibre_group_id: "{{ vault_calibre_group_id }}"

###
### Common
###
veggie_hostname: "{{ veggie_nas_domain_name }}"
veggie_admin_username: "{{ veggie_nas_admin_username }}"
veggie_admin_passwd: "{{ veggie_nas_admin_passwd }}"
veggie_users_passwords:
  retropie: "*"

###
### Diun
###
diun_notify_mail_host: "{{ vault_diun_notify_mail_host }}"
diun_notify_mail_port: "{{ vault_diun_notify_mail_port }}"
diun_notify_mail_ssl: true
diun_notify_mail_insecure_skip_verify: false
diun_notify_mail_username: "{{ vault_diun_notify_mail_username }}"
diun_notify_mail_password: "{{ vault_diun_notify_mail_password }}"
diun_notify_mail_from: "{{ vault_diun_notify_mail_from }}"
diun_notify_mail_to: "{{ vault_diun_notify_mail_to }}"
diun_regopts_dockerio_user: "{{ vault_diun_regopts_dockerio_user }}"
diun_regopts_dockerio_passwd: "{{ vault_diun_regopts_dockerio_passwd }}"

###
### Docker
###
docker_home: /mnt/nas/docker
docker_daemon_options:
  storage-driver: "zfs"
  data-root: "{{ docker_home }}/data"

###
### Glances
###
glances_host_domain: "{{ veggie_nas_domain_name }}"

###
### Grafana
###
grafana_docker_memory: "1G"
grafana_docker_config_dir: "/mnt/nas/grafana/etc"
grafana_docker_zfs_filesystems:
  - "nas/grafana"
  - "nas/grafana/etc"
grafana_docker_host_domain: "{{ veggie_base_domain_name }}"
grafana_docker_admin_password: "{{ vault_grafana_docker_admin_password }}"
grafana_docker_smtp_enabled: "true"
grafana_docker_smtp_host: "{{ vault_grafana_docker_smtp_host }}"
grafana_docker_smtp_user: "{{ vault_grafana_docker_smtp_user }}"
grafana_docker_smtp_password: "{{ vault_grafana_docker_smtp_password }}"
grafana_docker_smtp_from_address: "{{ primary_email_address }}"
grafana_docker_extra_networks:
  - "influxdb"

###
### InfluxDB
###
influxdb_docker_host_domain: "{{ veggie_nas_domain_name }}"
influxdb_docker_conf_dir: "/mnt/nas/influxdb/etc"
influxdb_docker_zfs_filesystems:
  - "nas/influxdb"
  - "nas/influxdb/etc"
influxdb_docker_superuser_name: "{{ influxdb_admin_user }}"
influxdb_docker_superuser_password: "{{ influxdb_admin_password }}"
influxdb_docker_superuser_org: "{{ influxdb_admin_org }}"
influxdb_docker_superuser_token: "{{ influxdb_admin_token }}"
influxdb_docker_init_bucket: "admin"

###
### Let's Encrypt / Certbot
###
certbot_domain_name: "{{ veggie_nas_domain_name }}"
certbot_admin_email: "{{ letsencrypt_email }}"
certbot_aws_access_key_id: "{{ letsencrypt_aws_access_key }}"
certbot_aws_secret_access_key: "{{ letsencrypt_aws_secret_key }}"

###
### Logrotate
###
logrotate_scripts:
  - name: rclone
    path: "/var/log/rclone.log"
    options:
      - daily
      - rotate 7
      - missingok
      - compress
      - delaycompress
      - copytruncate

###
### NFS
###
nfs_exports:
  - "/mnt/nas/data/books {{ veggie_virt_domain_name }}(rw,sync,no_subtree_check,no_root_squash)"
  - "/mnt/nas/data/music {{ veggie_virt_domain_name }}(rw,sync,no_subtree_check,no_root_squash)"
  - "/mnt/nas/data/videos {{ veggie_virt_domain_name }}(rw,sync,no_subtree_check,no_root_squash)"

###
### Node-RED
###
nodered_docker_image: "{{ vault_nodered_docker_image }}"
nodered_host_domain: "{{ veggie_nas_domain_name }}"

###
### organicveggie.folders
###
organicveggie_folders_create:
  - path: "{{ docker_home }}"
    owner: root
    group: root
    mode: "755"

###
### Photoprism
###
photoprism_admin_password: "{{ vault_photoprism_admin_password }}"
photoprism_docker_host_domain: "{{ veggie_base_domain_name }}"
photoprism_dir: "/mnt/nas/photoprism"
photoprism_extra_groups: "photo_writer"
photoprism_mariadb_dir: "/mnt/nas/photoprism-mariadb"
photoprism_mariadb_root_password: "{{ vault_photoprism_mariadb_root_password }}"
photoprism_mariadb_password: "{{ vault_photoprism_mariadb_password }}"
photoprism_zfs_filesystems:
  - dataset: "nas/photoprism"
    path: "/mnt/nas/photoprism"
  - dataset: "nas/photoprism-mariadb"
    path: "/mnt/nas/photoprism-mariadb"

###
### Plex
###
plex_docker_claim: "{{ vault_plex_docker_claim }}"
plex_docker_cpus: "8"
plex_docker_memory: "4GB"

###
### Pip
###
pip_install_packages:
  - docker

###
### Portainer
###
portainer_available_externally: "true"
portainer_admin_password: "{{ default_portainer_admin_password }}"
portainer_host_domain: "{{ veggie_nas_domain_name }}"

###
### RClone
###
rclone_configs:
  - name: AWSS3Remote
    properties:
      type: s3
      provider: AWS
      env_auth: false
      region: us-west-2
      location_constraint: us-west-2
      acl: private
      server_side_encryption: AES256
      storage_class: STANDARD
      access_key_id: "{{ aws_s3_rclone_access_key }}"
      secret_access_key: "{{ aws_s3_rclone_secret_key }}"
rclone_config_path: "{{ veggie_rclone_config_path }}"
veggie_rclone_s3_bucket: "{{ veggie_nas_rclone_s3_bucket }}"
veggie_rclone_config_path: /root/.config/rclone/rclone.conf

###
### Restic
###
restic_rest_server_backup_dir: "{{ veggie_nas_restic_rest_server_backup_dir }}"
restic_rest_server_hostname: "{{ veggie_nas_restic_rest_server_hostname }}"
restic_rest_server_host_domain: "{{ veggie_nas_domain_name }}"
restic_server_users:
  - name: "{{ restic_user_desktop | default('') }}"
    password: "{{ restic_htpasswd_desktop | default('') }}"
  - name: "{{ restic_user_unific | default('') }}"
    password: "{{ restic_htpasswd_unific | default('') }}"

###
### Samba
###
samba_domain_master: auto
samba_preferred_master: auto
samba_wins_support: false

# Defaults to true, which disables share browsing by Windows clients.
# See https://access.redhat.com/security/cve/cve-2017-7494
samba_mitigate_cve_2017_7494: false
samba_users:
  - name: "{{ veggie_nas_admin_username }}"
    password: "{{ veggie_nas_admin_samba_passwd }}"
  # - name: "plex"
  #   password: "{{ veggie_nas_plex_password }}"
  - name: "retropie"
    password: "{{ veggie_nas_retropie_password }}"
  - name: "kstar"
    password: "{{ veggie_kstar_password }}"
samba_shares:
  - name: books
    path: /mnt/nas/data/books
    group: book_writer
    write_list: +book_writer
  - name: documents
    path: /mnt/nas/data/documents
    group: doc_writer
    write_list: +doc_writer
  - name: music
    path: /mnt/nas/data/music
    group: music_writer
    write_list: +music_writer
  - name: photos
    path: /mnt/nas/data/photos
    group: photo_writer
    write_list: +photo_writer
  - name: roms
    path: /mnt/nas/data/roms
    group: rom_writer
    write_list: +rom_writer
  - name: source
    path: /mnt/nas/data/source
    group: source_writer
    write_list: +source_writer
  - name: videos
    path: /mnt/nas/data/videos
    group: media_writer
    write_list: +media_writer
  - name: kstar
    path: /mnt/nas/kstar
    owner: kstar
    group: kstar
    create_mode: 0740
    directory_mode: 0770
veggie_nas_samba_groups:
  - book_writer
  - doc_writer
  - media_writer
  - music_writer
  - photo_writer
  - rom_writer
  - source_writer

###
### Telegraf
###
telegraf_influxdb_url: "{{ influxdb_url }}"
telegraf_influxdb_token: "{{ influxdb_telegraf_token }}"
telegraf_influxdb_org: "{{ influxdb_admin_org }}"
telegraf_plugin_docker: true
telegraf_plugin_smartctl: true
telegraf_plugin_zfs_pool_sizes: true
telegraf_plugins_extra:
  - name: disk
    options:
      mount_points:
        - "/"
        - "/boot"
        - "/var/log"
        - "/mnt/nas"
        - "/mnt/nas/backups"
        - "/mnt/nas/data"
        - "/mnt/nas/data/books"
        - "/mnt/nas/data/documents"
        - "/mnt/nas/data/music"
        - "/mnt/nas/data/photos"
        - "/mnt/nas/data/roms"
        - "/mnt/nas/data/videos"
        - "/mnt/nas/docker"
        - "/mnt/nas/influxdb/lib"
        - "/mnt/nas/plex"
        - "/mnt/nas/time-machine"
  - name: prometheus
    options:
      urls:
        - "$INFLUX_URL"
    tags:
      influxdb_bucket: "influxdb"
  - name: zfs
    options:
      poolMetrics: true


###
### TimeMachine
###
timemachine_data_directory: "/mnt/nas/time-machine"
timemachine_volume_size_limit: "512000"
timemachine_share_name: "nas-time-machine"
timemachine_smb_password: "{{ vault_timemachine_smb_password }}"

###
### Traefik
###
traefik_hostname: "traefik.{{ veggie_nas_domain_name }}"
traefik_confkey_api:
  dashboard: true # use this for enabling the dashboard
# traefik_confkey_log:
#   level: DEBUG
#   filePath: /var/log/traefik.log
traefik_qs_https: "true"
traefik_qs_https_redirect: "true"
traefik_qs_https_le: "true"
traefik_qs_https_le_mail: "{{ letsencrypt_email }}"
traefik_qs_log_level: INFO
# Defined dynamically in roles/veggie_nas/tasks/docker.yml
# traefik_extra_networks:
traefik_ports:
  - '80:80'
  - '443:443'
traefik_labels:
  traefik.enable: "true"
  traefik.http.routers.traefik.service: "api@internal"
  traefik.http.routers.traefik.entrypoints: "https"
  traefik.http.routers.traefik.tls.certresolver: "letsencrypt"
  traefik.http.routers.traefik.tls.domains[0].main: "*.{{ veggie_nas_domain_name }}"
traefik_confkey_providers:
  docker:
    defaultRule: "Host(`{{ traefik_hostname }}`)"
traefik_le_ca_server: "https://acme-v02.api.letsencrypt.org/directory"
# traefik_le_ca_server: "https://acme-staging-v02.api.letsencrypt.org/directory"
traefik_confkey_certificatesResolvers:
  letsencrypt:
    acme:
      caServer: "{{ traefik_le_ca_server }}"
      dnsChallenge:
        provider: route53
traefik_container_environment:
  AWS_HOSTED_ZONE_ID: "{{ acme_route53_hosted_zone_id }}"
  AWS_ACCESS_KEY_ID: "{{ letsencrypt_aws_access_key }}"
  AWS_SECRET_ACCESS_KEY: "{{ letsencrypt_aws_secret_key }}"

###
### UniFi Controiller
###
unific_available_externally: "true"
unific_host_domain: "{{ veggie_nas_domain_name }}"
unific_cpus: "2"
unific_memory: "2GB"
unific_network_mode: "{{ traefik_network_name }}"
unific_dir_data: "/virtpool/unific/data"
unific_dir_log: "/virtpool/unific/log"
unific_dir_cert: "/virtpool/unific//cert"
unific_traefik_router_rule: "Host(`{{ unific_hostname }}.{{ unific_host_domain }}`) || Host(`{{ unific_hostname }}.{{ veggie_base_domain_name }}`)"

###
### Users/Groups
###
users_list_host: "{{ nas_users }}"