###
### ACME / Let's Encrypt
###
acme_email: "{{ primary_email_address }}"
acme_route53_domain: "{{ vault_acme_route53_domain }}"
acme_route53_hosted_zone_id: "{{ vault_acme_route53_hosted_zone_id }}"
letsencrypt_aws_access_key: "{{ vault_letsencrypt_aws_access_key }}"
letsencrypt_aws_secret_key: "{{ vault_letsencrypt_aws_secret_key }}"
letsencrypt_email: "{{ primary_email_address }}"

###
### AWS
###
aws_s3_rclone_access_key: "{{ vault_aws_s3_rclone_access_key }}}"
aws_s3_rclone_secret_key: "{{ vault_aws_s3_rclone_secret_key }}}"
aws_ses_usw2_access_key: "{{ vault_aws_ses_usw2_access_key }}}"
aws_ses_usw2_secret_key: "{{ vault_aws_ses_usw2_secret_key }}}"

###
### Common
###
default_admin_email: "{{ vault_default_admin_email }}"
real_hostname: "{{ inventory_hostname }}"
real_hostname_short: "{{ inventory_hostname_short }}"
home_latitude: "{{ vault_home_latitude }}"
home_longitude: "{{ vault_home_longitude }}"
home_timezone: "{{ vault_home_timezone }}"
veggie_base_domain_name: "{{ vault_veggie_base_domain_name }}"

###
### Home Assistant
###
veggie_home_assistant_hostname: "{{ vault_hass_hostname }}"
veggie_hass_db_user: "{{ vault_hass_db_user }}"
veggie_hass_db_password: "{{ vault_hass_db_password }}"

###
### InfluxDB 
###
influxdb_admin_user: "{{ vault_influxdb_admin_user }}"
influxdb_admin_password: "{{ vault_influxdb_admin_password }}"
influxdb_admin_org: "{{ vault_influxdb_admin_org }}"
influxdb_admin_token: "{{ vault_influxdb_admin_token }}"
influxdb_telegraf_token: "{{ vault_influxdb_telegraf_token }}"
influxdb_url: "https://influxdb.{{ veggie_nas_domain_name }}"

###
### msmtp
###
msmtp_host: "{{ vault_msmtp_host }}"
msmtp_port: "{{ vault_msmtp_port }}"
msmtp_user: "{{ vault_msmtp_user }}"
msmtp_passwd: "{{ vault_msmtp_passwd }}"
msmtp_from: "{{ vault_msmtp_from }}"

###
### Networking
###
default_dns_address: "{{ vault_default_dns_address }}"
iot_vlan_docker_network_name: "iot-macvlan40"

###
### Notifications
###
primary_email_address: "{{ default_admin_email }}"

###
### Portainer
###
default_portainer_admin_password: "{{ vault_portainer_admin_password }}"

###
### PostgreSQL
###
veggie_postgres_admin_password: "{{ vault_postgres_admin_password }}"

###
### RClone
###
veggie_nas_rclone_s3_bucket: "{{ vault_veggie_nas_rclone_s3_bucket }}"

###
### Restic
###
restic_client_admin_email: "{{ default_admin_email }}"
restic_htpasswd_desktop: "{{ vault_restic_htpasswd_desktop }}"
restic_htpasswd_unific: "{{ vault_restic_htpasswd_unific }}"
restic_passwd_desktop: "{{ vault_restic_passwd_desktop }}"
restic_passwd_unific: "{{ vault_restic_passwd_unific }}"
restic_user_desktop: "{{ vault_restic_user_desktop }}"
restic_user_unific: "{{ vault_restic_user_unific }}"
veggie_desktop_restic_password: "{{ vault_veggie_desktop_restic_password }}"
veggie_desktop_restic_server: "{{ vault_veggie_desktop_restic_server }}"
veggie_nas_restic_rest_server_backup_dir: "{{ vault_veggie_nas_restic_rest_server_backup_dir }}"
veggie_nas_restic_rest_server_hostname: "{{ vault_veggie_nas_restic_rest_server_hostname }}"

###
### SMTP
###
smtp_server_name: "{{ vault_smtp_server_name }}"
smtp_username: "{{ vault_smtp_username }}"
smtp_password: "{{ vault_smtp_password }}"

###
### SpeedTest
###
speedtest_cli_license: "{{ vault_speedtest_cli_license }}"
speedtest_install_key: "{{ vault_speedtest_install_key }}"
speedtest_telegraf_interval: "10m"

###
### Telegraf
###
telegraf_collection_jitter: 1s
telegraf_flush_interval: 10s
telegraf_flush_jitter: 1s
telegraf_ping_host1: "{{ vault_telegraf_ping_host1 }}"
telegraf_ping_host2: "{{ vault_telegraf_ping_host2 }}"
telegraf_snmp_firewall: "{{ vault_telegraf_snmp_firewall }}"
telegraf_snmp_firewall_community: "{{ vault_telegraf_snmp_firewall_community }}"
telegraf_snmp_net_community: "{{ vault_telegraf_snmp_net_community }}"
telegraf_snmp_trap_port: "{{ vault_telegraf_snmp_trap_port }}"

###
### Traefik
###
traefik_image: "traefik:latest"

###
### Users
###
veggie_kstar_password: "{{ vault_veggie_kstar_password }}"

###
### Veggie NAS
###
veggie_nas_domain_name: "{{ vault_nas_domain_name }}"

###
### Veggie Virt
###
veggie_virt_domain_name: "{{ vault_veggie_virt_domain_name }}"
