---
- name: "Create Readarr Docker config volume"
  community.docker.docker_volume:
    name: "{{ readarr_docker_volume_config_name }}"

- name: "Set Docker mount list for volume mounts"
  ansible.builtin.set_fact:
    _readarr_docker_mount_list:
      - source: "{{ readarr_docker_volume_config_name }}"
        target: "/config"
        type: "volume"
      - source: "{{ readarr_docker_data_source_path }}"
        target: "/data"
        type: "bind"

- name: "Build container FQDN"
  ansible.builtin.set_fact:
    _readarr_docker_fqdn: "{{ readarr_docker_host_name }}.{{ readarr_docker_host_domain }}"

- name: "Create placeholder array for default network"
  ansible.builtin.set_fact:
    _readarr_docker_default_networks:
      - name: "{{ readarr_docker_network }}"
        aliases: "{{ readarr_docker_network_aliases | default(omit) }}"

- name: "Define all Docker networks for this container"
  ansible.builtin.set_fact:
    _readarr_docker_all_networks: >
      {{ _readarr_docker_default_networks + readarr_docker_extra_networks }}

- name: "Define Docker labels with Traefik disabled"
  ansible.builtin.set_fact:
    _readarr_docker_labels: "{{ _readarr_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  with_items:
    - key: "traefik.enable"
      value: "{{ readarr_available_externally }}"
  when: "not readarr_available_externally"

- name: "Define Docker labels with Traefik enabled"
  ansible.builtin.set_fact:
    _readarr_docker_labels: "{{ _readarr_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  with_items:
    - key: "traefik.enable"
      value: "{{ readarr_available_externally }}"
    - key: "traefik.docker.network"
      value: "{{ servarr_docker_network }}"
    - key: "traefik.http.routers.readarr.rule"
      value: "Host(`{{ _readarr_docker_fqdn }}`)"
    - key: "traefik.http.routers.readarr.entrypoints"
      value: "http,https"
    - key: "traefik.http.routers.readarr.tls.certresolver"
      value: "letsencrypt"
    - key: "traefik.http.routers.readarr.tls.domains[0].main"
      value: "*.{{ readarr_docker_host_domain }}"
    - key: "traefik.http.services.readarr.loadbalancer.server.port"
      value: "{{ readarr_docker_web_port }}"
  when: "readarr_available_externally"

- name: "Define user-supplied extra Docker labels"
  ansible.builtin.set_fact:
    _readarr_docker_labels: "{{ _readarr_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  loop: "{{ readarr_docker_extra_labels | dict2items }}"

- name: "Readarr Docker Container"
  community.docker.docker_container:
    name: "{{ readarr_docker_name }}"
    image: "{{ readarr_docker_image }}:{{ readarr_docker_image_version }}"
    pull: true
    env:
      "PUID": "{{ readarr_docker_uid }}"
      "PGID": "{{ readarr_docker_gid }}"
      "TZ": "{{ readarr_docker_timezone }}"
    mounts: "{{ _readarr_docker_mount_list }}"
    network_mode: "{{ readarr_docker_network }}"
    networks: "{{ _readarr_docker_all_networks }}"
    restart_policy: unless-stopped
    memory: "{{ readarr_docker_memory }}"
    cpus: "{{ readarr_docker_cpus }}"
    container_default_behavior: no_defaults
    auto_remove: no
    detach: yes
    init: false
    interactive: no
    paused: no
    privileged: no
    read_only: no
    tty: no
    labels: "{{ _readarr_docker_labels }}"
