---
###
### Home Assistant
###

# Latitude of the location where Home Assistant is running.
hass_home_latitude: "38.8977"

# Longitude of the location where Home Assistant is running.
hass_home_longitude: "77.0365"

# Name of the location where Home Assistant is running.
hass_home_name: "home"

# Default system of units in the location where Home Assistant is running.
hass_home_units: "imperial"

hass_host_domain: "example.com"
hass_host_name: "hass"

# Timeone of the location where Home Assistant is running.
hass_home_timezone: "America/New_York"

# Name of the Docker volume to create to store config files.
hass_volume_config_name: "hass-config"

# ZWave USB stick
hass_zwave_device: "/dev/serial/by-id/usb-1234_5678-if00"

# Use Docker volumes
hass_use_volumes: "true"

# TCP port number to expose to handle HTTP traffic.
hass_web_port: "8123"

### Network
hass_network_internal: "false"
hass_network_name: "hass"
hass_network_subnet: "172.1.2.0/24"
hass_network_gateway: "172.1.2.1"

###
### Ecowit
###
hass_ecowitt_name: "ecowitt-proxy"
hass_ecowitt_docker_port: "8181"
hass_ecowitt_docker_image_name: "ghcr.io/organicveggie/home-assistant-ecowitt-proxy"
hass_ecowitt_docker_image_version: "latest"
hass_ecowitt_docker_memory: "512M"
hass_ecowitt_docker_cpus: "1"

hass_ecowitt_hass_auth_token: "ABCD"
hass_ecowitt_hass_webhook_id: "1234"

###
### Devices / Entities
###
hass_espresso_machine_device_id: "d94e677d5e0eadbce78ceb5b66116f66"
hass_espresso_machine_entity_id: "switch.plug_in_appliance_module"