---
###
### Home Assistant
###

# Latitude of the location where Home Assistant is running.
hass_home_latitude: "38.8977"

# Longitude of the location where Home Assistant is running.
hass_home_longitude: "77.0365"

# Name of the location where Home Assistant is running.
hass_home_name: "home"

# Default system of units in the location where Home Assistant is running.
hass_home_units: "imperial"

hass_host_domain: "{{ veggie_base_domain_name }}"
hass_host_name: "hass"

# Timeone of the location where Home Assistant is running.
hass_home_timezone: "{{ vault_nas_timezone }}"

# URL of the Home Assistant instance.
hass_url: "https://{{ hass_host_name }}.{{ hass_host_domain }}"

# Name of the Docker volume to create to store config files.
hass_volume_config_name: "hass-config"

# ZWave USB stick
hass_zwave_device: "/dev/serial/by-id/usb-0658_0200-if00"

### Docker

# TCP port number to expose to handle HTTP traffic.
hass_web_port: "8123"

### Network
hass_network_internal: "false"
hass_network_name: "hass"
hass_network_subnet: "{{ vault_hass_network_subnet }}"
hass_network_gateway: "{{ vault_hass_network_gateway }}"

### Recorder Database
hass_recorder_db_user: "hass"
hass_recorder_db_password: "hass-password"
hass_recorder_db_server_addr: "hass-pgsql"
hass_recorder_db_db_name: "hass"
hass_recorder_db_url: "postgresql://{{ hass_recorder_db_user }}:{{ hass_recorder_db_password }}@{{ hass_recorder_db_server_addr }}/{{ hass_recorder_db_db_name }}"
hass_use_volumes: "true"

###
### PostgreSQL
###
hass_pgsql_admin_password: "{{ vault_postgres_docker_admin_password }}"
hass_pgsql_image: "postgres:15-bullseye"
hass_pgsql_name: "hass-pgsql"
hass_pgsql_network_name: "{{ hass_network_name }}"
hass_pgsql_volume_init_name: "hass-pgsql-initscripts"
hass_pgsql_volume_conf_name: "hass-pgsql-conf"
hass_pgsql_volume_data_name: "hass-pgsql-data"
hass_pgsql_init_tempates_dir: "/mnt/nas/hass/pgsql"

###
### pgAdmin
###

# Name of the Docker container.
hass_pgadmin_host_domain: "{{ hass_host_name }}.{{ hass_host_domain }}"
hass_pgadmin_name: "hass-pgadmin"
hass_pgadmin_network_name: "{{ hass_network_name }}"
hass_pgadmin_servers:
  "pg_hass":
    Name: "Hass Postgres"
    Group: "Servers"
    Port: "5432"
    Username: "postgres"
    Host: "{{ hass_pgsql_name }}"
    SSLMode: "prefer"
    MaintenanceDB: "postgres"
hass_pgadmin_use_volumes: true
hass_pgadmin_volume_data_name: "hass-pgadmin-data"

###
### Ecowit
###
hass_ecowitt_name: "ecowitt-proxy"
hass_ecowitt_docker_port: "8181"
hass_ecowitt_docker_image_name: "ghcr.io/organicveggie/home-assistant-ecowitt-proxy"
hass_ecowitt_docker_image_version: "latest"
hass_ecowitt_docker_memory: "512M"
hass_ecowitt_docker_cpus: "1"

hass_ecowitt_hass_url: "{{ hass_url }}"
hass_ecowitt_hass_auth_token: "ABCD"
hass_ecowitt_hass_webhook_id: "1234"

hass_ecowitt_fqdn: "ecowitt.{{ hass_host_domain }}"
