---
hass_ecowitt_port: "4199"

# Latitude of the location where Home Assistant is running.
hass_home_latitude: "38.8977"

# Longitude of the location where Home Assistant is running.
hass_home_longitude: "77.0365"

# Name of the location where Home Assistant is running.
hass_home_name: "home"

# Default system of units in the location where Home Assistant is running.
hass_home_units: "imperial"

hass_host_domain: "{{ veggie_base_domain_name }}"
hass_host_name: "hass"

# Timeone of the location where Home Assistant is running.
hass_home_timezone: "{{ vault_nas_timezone }}"

# URL of the Home Assistant instance.
hass_url: "https://{{ hass_host_name }}.{{ hass_host_domain }}"

# Name of the Docker volume to create to store config files.
hass_volume_config_name: "hass-config"

# ZWave USB stick
hass_zwave_device: "/dev/serial/by-id/usb-0658_0200-if00"

### Network
hass_network_internal: "false"
hass_network_name: "hass"
hass_network_subnet: "{{ vault_hass_network_subnet }}"
hass_network_gateway: "{{ vault_hass_network_gateway }}"

### Recorder Database
hass_recorder_db_user: "hass"
hass_recorder_db_password: "hass-password"
hass_recorder_db_server_addr: "hass-pgsql"
hass_recorder_db_db_name: "hass"
hass_recorder_db_url: "postgresql://{{ hass_recorder_db_user }}:{{ hass_recorder_db_password }}@{{ hass_recorder_db_server_addr }}/{{ hass_recorder_db_db_name }}"
hass_use_volumes: "true"
