---
- name: Install dependencies
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_facts["os_family"] == 'Debian'

    - name: Wait for systemd to complete initialization
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_facts["service_mgr"] == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

- name: Converge  # noqa: command-instead-of-module var-naming[no-role-prefix]
  hosts: all
  become: true

  vars:
    mosquitto_docker_network_name: "mosquitto-test"
    mosquitto_docker_available_externally: false

  pre_tasks:
    - name: Install Docker
      ansible.builtin.include_role:
        name: geerlingguy.docker

    - name: Create mosquitto-test Docker network
      community.docker.docker_network:
        name: mosquitto-test
        state: present

  roles:
    - role: mosquitto
      vars:
        mosquitto_docker_name: "mosquitto-molecule"
