---
- name: "{{ hass_otbr_role_label }} | Build container FQDN"
  ansible.builtin.set_fact:
    _hass_otbr_fqdn: "{{ hass_otbr_host_name }}.{{ hass_otbr_host_domain }}"

- name: "{{ hass_otbr_role_label }} | Create OpenThread Border Router data volume"
  community.docker.docker_volume:
    name: "{{ hass_otbr_volume_data_name }}"

- name: "{{ hass_otbr_role_label }} | Set Docker mount list"
  ansible.builtin.set_fact:
    _hass_otbr_mount_list:
      - "source": "{{ hass_otbr_volume_data_name }}"
        "target": "/config"
        "type": "volume"

- name: "{{ hass_otbr_role_label }} | Define all Docker networks for this container"
  ansible.builtin.set_fact:
    _hass_otbr_all_networks: >
      {{ _hass_otbr_default_networks + hass_otbr_extra_networks }}
  vars:
    _hass_otbr_default_networks:
      - name: "{{ hass_otbr_network_name }}"
        aliases: "{{ hass_otbr_network_aliases | default(omit, true) }}"

- name: "{{ hass_otbr_role_label }} | Define common Docker labels"
  ansible.builtin.set_fact:
    _hass_otbr_labels: "{{ _hass_otbr_labels | default({}) |
      combine({item.key: item.value}) }}"
  with_items:
    - key: "traefik.enable"
      value: "{{ hass_otbr_available_externally | default(false, true) | string | lower | ternary('true', 'false') }}"

- name: "{{ hass_otbr_role_label }} | Define Docker labels with Traefik enabled"
  ansible.builtin.set_fact:
    _hass_otbr_labels: "{{ _hass_otbr_labels | default({}) |
      combine({item.key: item.value}) }}"
  with_items:
    - key: "traefik.http.routers.hass-otbr.rule"
      value: "Host(`{{ _hass_otbr_fqdn }}`)"
    - key: "traefik.http.routers.hass-otbr.entrypoints"
      value: "http,https"
    - key: "traefik.http.routers.hass-otbr.tls.certresolver"
      value: "letsencrypt"
    - key: "traefik.http.routers.hass-otbr.tls.domains[0].main"
      value: "*.{{ hass_otbr_host_domain }}"
    - key: "traefik.http.services.hass-otbr.loadbalancer.server.port"
      value: "{{ hass_otbr_web_port }}"
  when: "hass_otbr_available_externally | default(false, true)"

- name: "{{ hass_otbr_role_label }} | Define user-supplied extra Docker labels"
  ansible.builtin.set_fact:
    _hass_otbr_labels: "{{ _hass_otbr_labels | default({}) |
      combine({item.key: item.value}) }}"
  loop: "{{ hass_otbr_extra_labels | dict2items }}"

- name: "{{ hass_otbr_role_label }} | Define default Docker environment variables"
  ansible.builtin.set_fact:
    _hass_otbr_env_vars:
      "AUTOFLASH_FIRMWARE": "{{ hass_otbr_device_autoflash_firmware | default('none', true) | int | string }}"
      "BACKBONE_IF": "{{ hass_otbr_host_backbone_if }}"
      "BAUDRATE": "{{ hass_otbr_device_baudrate | string }}"
      "DEVICE": "/dev/ttyACM1"
      "FIREWALL": "{{ hass_otbr_enable_firewall | default(false, true) | int | string }}"
      "FLOW_CONTROL": "{{ hass_otbr_device_flow_control | default('none', true) | int | string }}"
      "NAT64": "{{ hass_otbr_enable_nat64 | default(false, true) | int | string }}"
      "OTBR_LOG_LEVEL": "{{ hass_otbr_log_level | default('info', true) }}"
      "OTBR_REST_PORT": "{{ hass_otbr_rest_port |string }}"
      "OTBR_WEB": "{{ hass_otbr_enable_webui | default(false, true) | int | string }}"
      "THREAD_1_4": "{{ hass_otbr_enable_thread_1_4 | default(false, true) | int | string }}"

- name: "{{ hass_otbr_role_label }} | Define optional Web UI Docker environment variable"
  ansible.builtin.set_fact:
    _hass_otbr_env_vars: "{{ _hass_otbr_env_vars | default({}) |
      combine({__item.key: __item.value}) }}"
  loop:
    - key: "OTBR_WEB_PORT"
      value: "{{ hass_otbr_web_port | string }}"
  loop_control:
    loop_var: __item
  when: "hass_otbr_enable_webui | default(false, true)"

- name: "{{ hass_otbr_role_label }} | Define user-supplied extra Docker environment variables"
  ansible.builtin.set_fact:
    _hass_otbr_env_vars: "{{ _hass_otbr_env_vars | default({}) |
      combine({__item.key: __item.value}) }}"
  loop: "{{ hass_otbr_extra_env | dict2items }}"
  loop_control:
    loop_var: __item

- name: "{{ hass_otbr_role_label }} | Define common Docker labels"
  ansible.builtin.set_fact:
    _hass_otbr_labels: {}

- name: "{{ hass_otbr_role_label }} | Define user-supplied extra Docker labels"
  ansible.builtin.set_fact:
    _hass_otbr_labels: "{{ _hass_otbr_labels | default({}) |
      combine({item.key: item.value}) }}"
  loop: "{{ hass_otbr_extra_labels | dict2items }}"

- name: "{{ hass_otbr_role_label }} | Create Home Assistant OpenThread Border Router container"
  community.docker.docker_container:
    name: "{{ hass_otbr_name }}"
    image: "{{ hass_otbr_image_name }}:{{ hass_otbr_image_version }}"
    pull: true
    mounts: "{{ _hass_otbr_mount_list }}"
    env: "{{ _hass_otbr_env_vars }}"
    network_mode: "{{ hass_otbr_network_name }}"
    networks: "{{ _hass_otbr_all_networks }}"
    restart_policy: unless-stopped
    memory: "{{ hass_otbr_memory }}"
    cpus: "{{ hass_otbr_cpus }}"
    devices:
      - "{{ hass_otbr_device }}:/dev/ttyACM1:rw"
    container_default_behavior: "no_defaults"
    auto_remove: false
    detach: true
    init: false
    interactive: false
    paused: false
    privileged: true
    read_only: false
    tty: false
    capabilities:
      - "NET_ADMIN"
      - "SYS_ADMIN"
    labels: "{{ _hass_otbr_labels }}"
