---
- name: "Get info on {{ __grafana_network_name }} network"
  community.docker.docker_network_info:
    name: "{{ __grafana_network_name }}"
  register: _grafana_docker_network_info

- name: "Verify {{ __grafana_network_name }} network exists"
  ansible.builtin.assert:
    that: _grafana_docker_network_info.exists
