---
- name: Create /etc/glances
  ansible.builtin.file:
    path: /etc/glances
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install glances.conf
  ansible.builtin.template:
    src: ../templates/glances.conf
    dest: /etc/glances/glances.conf
    owner: root
    group: root
  notify:
    - restart glances

- name: Create Glances Docker Container
  community.docker.docker_container:
    name: glances
    image: nicolargo/glances
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/glances/glances.conf:/glances/conf/glances.conf"
      - "/mnt/nas:/mnt/nas:ro"
    pid_mode: host
    exposed_ports:
      - "{{ glances_port }}"
    networks:
      - name: "{{ traefik_network_name }}"
    env:
      GLANCES_OPT: "-w"
    restart_policy: unless-stopped
    memory: "{{ glances_memory }}"
    container_default_behavior: no_defaults
    auto_remove: no
    detach: yes
    init: no
    interactive: no
    paused: no
    privileged: no
    read_only: no
    tty: no
    labels:
      traefik.enable: "{{ glances_available_externally }}"
      traefik.http.routers.glances.rule: "Host(`{{ glances_hostname }}.{{ glances_host_domain }}`)"
      traefik.http.routers.glances.tls.certresolver: "letsencrypt"
      traefik.http.routers.glances.tls.domains[0].main: "*.{{ glances_host_domain }}"
      traefik.http.services.glances.loadbalancer.server.port: "{{ glances_port }}"
