---
- name: Create Glances Docker Container
  docker_container:
    name: glances
    image: nicolargo/glances
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/timezone:/etc/timezone:ro"
    pid_mode: host
    ports:
      - "{{ glances_port_one }}:61208"
      - "{{ glances_port_two }}:61209"
    env:
      GLANCES_OPT: "-w"
    restart_policy: unless-stopped
    memory: "{{ glances_memory }}"
    container_default_behavior: no_defaults
    auto_remove: no
    detach: yes
    init: no
    interactive: no
    paused: no
    privileged: no
    read_only: no
    tty: no
    labels:
      traefik.enable: "{{ glances_available_externally }}"
      traefik.http.routers.glances.rule: "Host(`{{ glances_hostname }}.{{ glances_host_domain }}`)"
      traefik.http.routers.glances.tls.certresolver: "letsencrypt"
      traefik.http.routers.glances.tls.domains[0].main: "{{ glances_host_domain }}"
      traefik.http.routers.glances.tls.domains[0].sans: "*.{{ glances_host_domain }}"
      traefik.http.services.glances.loadbalancer.server.port: "61208"
