---
- name: Install python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
  register: result
  until: result is succeeded

- name: Remove docker-py python module
  ansible.builtin.pip:
    name: docker-py
    state: absent
  register: result
  until: result is succeeded

- name: Install docker python module
  ansible.builtin.pip:
    name: docker
    state: present
  register: result
  until: result is succeeded

- name: Create Docker home directory
  ansible.builtin.file:
    path: "{{ docker_home }}"
    mode: 0755
    state: directory

- name: Add user account to Docker group
  ansible.builtin.user:
    name: "{{ docker_admin_user }}"
    groups: docker
    append: yes
  when: docker_admin_user is defined

- name: Update Docker home from install default
  ansible.builtin.template:
    src: daemon.json
    dest: /etc/docker/daemon.json
  register: docker_config

- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted
  when: docker_config.changed
  tags:
    - skip_ansible_lint