---
# tasks file for traefik3
- name: "traefik3 | Build container FQDN"
  ansible.builtin.set_fact:
    _traefik3_docker_fqdn: "{{ traefik3_host_name }}.{{ traefik3_host_domain }}"

- name: "traefik3 | Create container volumes"
  community.docker.docker_volume:
    name: "{{ __item }}"
  loop:
    - "{{ traefik3_config_volume_name }}"
    - "{{ traefik3_log_volume_name }}"
  loop_control:
    loop_var: __item

- name: "traefik3 | Get info on config volume"
  community.docker.docker_volume_info:
    name: "{{ traefik3_config_volume_name }}"
  register: "_traefik3_config_volume_info"

- name: "traefik3 | Build target path to config volume"
  ansible.builtin.set_fact:
    _traefik3_config_volume_path:
      "{{ _traefik3_config_volume_info['volume']['Mountpoint'] }}"

- name: "traefik3 | Dashboard"
  when: "traefik3_dashboard_enabled"
  block:
    - name: "traefik3 | Dashboard | FQDN length"
      ansible.builtin.set_fact:
        __dashboard_fqdn_empty: "{{ traefik3_dashboard_fqdn | default('', true) | string | length <= 0 }}"

    - name: "traefik3 | Dashboard | Set FQDN"
      ansible.builtin.set_fact:
        _traefik3_dashboard_fqdn: "{{ __dashboard_fqdn_empty | ternary(_traefik3_docker_fqdn, traefik3_dashboard_fqdn) }}"
    
    - name: "traefik3 | Dashboard | insecure entrypoint"
      ansible.builtin.set_fact:
        _traefik3_dashboard_insecure_entrypoint: "{ '{{ traefik3_entrypoint_insecure }}': {{ __insecure_fields }} }"
      vars:
        __insecure_fields:
            address: ":{{ traefik3_entrypoint_insecure_port }}"
            reusePort: true
            forwardedHeaders:
              trustedIPs: "{{ traefik3_trusted_ips | default(omit) }}"
            http:
              redirections:
                entryPoint:
                  to: "{{ traefik3_entrypoint_secure }}"
                  scheme: https
                  permanent: "{{ traefik3_dashboard_entrypoint_permanent_redirect }}"
            observability: "{{ traefik3_dashboard_entrypoint_observability | default(omit) }}"

    - name: "traefik3 | Dashboard | secure entrypoint"
      ansible.builtin.set_fact:
        _traefik3_dashboard_secure_entrypoint: "{ '{{ traefik3_entrypoint_secure }}': {{ __secure_fields }} }"
      vars:
        __secure_fields:
          address: ":{{ traefik3_entrypoint_secure_port }}"
          reusePort: true
          asDefault: true
          forwardedHeaders:
            trustedIPs: "{{ traefik3_trusted_ips | default(omit) }}"
          observability: "{{ traefik3_dashboard_entrypoint_observability | default(omit) }}"

    - name: "traefik3 | Dashboard | entrypoints"
      ansible.builtin.set_fact:
        _traefik3_dashboard_entrypoints: "{{ _traefik3_dashboard_insecure_entrypoint | combine(_traefik3_dashboard_secure_entrypoint) }}"

    - name: "traefik3 | Dashboard | insecure api entrypoint"
      ansible.builtin.set_fact:
        _traefik3_dashboard_entrypoints: >
          {{ _traefik3_dashboard_entrypoints | default({}) | combine(_traefik3_api_insecure_entrypoint) }}
      vars:
        _traefik3_api_insecure_entrypoint:
          traefik:
            address: ":8181"
            reusePort: true
            observability: "{{ traefik3_dashboard_entrypoint_observability | default(omit) }}"
      when: "traefik3_dashboard_api_insecure"

    - name: "traefik3 | Dashboard | middleware"
      ansible.builtin.set_fact:
        _traefik3_dashboard_labels: >
          {{ _traefik3_dashboard_labels | default({}, true) | combine({__key: __value}) }}
      vars:
        __key: "traefik.http.routers.dashboard.middlewares"
        __value: "{{ traefik3_dashboard_middleware_names }}"
      when: "traefik3_dashboard_middleware_names | default('', true) | string | length > 0"

    - name: "traefik3 | Dashboard | router labels"
      ansible.builtin.set_fact:
        _traefik3_dashboard_labels: >
          {{ _traefik3_dashboard_labels | default({}, true) | combine({__item.key: __item.value}) }}
      loop:
        - key: "traefik.http.routers.dashboard.rule"
          value: "Host(`{{ _traefik3_dashboard_fqdn }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
        - key: "traefik.http.routers.dashboard.service"
          value: "api@internal"
        - key: "traefik.http.routers.dashboard.entrypoints"
          value: "{{ traefik3_entrypoint_secure }}"
        - key: "traefik.http.routers.dashboard.tls"
          value: "true"
        - key: "traefik.http.routers.dashboard.tls.certresolver"
          value: "letsencrypt"
        - key: "traefik.http.routers.dashboard.tls.domains[0].main"
          value: "{{ _traefik3_dashboard_fqdn }}"
      loop_control:
        loop_var: __item

- name: "traefik3 | Define container labels"
  ansible.builtin.set_fact:
    _traefik3_all_labels: >
      {{ __labels_dashboard | combine(__labels_traefik_enable) }}
  vars:
    __labels_dashboard: "{{ _traefik3_dashboard_labels | default({}, true) }}"
    __labels_traefik_enable:
      traefik.enable: "true"

- name: "traefik3 | Access Log options"
  when: "traefik3_conf_access_log_enabled"
  block:
    - name: "traefik3 | access logs | filters"
      ansible.builtin.set_fact:
        _traefik3_access_log_filters:
          filters: "{{ traefik3_conf_access_log_filters }}"
      when: "traefik3_conf_access_log_filters | dict2items | length > 0"

    - name: "traefik3 | access logs | fields names"
      ansible.builtin.set_fact:
        _traefik3_access_log_fields_names:
          names: "{{ traefik3_conf_access_log_fields_names }}"
      when: "traefik3_conf_access_log_fields_names | dict2items | length > 0"
      
    - name: "traefik3 | access logs | header names"
      ansible.builtin.set_fact:
        _traefik3_access_log_header_names:
          names: "{{ traefik3_conf_access_log_headers_names }}"
      when: "traefik3_conf_access_log_headers_names | dict2items | length > 0"

    - name: "traefik3 | access logs | headers"
      ansible.builtin.set_fact:
        _traefik3_access_log_headers: >
          {{ __access_logs_headers_mode | combine(__access_logs_headers_names) | combine(__access_logs_headers_extras) }}
      vars:
        __access_logs_headers_extras: "{{ traefik3_conf_access_log_headers_extras | default({}, true) }}"
        __access_logs_headers_names:
          names: "{{ _traefik3_access_log_header_names | default('', true) }}"
        __access_logs_headers_mode:
          defaultMode: "{{ traefik3_conf_access_log_headers_default_mode }}"
      when: "traefik3_conf_access_log_headers_names | dict2items | length > 0"

    - name: "traefik3 | access logs | fields"
      ansible.builtin.set_fact:
        _traefik3_access_log_fields: >
          {{ __access_logs_fields_mode | combine(__access_logs_names) | combine(__access_logs_extras) }}
      vars:
        __access_logs_extras: "{{ traefik3_conf_access_log_fields_extras | default({}, true) }}"
        __access_logs_names: "{{ _traefik3_access_log_fields_names | default('', true) }}"
        __access_logs_fields_mode:
          defaultMode: "{{ traefik3_conf_access_log_fields_default_mode }}"

    - name: "traefik3 | access logs | main options"
      ansible.builtin.set_fact:
        _traefik3_access_log_all_options:
          accessLog: >
            {{ __access_log_options | combine(__access_logs_filters) | combine(__access_log_extras) }}
      vars:
        __access_log_extras: "{{ traefik3_conf_access_log_extra_options | default({}, true) }}"
        __access_logs_filters: "{{ _traefik3_access_log_filters | default({}, true) }}"
        __access_log_options:
          bufferingSize: "{{ traefik3_conf_access_log_buffering_size | default(0, true) | int }}"
          filePath: "{{ traefik3_conf_access_log_file }}"
          format: "{{ traefik3_conf_access_log_format }}"
          fields:
            defaultMode: "{{ traefik3_conf_access_log_fields_default_mode }}"
            headers: "{{ _traefik3_access_log_headers | default(omit) }}"
            names: "{{ traefik3_conf_access_log_fields_names | default(omit)  }}"

- name: "traefik3 | Trusted IPs"
  ansible.builtin.set_fact:
    _traefik3_trusted_ips:
      forwardedHeaders:
        trustedIPs: "{{ traefik3_trusted_ips | default(omit) }}"
  when: "traefik3_trusted_ips | default('', true) | string | length > 0"

- name: "traefik3 | Logging options"
  ansible.builtin.set_fact:
    _traefik3_logging_all_options:
      log: >
        {{ __logging_quick_options | combine(__logging_extras) }}
  vars:
    __logging_extras: "{{ traefik3_conf_logging_extra_options | default({}) }}"
    __logging_quick_options:
        filePath: "{{ traefik3_conf_logging_file }}"
        format: "{{ traefik3_conf_logging_format }}"
        level: "{{ traefik3_conf_logging_level }}"

- name: "traefik3 | Metrics options"
  ansible.builtin.set_fact:
    _traefik3_metrics_all_options:
      metrics: "{{ traefik3_conf_metrics }}"

- name: "traefik3 | Create config file"
  ansible.builtin.template:
    src: "templates/traefik.yml.j2"
    dest: "{{ _traefik3_config_volume_path }}/traefik.yml"
    mode: "0644"
  vars:
    _traefik3_conf_cert_resolvers:
      certificatesResolvers: "{{ traefik3_conf_cert_resolvers }}"
    _traefik3_conf_entrypoints:
      entrypoints: "{{ _traefik3_dashboard_entrypoints | default({}) | combine(traefik3_conf_entrypoints | default({})) }}"
    _traefik3_conf_providers:
      providers: "{{ traefik3_conf_providers }}"
    _traefik3_conf_tracing:
      tracing: "{{ traefik3_conf_tracing_options | default({}) }}"
  register: "_traefik3_config"

- name: "traefik3 | Set Docker mount list for bind mounts"
  ansible.builtin.set_fact:
    _traefik3_bind_mount_list: "{{_traefik3_docker_bind_mount_list | default([]) +
      [ {'source': __item.key, 'target': __item.value, 'read_only': true, 'type': 'bind'} ] }}"
  loop: "{{ traefik3_bind_mounts | dict2items }}"
  loop_control:
    loop_var: __item

- name: "traefik3 | Set combined Docker mount list"
  ansible.builtin.set_fact:
    _traefik3_complete_mount_list: "{{ _traefik3_bind_mount_list + _traefik3_volume_mounts }}"
  vars:
    _traefik3_volume_mounts:
      - source: "{{ traefik3_config_volume_name }}"
        target: "/etc/traefik"
        type: "volume"
      - source: "{{ traefik3_log_volume_name }}"
        target: "/var/log/traefik"
        type: "volume"

- name: "traefik3 | Create placeholder array for default network"
  ansible.builtin.set_fact:
    _traefik3_docker_default_networks:
      - name: "{{ traefik3_network_name }}"
        aliases: "{{ traefik3_network_aliases | default(omit) }}"

- name: "traefik3 | Define all Docker networks for this container"
  ansible.builtin.set_fact:
    _traefik3_docker_all_networks: >
      {{ _traefik3_docker_default_networks + traefik3_extra_networks | default([]) }}

- name: "traefik3 | Define Docker port map"
  ansible.builtin.set_fact:
    _traefik3_docker_ports: "{{ _traefik3_docker_ports | default([]) + [__item] }}"
  loop: "{{ traefik3_port_map_list }}"
  loop_control:
    loop_var: __item

- name: "traefik3 | Define common environment variables"
  ansible.builtin.set_fact:
    _traefik3_all_env_vars: >
      {{ _traefik3_std_env_vars | combine(traefik3_extra_env_vars) }}
  vars:
    _traefik3_std_env_vars:
      "TZ": "{{ traefik3_timezone }}"

- name: "traefik3 | Define extra environment variables"
  ansible.builtin.set_fact:
    _traefik3_all_env_vars: "{{ _traefik3_all_env_vars | default({}) |
      combine({__item.key: __item.value}) }}"
  loop: "{{ traefik3_extra_env_vars | dict2items }}"
  loop_control:
    loop_var: __item
  no_log: True

- name: "traefik3 | Debug | container labels"
  ansible.builtin.debug:
    msg: "{{ _traefik3_all_labels }}"

- name: "traefik3 | Debug | mount points"
  ansible.builtin.debug:
    msg:
      - "{{ _traefik3_complete_mount_list }}"

- name: "traefik3 | Create Traefik3 Docker container"  # noqa: args[module]
  community.docker.docker_container:
    name: "{{ traefik3_name }}"
    image: "{{ traefik3_image_name }}:{{ traefik3_image_version }}"
    pull: true
    mounts: "{{ _traefik3_complete_mount_list }}"
    env: "{{ _traefik3_all_env_vars | default({}, true) }}"
    network_mode: "{{ traefik3_network_name }}"
    networks: "{{ _traefik3_docker_all_networks }}"
    published_ports: "{{ _traefik3_docker_ports | default([], true) }}"
    restart: "{{ _traefik3_config.changed | default(false) }}"
    memory: "{{ traefik3_memory }}"
    cpus: "{{ traefik3_cpus }}"
    command_handling: "correct"
    container_default_behavior: "no_defaults"
    auto_remove: false
    detach: true
    init: true
    interactive: true
    paused: false
    privileged: false
    read_only: false
    tty: true
    labels: "{{ _traefik3_all_labels }}"
