restic_server_name: "restic.example.com"
restic_repo_name: "{{ inventory_hostname }}"
restic_repo_password: "secret"

restic_client_user: "user"
restic_client_passwd: "password"

restic_client_include_paths: []
restic_client_exclude_paths: []

restic_user: "restic"
restic_group: "restic"

restic_config_folder: "/etc/restic"
restic_config_location_file: "{{ restic_config_folder }}/repo.txt"
restic_config_location_script_file: "{{ restic_config_folder }}/repo-env.sh"
restic_config_password_file: "{{ restic_config_folder }}/password.txt"

restic_client_admin_email: "user@example.com"
restic_client_cache_dir: "/var/cache/restic"
restic_client_backup_script: "/usr/local/sbin/restic-backup.sh"
restic_client_export_script: "/usr/local/sbin/restic-export.sh"
restic_client_failure_script: "/usr/local/sbin/systemd-unit-failure.sh"
restic_client_forget_script: "/usr/local/sbin/restic-forget.sh"
restic_client_prune_script: "/usr/local/sbin/restic-prune.sh"
restic_client_backup_includes_file: "{{ restic_config_folder }}/includes"
restic_client_backup_excludes_file: "{{ restic_config_folder }}/excludes"
