---
- name: Copy htpasswd
  ansible.builtin.copy:
    src: htpasswd
    dest: "{{ restic_rest_server_backup_dir }}/.htpasswd"
    mode: 0600

- name: Create restic Rest Server Docker Container
  community.docker.docker_container:
    name: rest-server
    image: restic/rest-server
    pull: true
    volumes:
      - "{{ restic_rest_server_backup_dir }}:/data"
    network_mode: host
    env:
      OPTIONS: "--private-repos"
    restart_policy: unless-stopped
    memory: "{{ restic_rest_server_memory }}"
    container_default_behavior: no_defaults
    auto_remove: no
    detach: yes
    init: no
    interactive: no
    paused: no
    privileged: no
    read_only: no
    tty: no
    labels:
      traefik.enable: "{{ restic_rest_server_available_externally }}"
      traefik.http.routers.restic_rest_server.rule: "Host(`{{ restic_rest_server_hostname }}.{{ restic_rest_server_host_domain }}`)"
      traefik.http.routers.restic_rest_server.tls.certresolver: "letsencrypt"
      traefik.http.routers.restic_rest_server.tls.domains[0].main: "{{ restic_rest_server_host_domain }}"
      traefik.http.routers.restic_rest_server.tls.domains[0].sans: "*.{{ restic_rest_server_host_domain }}"
      traefik.http.services.restic_rest_server.loadbalancer.server.port: "{{ restic_rest_server_port }}"
