---
- name: Create restic Rest Server Docker Container
  community.docker.docker_container:
    name: rest-server
    image: restic/rest-server
    pull: true
    volumes:
      - "{{ restic_rest_server_backup_dir }}:/data"
      - "/etc/letsencrypt:/letsencrypt:ro"
    network_mode: "{{ restic_rest_server_network_name }}"
    env:
      OPTIONS: >-
        --private-repos
    restart_policy: unless-stopped
    memory: "{{ restic_rest_server_memory }}"
    container_default_behavior: no_defaults
    auto_remove: no
    detach: yes
    init: no
    interactive: no
    paused: no
    privileged: no
    read_only: no
    tty: no
    labels:
      traefik.enable: "{{ restic_rest_server_available_externally }}"
      traefik.docker.network: "{{ restic_rest_server_network_name }}"
      traefik.http.routers.rest-server.rule: "Host(`{{ restic_rest_server_hostname }}.{{ restic_rest_server_host_domain }}`)"
      traefik.http.routers.rest-server.entrypoints: "https"
      traefik.http.routers.rest-server.tls.certresolver: "letsencrypt"
      traefik.http.routers.rest-server.tls.domains[0].main: "*.{{ restic_rest_server_host_domain }}"
      traefik.http.services.rest-server.loadbalancer.server.port: "{{ restic_rest_server_port }}"
