---
- name: Install python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
  register: result
  until: result is succeeded

- name: Remove docker-py python module
  ansible.builtin.pip:
    name: docker-py
    state: absent
  register: result
  until: result is succeeded

- name: Install docker python module
  ansible.builtin.pip:
    name: docker
    state: present
  register: result
  until: result is succeeded

- name: Copy htpasswd
  ansible.builtin.copy:
    src: htpasswd
    dest: "{{ restic_rest_server_backup_dir }}/.htpasswd"
    mode: 0600

- name: Create restic Rest Server Docker Container
  community.docker.docker_container:
    name: rest-server
    image: restic/rest-server
    pull: true
    volumes:
      - "{{ restic_rest_server_backup_dir }}:/data"
    network_mode: host
    env:
      OPTIONS: "--private-repos"
    restart_policy: unless-stopped
    memory: "{{ restic_rest_server_memory }}"
    container_default_behavior: no_defaults
    auto_remove: no
    detach: yes
    init: no
    interactive: no
    paused: no
    privileged: no
    read_only: no
    tty: no
    labels:
      traefik.enable: "false"
