---

- name: "{{ traefik2_role_label }} | config | generate https entrypoint config"
  ansible.builtin.set_fact:
    traefik2_int_conf_entrypoints: "{{ traefik2_int_conf_entrypoints |
      combine(traefik2_int_conf_entrypoints_https) }}"
  when: "traefik2_qs_https | default(false, true)"

- name: "{{ traefik2_role_label }} | config | generate https redirect config"
  ansible.builtin.set_fact:
    traefik2_int_conf_entrypoints: "{{ traefik2_int_conf_entrypoints |
      combine(traefik2_int_conf_entrypoints_https_redirect, recursive=True) }}"
  when: "traefik2_qs_https and traefik2_qs_https_redirect"

- name: "{{ traefik2_role_label }} | config | generate neutral certresolver"
  ansible.builtin.set_fact:
    traefik2_conf_certificatesresolvers: "{{ traefik2_int_conf_certificatesResolvers_le }}"
  when: "traefik2_qs_https and traefik2_qs_https_le"

- name: "{{ traefik2_role_label }} | config | generate neutral certresolver"
  ansible.builtin.set_fact:
    traefik2_conf_certificatesresolvers: >
      {{ traefik2_conf_certificatesresolvers | default({}) | combine(traefik2_confkey_certificatesResolvers) }}
  when: "traefik2_confkey_certificatesResolvers is defined"

- name: "{{ traefik2_role_label }} | config | generate static config"
  ansible.builtin.set_fact:
    traefik2_static_config:
      global: "{{ traefik2_conf_global }}"
      serversTransport: "{{traefik2_confkey_serversTransport | default(omit) }}"
      entryPoints: "{{ traefik2_conf_entryPoints }}"
      providers: "{{ traefik2_conf_providers }}"
      api: "{{ traefik2_confkey_api | default(omit) }}"
      metrics: "{{ traefik2_confkey_metrics | default(omit) }}"
      ping: "{{ traefik2_confkey_ping | default(omit) }}"
      log: "{{ traefik2_conf_log }}"
      accessLog: "{{  traefik2_confkey_accessLog | default(omit) }}"
      tracing: "{{ traefik2_confkey_tracing | default(omit) }}"
      hostResolver: "{{ traefik2_confkey_hostResolver | default(omit) }}"
      certificatesResolvers: "{{ traefik2_conf_certificatesresolvers | default(omit) }}"
