---
- name: "Create prowlarr Docker config volume"
  community.docker.docker_volume:
    name: "{{ prowlarr_docker_volume_config_name }}"

- name: "Set Docker mount list for volume mounts"
  ansible.builtin.set_fact:
    _prowlarr_docker_mount_list:
      - source: "{{ prowlarr_docker_volume_config_name }}"
        target: "/config"
        type: "volume"

- name: "Build container FQDN"
  ansible.builtin.set_fact:
    _prowlarr_docker_fqdn: "{{ prowlarr_docker_host_name }}.{{ prowlarr_docker_host_domain }}"

- name: "Create placeholder array for default network"
  ansible.builtin.set_fact:
    _prowlarr_docker_default_networks:
      - name: "{{ prowlarr_docker_network }}"
        aliases: "{{ prowlarr_docker_network_aliases | default(omit) }}"

- name: "Define all Docker networks for this container"
  ansible.builtin.set_fact:
    _prowlarr_docker_all_networks: >
      {{ _prowlarr_docker_default_networks + prowlarr_docker_extra_networks }}

- name: "Define Docker labels with Traefik disabled"
  ansible.builtin.set_fact:
    _prowlarr_docker_labels: "{{ _prowlarr_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  with_items:
    - key: "traefik.enable"
      value: "{{ prowlarr_available_externally }}"
  when: "not prowlarr_available_externally"

- name: "Define Docker labels with Traefik enabled"
  ansible.builtin.set_fact:
    _prowlarr_docker_labels: "{{ _prowlarr_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  with_items:
    - key: "traefik.enable"
      value: "{{ prowlarr_available_externally }}"
    - key: "traefik.docker.network"
      value: "{{ servarr_docker_network }}"
    - key: "traefik.http.routers.prowlarr.rule"
      value: "Host(`{{ _prowlarr_docker_fqdn }}`)"
    - key: "traefik.http.routers.prowlarr.entrypoints"
      value: "http,https"
    - key: "traefik.http.routers.prowlarr.tls.certresolver"
      value: "letsencrypt"
    - key: "traefik.http.routers.prowlarr.tls.domains[0].main"
      value: "*.{{ prowlarr_docker_host_domain }}"
    - key: "traefik.http.services.prowlarr.loadbalancer.server.port"
      value: "{{ prowlarr_docker_web_port }}"
  when: "prowlarr_available_externally"

- name: "Define user-supplied extra Docker labels"
  ansible.builtin.set_fact:
    _prowlarr_docker_labels: "{{ _prowlarr_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  loop: "{{ prowlarr_docker_extra_labels | dict2items }}"

- name: "Prowlarr Docker Container"
  community.docker.docker_container:
    name: "{{ prowlarr_docker_name }}"
    image: "{{ prowlarr_docker_image }}:{{ prowlarr_docker_image_version }}"
    pull: true
    env:
      "PUID": "{{ prowlarr_docker_uid }}"
      "PGID": "{{ prowlarr_docker_gid }}"
      "TZ": "{{ prowlarr_docker_timezone }}"
    mounts: "{{ _prowlarr_docker_mount_list }}"
    network_mode: "{{ prowlarr_docker_network }}"
    networks: "{{ _prowlarr_docker_all_networks }}"
    restart_policy: unless-stopped
    memory: "{{ prowlarr_docker_memory }}"
    cpus: "{{ prowlarr_docker_cpus }}"
    container_default_behavior: no_defaults
    auto_remove: no
    detach: yes
    init: no
    interactive: no
    paused: no
    privileged: no
    read_only: no
    tty: no
    labels: "{{ _prowlarr_docker_labels }}"
