---
#####
# Container settings
#####

# Name of the Docker container.
sabnzbd_docker_name: "sabnzbd"

# Base name of the Docker image to use for the container.
sabnzbd_docker_image: "lscr.io/linuxserver/sabnzbd"

# Specific Docker image version to use for the container.
sabnzbd_docker_image_version: "latest"

# Group ID to use inside the container.
sabnzbd_docker_gid: "1000"

# User ID to use inside the container.
sabnzbd_docker_uid: "1000"

# Timezone to use inside the container.
sabnzbd_docker_timezone: "America/New_York"

sabnzbd_docker_data_source_path: "/data"
sabnzbd_docker_volume_config_name: "sabnzbd-config"

# Number of vCPUs to allocate to the container.
sabnzbd_docker_cpus: "2"

# Amount of memory to allocate to the container.
sabnzbd_docker_memory: "2GB"

# TCP port number to expose to handle HTTP traffic.
sabnzbd_docker_web_port: "8080"

# Dictionary of extra key value pairs to set as labels on the Docker container.
sabnzbd_docker_extra_labels: {}

# Default Docker network.
sabnzbd_docker_network: "servarr"

# List of additional networks the container should attach to. Elements should be dictionaries like
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-networks.
sabnzbd_docker_extra_networks: []

# List of aliases for this container in the default network. These names can be used in the default
# network to reach this container.
sabnzbd_docker_network_aliases: []

#####
# Traefik
#####

# Enable use of Traefik as a proxy.
sabnzbd_docker_available_externally: "true"

# Host name to use for the Traefik endpoint. Combined with [sabnzbd_docker_host_domain] to form the
# FQDN for the endpoint.
sabnzbd_docker_host_name: "sabnzbd"

# Domain name to use for the Traefik endpoint. Combined with [sabnzbd_docker_host_name] to form the
# FQDN for the endpoint. Also used by Traefik to create the necessary Let's Encrypt certificate.
sabnzbd_docker_host_domain: "example.com"
