---
allow_duplicates: true
galaxy_info:
  role_name: "sonarr"
  author: "organicveggie"
  description: "Role to install Sonarr container on Linux."

  license: "license GPL-3.0-only"

  min_ansible_version: "2.14"

  platforms:
    - name: "EL"
      versions:
        - "8"
    - name: "Fedora"
      versions:
        - "35"
        - "36"
    - name: "Debian"
      versions:
        - "buster"
        - "bullseye"
    - name: "Ubuntu"
      versions:
        - "bionic"
        - "focal"
        - "jammy"
  galaxy_tags:
    - "radarr"
    - "docker"
    - "linux"

dependencies: []
