---
- name: "Set Docker mount list for volume mounts"
  ansible.builtin.set_fact:
    _fact_influxdb_docker_mount_list:
      - source: "{{ influxdb_docker_config_volume_name }}"
        target: "/etc/influxdb2"
        type: "volume"
      - source: "{{ influxdb_docker_data_volume_name }}"
        target: "/var/lib/influxdb2"
        type: "volume"

- name: "Define all Docker networks for this container"
  ansible.builtin.set_fact:
    _fact_influxdb_docker_all_networks: "{{ influxdb_docker_extra_networks }}"

- name: "Build container FQDN"
  ansible.builtin.set_fact:
    _influxdb_docker_fqdn: "{{ influxdb_docker_hostname }}.{{ influxdb_docker_host_domain }}"

- name: "Define environment variables"
  ansible.builtin.set_fact:
    _fact_influxdb_docker_env_vars: "{{ influxdb_docker_extra_env_vars | default({}) | 
      combine({item.key: item.value})}}"
  with_items:
      - key: "INFLUXD_HTTP_BIND_ADDRESS"
        value: ":{{ influxdb_docker_web_port }}"

- name: "Define Docker labels with Traefik disabled"
  ansible.builtin.set_fact:
    _influxdb_docker_labels: "{{ _influxdb_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  with_items:
    - key: "traefik.enable"
      value: "{{ influxdb_available_externally }}"
  when: "not influxdb_docker_available_externally"

- name: "Define Docker labels with Traefik enabled"
  ansible.builtin.set_fact:
    _influxdb_docker_labels: "{{ _influxdb_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  with_items:
    - key: "traefik.enable"
      value: "true"
    - key: "traefik.docker.network"
      value: "{{ influxdb_docker_network }}"
    - key: "traefik.http.routers.influxdb27.rule"
      value: "Host(`{{ _influxdb_docker_fqdn }}`)"
    - key: "traefik.http.routers.influxdb27.entrypoints"
      value: "http,https"
    - key: "traefik.http.routers.influxdb27.tls.certresolver"
      value: "letsencrypt"
    - key: "traefik.http.routers.influxdb27.tls.domains[0].main"
      value: "*.{{ influxdb_docker_host_domain }}"
    - key: "traefik.http.services.influxdb27.loadbalancer.server.port"
      value: "{{ influxdb_docker_web_port }}"
  when: "influxdb_docker_available_externally"

- name: "Define user-supplied extra Docker labels"
  ansible.builtin.set_fact:
    _influxdb_docker_labels: "{{ _influxdb_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  loop: "{{ influxdb_docker_extra_labels | dict2items }}"

- name: "Create InfluxDB Docker container" # noqa: args[module]
  community.docker.docker_container:
    name: "{{ influxdb_docker_name }}"
    image: "{{ influxdb_docker_image_name }}:{{ influxdb_docker_image_version }}"
    pull: true
    env: "{{ _fact_influxdb_docker_env_vars }}"
    mounts: "{{ _fact_influxdb_docker_mount_list }}"
    network_mode: "{{ influxdb_docker_network }}"
    networks: "{{ _fact_influxdb_docker_all_networks }}"
    restart_policy: unless-stopped
    memory: "{{ influxdb_docker_memory }}"
    cpus: "{{ influxdb_docker_cpus }}"
    container_default_behavior: "no_defaults"
    auto_remove: false
    detach: true
    image_name_mismatch: "ignore"
    init: true
    interactive: false
    paused: false
    privileged: false
    read_only: false
    tty: false
    labels: "{{ _influxdb_docker_labels }}"
