---
- name: "Enable Universe repository"
  ansible.builtin.apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu {{ veggie_common_release_name }} universe"
    state: present
    update_cache: true

- name: "Update apt-cache"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  register: result
  until: result is succeeded

- name: "Upgrade all packages"
  ansible.builtin.apt:
    upgrade: yes
    state: latest
  when: veggie_common_keep_packages_updated

- name: "Install some packages"
  ansible.builtin.apt:
    name: "{{ veggie_common_extra_packages }}"
    state: present
  register: result
  until: result is succeeded

- name: "Set hostname to {{ veggie_common_hostname }}"
  ansible.builtin.hostname:
    name: "{{ veggie_common_hostname }}"

- name: "Set timezone to {{ veggie_common_timezone }}"
  community.general.timezone:
    name: "{{ veggie_common_timezone }}"

- name: "Create admin user"
  ansible.builtin.user:
    name: "{{ veggie_common_admin_username }}"
    shell: "/bin/bash"
    state: present
    password: "{{ veggie_common_admin_passwd }}"
    update_password: "on_create"
