---
- name: Enable Universe repository
  ansible.builtin.apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu focal universe
    state: present
    update_cache: True

- name: Update apt-cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  register: result
  until: result is succeeded

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: yes
    state: latest
  when: keep_packages_updated
  tags:
    - skip_ansible_lint

- name: Install some packages
  ansible.builtin.apt:
    name: "{{ veggie_extra_packages }}"
    state: present
  register: result
  until: result is succeeded

- name: "Set hostname to {{ veggie_hostname }}"
  ansible.builtin.hostname:
    name: "{{ veggie_hostname }}"

- name: "Set timezone to {{ veggie_timezone }}"
  community.general.timezone:
    name: "{{ veggie_timezone }}"

- name: Create admin user
  ansible.builtin.user:
    name: "{{ veggie_admin_username }}"
    shell: /bin/bash
    state: present
    password: "{{ veggie_admin_passwd }}"
    update_password: on_create

- name: Create additional users
  ansible.builtin.user:
    name: "{{ item.key }}"
    shell: /usr/bin/false
    state: present
    password: "{{ item.value }}"
    update_password: always
  loop: "{{ veggie_users_passwords | dict2items }}"
