---
- name: "{{ sonarr_docker_role_label }} | Create sonarr Docker config volume"
  community.docker.docker_volume:
    name: "{{ sonarr_docker_volume_config_name }}"

- name: "{{ sonarr_docker_role_label }} | Set base Docker mount list"
  ansible.builtin.set_fact:
    _sonarr_docker_mount_list:
      - source: "{{ sonarr_docker_volume_config_name }}"
        target: "/config"
        type: "volume"
      - source: "{{ sonarr_docker_data_source_path }}"
        target: "/data"
        type: "bind"
      - source: "{{ sonarr_docker_tv_source_path }}"
        target: "/data/media/tv"
        type: "bind"

- name: "{{ sonarr_docker_role_label }} | Check additional mount list"
  ansible.builtin.set_fact:
    _sonarr_docker_extra_mount_list: "{{ sonarr_docker_extra_mounts | default([])  }}"

- name: "{{ sonarr_docker_role_label }} | Set additional mount list"
  ansible.builtin.set_fact:
    _sonarr_docker_mount_list: "{{ _sonarr_docker_mount_list + _sonarr_docker_extra_mount_list }}"

- name: "{{ sonarr_docker_role_label }} | Build container FQDN"
  ansible.builtin.set_fact:
    _sonarr_docker_fqdn: "{{ sonarr_docker_host_name }}.{{ sonarr_docker_host_domain }}"

- name: "{{ sonarr_docker_role_label }} | Create placeholder array for default network"
  ansible.builtin.set_fact:
    _sonarr_docker_default_networks:
      - name: "{{ sonarr_docker_network }}"
        aliases: "{{ sonarr_docker_network_aliases | default(omit) }}"

- name: "{{ sonarr_docker_role_label }} | Define all Docker networks for this container"
  ansible.builtin.set_fact:
    _sonarr_docker_all_networks: >
      {{ _sonarr_docker_default_networks + sonarr_docker_extra_networks }}

- name: "{{ sonarr_docker_role_label }} | Define placeholder map for Docker labels"
  ansible.builtin.set_fact:
    _sonarr_docker_labels: {}

- name: "{{ sonarr_docker_role_label }} | Define Docker labels with Traefik disabled"
  ansible.builtin.set_fact:
    _sonarr_docker_labels: "{{ _sonarr_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  with_items:
    - key: "traefik.enable"
      value: "{{ sonarr_available_externally }}"
  when: "not sonarr_docker_available_externally"

- name: "{{ sonarr_docker_role_label }} | Define Docker labels with Traefik enabled"
  ansible.builtin.set_fact:
    _sonarr_docker_labels: "{{ _sonarr_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  with_items:
    - key: "traefik.enable"
      value: "{{ sonarr_docker_available_externally }}"
    - key: "traefik.docker.network"
      value: "{{ servarr_docker_network }}"
    - key: "traefik.http.routers.{{ sonarr_docker_host_name }}.rule"
      value: "Host(`{{ _sonarr_docker_fqdn }}`)"
    - key: "traefik.http.routers.{{ sonarr_docker_host_name }}.entrypoints"
      value: "http,https"
    - key: "traefik.http.routers.{{ sonarr_docker_host_name }}.tls.certresolver"
      value: "letsencrypt"
    - key: "traefik.http.routers.{{ sonarr_docker_host_name }}.tls.domains[0].main"
      value: "*.{{ sonarr_docker_host_domain }}"
    - key: "traefik.http.services.{{ sonarr_docker_host_name }}.loadbalancer.server.port"
      value: "{{ sonarr_docker_web_port }}"
  when: "sonarr_docker_available_externally"

- name: "{{ sonarr_docker_role_label }} | Define user-supplied extra Docker labels"
  ansible.builtin.set_fact:
    _sonarr_docker_labels: "{{ _sonarr_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  loop: "{{ sonarr_docker_extra_labels | dict2items }}"

- name: "{{ sonarr_docker_role_label }} | sonarr Docker Container"
  community.docker.docker_container:
    name: "{{ sonarr_docker_name }}"
    image: "{{ sonarr_docker_image }}:{{ sonarr_docker_image_version }}"
    pull: true
    env:
      "PUID": "{{ sonarr_docker_uid }}"
      "PGID": "{{ sonarr_docker_gid }}"
      "TZ": "{{ sonarr_docker_timezone }}"
    mounts: "{{ _sonarr_docker_mount_list }}"
    network_mode: "{{ sonarr_docker_network }}"
    networks: "{{ _sonarr_docker_all_networks }}"
    restart_policy: unless-stopped
    memory: "{{ sonarr_docker_memory }}"
    cpus: "{{ sonarr_docker_cpus }}"
    container_default_behavior: no_defaults
    auto_remove: no
    detach: yes
    init: no
    interactive: no
    paused: no
    privileged: no
    read_only: no
    tty: no
    labels: "{{ _sonarr_docker_labels }}"
