---
- name: "Get info on {{ __molecule_volume_name }} volume"
  community.docker.docker_volume_info:
    name: "{{ __molecule_volume_name }}"
  register: __volume_info

- name: "Verify {{ __molecule_volume_name }} volume exists"
  ansible.builtin.assert:
    that: __volume_info.exists
