---
- name: "diun | Set group id"
  ansible.builtin.set_fact:
    _nas_diun_gid: "{{ r740xd_diun_gid | default(r740xd_diun_uid) }}"

- name: "diun | Set group name"
  ansible.builtin.set_fact:
    _nas_diun_groupname: "{{ r740xd_diun_group | default(r740xd_diun_user) }}"

- name: "diun | Create Diun group"
  ansible.builtin.group:
    name: "{{ _nas_diun_groupname }}"
    gid: "{{ _nas_diun_gid }}"
    state: "present"

- name: "diun | Create Diun user"
  ansible.builtin.user:
    name: "{{ r740xd_diun_user }}"
    password: "*"
    shell: "/bin/false"
    system: false
    uid: "{{ r740xd_diun_uid }}"
    group: "{{ _nas_diun_groupname }}"
    password_lock: true

- name: "diun | Create Diun directories"
  ansible.builtin.file:
    path: "{{ __item }}"
    state: directory
    owner: "{{ r740xd_diun_user }}"
    group: "{{ _nas_diun_groupname }}"
    mode: "0770"
  with_items:
    - "{{ r740xd_diun_config_dir }}"
  loop_control:
    loop_var: __item

- name: "diun | Setup Diun Docker network"
  community.docker.docker_network:
    name: "{{ docker_networks.diun.name }}"
    driver: "bridge"
    enable_ipv6: "no"
    internal: "no"
    scope: "local"
    ipam_config:
      - subnet: "{{ docker_networks.diun.subnet }}"
        gateway: "{{ docker_networks.diun.gateway }}"

- name: "diun | Create Diun container"
  ansible.builtin.import_role:
    name: "diun"
  vars:
    r740xd_diun_user: "{{ r740xd_diun_user }}"
    r740xd_diun_uid: "{{ r740xd_diun_uid }}"
    r740xd_diun_group: "{{ _nas_diun_groupname }}"
    r740xd_diun_docker_network_name: "{{ docker_networks.diun.name }}"
    r740xd_diun_docker_timezone: "{{ r740xd_timezone }}"
    r740xd_diun_notify_mail_host: "{{ r740xd_diun_notify_mail_host }}"
    r740xd_diun_notify_mail_port: "{{ r740xd_diun_notify_mail_port }}"
    r740xd_diun_notify_mail_ssl: true
    r740xd_diun_notify_mail_insecure_skip_verify: false
    r740xd_diun_notify_mail_username: "{{ r740xd_diun_notify_mail_username }}"
    r740xd_diun_notify_mail_password: "{{ r740xd_diun_notify_mail_password }}"
    r740xd_diun_notify_mail_from: "{{ r740xd_diun_notify_mail_from }}"
    r740xd_diun_notify_mail_to: "{{ r740xd_diun_notify_mail_to }}"
    r740xd_diun_regopts_dockerio_user: "{{ r740xd_diun_regopts_dockerio_user }}"
    r740xd_diun_regopts_dockerio_passwd: "{{ r740xd_diun_regopts_dockerio_passwd }}"
