- name: "R740xd | EMQX | Setup Docker network"
  community.docker.docker_network:
    name: "{{ docker_networks.emqx.name }}"
    driver: "bridge"
    enable_ipv6: "no"
    internal: "no"
    scope: "local"
    ipam_config:
      - subnet: "{{ docker_networks.emqx.subnet }}"
        gateway: "{{ docker_networks.emqx.gateway }}"
  tags: ["setup", "network"]

- name: "R740xd | EMQX | Setup EMQX container"
  ansible.builtin.import_role:
    name: "emqx"
  vars:
    emqx_docker_users:
      - username: "admin"
        password: "password"
        is_superuser: true
      - username: "zigbee2mqtt"
        password: "zigbee2mqtt"
    emqx_docker_acls:
      - permission: "allow"
        clients: "zigbee2mqtt"
        access: "all"
        topic: "zigbee2mqtt/#"
    emqx_docker_host_domain: "{{ r740xd_emqx_host_domain }}"
    emqx_docker_network_name: "{{ docker_networks.emqx.name }}"
    emqx_docker_name: "{{ r740xd_emqx_docker_name }}"
  tags: ["setup", "emqx"]