---
- name: "glances | Setup Docker network"
  community.docker.docker_network:
    name: "{{ nas_docker_networks.glances.name }}"
    driver: "bridge"
    enable_ipv6: "no"
    internal: "no"
    scope: "local"
    ipam_config:
      - subnet: "{{ nas_docker_networks.glances.subnet }}"
        gateway: "{{ nas_docker_networks.glances.gateway }}"

- name: "glances | Setup Docker container"
  ansible.builtin.import_role:
    name: "glances"
  vars:
    glances_docker_host_domain: "{{ nas_domain_name }}"
    glances_docker_network_name: "{{ nas_docker_networks.glances.name }}"
    glances_docker_config: "{{ nas_glances_config_data }}"
    glances_docker_extra_bind_mounts: "{{ nas_glances_extra_bind_mounts }}"
