---
- name: "hass | Set fqdn"
  ansible.builtin.set_fact:
    _nas_hass_fqdn: "{{ r740xd_hass_host_name }}.{{ r740xd_hass_host_domain }}"

- name: "hass | Set endpoint URL for Ecowitt"
  ansible.builtin.set_fact:
    _nas_hass_ecowitt_url: "http://{{ _nas_hass_fqdn }}:8123"

- name: "hass | Setup Docker network"
  community.docker.docker_network:
    name: "{{ docker_networks.hass.name }}"
    driver: "bridge"
    enable_ipv6: "no"
    internal: "no"
    scope: "local"
    ipam_config:
      - subnet: "{{ docker_networks.hass.subnet }}"
        gateway: "{{ docker_networks.hass.gateway }}"

- name: "hass | Setup Z-Wave JS UI container"
  ansible.builtin.import_role:
    name: "organicveggie.zwavejsui"
  vars:
    zwavejsui_docker_device: "{{ r740xd_hass_zwave_device }}"
    zwavejsui_docker_host_domain: "{{ r740xd_hass_host_domain }}"
    zwavejsui_docker_network: "{{ docker_networks.hass.name }}"
    zwavejsui_docker_timezone: "{{ r740xd_hass_timezone }}"
  when:
    - "r740xd_hass_zwave_device is defined"
    - "r740xd_hass_zwave_device not in (None, omit)"

- name: "hass | Setup OpenThread Border Router container"
  ansible.builtin.import_role:
    name: "hass-otbr"
  vars:
    hass_otbr_auto_update_firmware: "{{ r740xd_hass_otbr_auto_update_firmware }}"
    hass_otbr_device: "{{ r740xd_hass_matter_device }}"
    hass_otbr_device_baudrate: "{{ r740xd_hass_otbr_device_baudrate }}"
    hass_otbr_device_flow_control: "{{ r740xd_hass_otbr_device_flow_control }}"
    hass_otbr_enable_firewall: "{{ r740xd_hass_otbr_enable_firewall }}"
    hass_otbr_enable_nat64: "{{ r740xd_hass_otbr_enable_nat64 }}"
    hass_otbr_enable_thread_1_4: "{{ r740xd_hass_otbr_enable_thread_1_4 }}"
    hass_otbr_enable_webui: "{{ r740xd_hass_otbr_enable_webui }}"
    hass_otbr_host_backbone_if: "{{ r740xd_hass_otbr_iface }}"
    hass_otbr_log_level: "{{ r740xd_hass_otbr_log_level }}"
    hass_otbr_traefik_available_externally: true
    hass_otbr_traefik_host_domain: "{{ r740xd_hass_host_domain }}"
  when:
    - "r740xd_hass_matter_device is defined"
    - "r740xd_hass_matter_device not in (None, omit)"

- name: "hass | Setup Home Assistant container"
  ansible.builtin.import_role:
    name: "home-assistant"
  vars:
    #hass_docker_otbr_url: "host.docker.internal:"
    hass_docker_host_domain: "{{ r740xd_hass_host_domain }}"
    hass_docker_host_name: "{{ r740xd_hass_host_name }}"
    hass_docker_zigbee_device: "{{ r740xd_hass_zigbee_device }}"
    hass_docker_network_aliases:
      - "{{ _nas_hass_fqdn }}"
    hass_docker_network_name: "{{ docker_networks.hass.name }}"
    hass_home_latitude: "{{ r740xd_hass_latitude }}"
    hass_home_longitude: "{{ r740xd_hass_longitude }}"
    hass_home_timezone: "{{ r740xd_hass_timezone }}"
    hass_network_subnet: "{{ docker_networks.hass.subnet }}"
    hass_ecowitt_hass_auth_token: "{{ r740xd_hass_ecowitt_hass_auth_token | default(omit) }}"
    hass_ecowitt_hass_webhook_id: "{{ r740xd_hass_ecowitt_hass_webhook_id | default(omit) }}"
    hass_ecowitt_hass_url: "{{ _nas_hass_ecowitt_url }}"
