---
- name: "R740xd | mosquitto | Setup Docker network"
  community.docker.docker_network:
    name: "{{ docker_networks.mosquitto.name }}"
    driver: "bridge"
    enable_ipv6: "no"
    internal: "no"
    scope: "local"
    ipam_config:
      - subnet: "{{ docker_networks.mosquitto.subnet }}"
        gateway: "{{ docker_networks.mosquitto.gateway }}"
  tags: ["setup", "network"]

- name: "R740xd | mosquitto | Setup Mosquitto container"
  ansible.builtin.import_role:
    name: "mosquitto"
  vars:
    mosquitto_docker_name: "{{ r740xd_mosquitto_docker_name }}"
    mosquitto_docker_host_domain: "{{ r740xd_mosquitto_host_domain }}"
    mosquitto_docker_listen_port: "{{ r740xd_mosquitto_http_port }}"
    mosquitto_docker_ws_listen_port: "{{ r740xd_mosquitto_ws_port }}"
  tags: ["setup", "mosquitto"]
