---
- name: "node-red | Setup Node-RED"
  ansible.builtin.import_role:
    name: "nodered"
  vars:
    nodered_docker_network_name: "{{ docker_networks.node_red.name }}"
    nodered_docker_timezone: "{{ r740xd_nodered_timezone }}"
    nodered_docker_extra_networks:
      - name: "{{ docker_networks.hass.name }}"
      - name: "{{ docker_networks.ingressproxy.name }}"      
