---
- name: "Docker | Launch Portainer container"
  ansible.builtin.import_role:
    name: "portainer"
  vars:
    portainer_docker_home: "{{ r740xd_docker_home }}"
    portainer_extra_networks:
      - name: "{{ docker_networks.ingressproxy.name }}"
    portainer_host_domain: "{{ veggie_nas_domain_name }}"
    portainer_network_name: "{{ docker_networks.traefik.name }}"
    portainer_traefik_network: "{{ docker_networks.traefik.name }}"
