---
- name: "docker | Create Portainer Docker network"
  community.docker.docker_network:
    name: "{{ portainer_network_name }}"
    driver: "bridge"
    enable_ipv6: "no"
    internal: "no"
    scope: "local"
    ipam_config:
      - subnet: "{{ portainer_network_subnet }}"
        gateway: "{{ portainer_network_gateway }}"

- name: "docker | Launch Portainer container"
  ansible.builtin.import_role: "portainer"
  vars:
    portainer_docker_home: "{{ nas_docker_home }}"
    portainer_host_domain: "{{ veggie_nas_domain_name }}"
