---
- name: "R740xd | Create Prometheus Docker network"
  community.docker.docker_network:
    name: "{{ docker_networks.prometheus.name }}"
    driver: "bridge"
    enable_ipv6: "no"
    internal: "no"
    scope: "local"
    ipam_config:
      - subnet: "{{ docker_networks.prometheus.subnet }}"
        gateway: "{{ docker_networks.prometheus.gateway }}"

- name: "R740xd | Launch Prometheus container"
  ansible.builtin.import_role:
    name: "prometheus_docker"
  vars:
    prometheus_docker_available_externally: true
    prometheus_docker_cpus: "2"
    prometheus_docker_extra_hosts:
      host.docker.internal: "host-gateway"
    prometheus_docker_extra_networks:
      - name: "{{ docker_networks.saurron.name }}"
    prometheus_docker_host_domain: "{{ r740xd_prometheus_host_domain }}"
    prometheus_docker_memory: "1GB"
    prometheus_docker_mount_docker_socket: true
    prometheus_docker_network_name: "{{ docker_networks.prometheus.name }}"
    prometheus_docker_config: 
      global:
        scrape_interval: "15s"
        scrape_failure_log_file: "/prometheus/scrape-failures.log"
      scrape_configs:
        # Make Prometheus scrape itself for metrics.
        - job_name: "prometheus"
          static_configs:
            - targets:
              - "localhost:9090"

        # Scrape Docker daemon metrics using the Docker support for Prometheus. See
        # https://docs.docker.com/engine/daemon/prometheus/.
        - job_name: docker
          static_configs:
            - targets:
              - "host.docker.internal:9323"
          # Relabel Docker metrics to have a `docker_` prefix to avoid conflicts with other metrics.
          metric_relabel_configs:
          - source_labels: [__name__]
            regex: '(.*)'
            target_label: __name__
            replacement: 'docker_${1}'
        
        # Scrape node-exporter metrics from the node exporter container running on the host.
        - job_name: host-node-exporter
          static_configs:
            - targets:
              - "host.docker.internal:9100"
        
        # Create a job for scraping metrics from other Docker containers using Docker service
        # discovery. This requires mounting the Docker socket into the container.
        - job_name: "docker-containers"
          docker_sd_configs:
            - host: "unix:///var/run/docker.sock"
          relabel_configs:
            # Only keep containers that have a `prometheus-job` label.
            - source_labels:
              - "__meta_docker_container_label_prometheus_job"
              regex: ".+"
              action: "keep"
            # Use the task labels that are prefixed by `prometheus-`.
            - regex: "__meta_docker_container_label_prometheus_(.+)"
              action: "labelmap"
              replacement: "$1"
        
        - job_name: "saurron"
          metrics_path: "/v1/metrics"
          scrape_interval: "1m"
          static_configs:
            - targets:
              - "{{ r740xd_saurron_docker_name }}:{{ r740xd_saurron_http_api_port }}"

- name: "R740xd | Install Prometheus node exporter"
  ansible.builtin.import_role:
    name: "node_exporter_docker"
