---
- name: "R740xd | seerr | Setup Docker network"
  community.docker.docker_network:
    name: "{{ docker_networks.seerr.name }}"
    driver: "bridge"
    enable_ipv6: "no"
    internal: "no"
    scope: "local"
    ipam_config:
      - subnet: "{{ docker_networks.seerr.subnet }}"
        gateway: "{{ docker_networks.seerr.gateway }}"
  tags: ["setup", "network"]

- name: "R740xd | seerr | Setup Seerr"
  ansible.builtin.import_role:
    name: "seerr"
  vars:
    seerr_docker_extra_networks:
      - name: "{{ docker_networks.servarr.name }}"
      - name: "{{ docker_networks.tautulli.name }}"
    seerr_docker_host_domain: "{{ nas_seerr_host_domain }}"
    seerr_docker_network: "{{ docker_networks.seerr.name }}"
    seerr_docker_timezone: "{{ nas_timezone }}"
  tags: ["seerr"]
