---
- name: "{{ r740xd_ansible_role_label }} | servarr | cross-seed | Build torznab urls"
  ansible.builtin.set_fact:
    _r740xd_cross_seed_torznab_urls: >
      {{ _r740xd_cross_seed_torznab_urls | default([]) + ["http://prowlarr:9696/" + __item + "/api?apikey=" + r740xd_cross_seed_prowlarr_api_key] }}
  loop: "{{ r740xd_cross_seed_prowlarr_indexer_ids }}"
  loop_control:
    loop_var: __item

- name: "{{ r740xd_ansible_role_label }} | servarr | cross-seed | Setup"
  ansible.builtin.import_role:
    name: "cross-seed"
  vars:
    cross_seed_action: "inject"
    cross_seed_api_key: "{{ r740xd_cross_seed_api_key }}"
    cross_seed_duplicate_categories: true
    cross_seed_match_mode: "{{ r740xd_cross_seed_match_mode }}"
    cross_seed_network_name: "{{ docker_networks.servarr.name }}"
    cross_seed_qbittorrrent_url: "{{ r740xd_cross_seed_qbittorrent_url }}"
    cross_seed_radarr_urls: 
      - "http://{{ r740xd_radarr1080_container_name }}:7878/?apikey={{ r740xd_cross_seed_radarr1080_apikey }}"
      - "http://{{ r740xd_radarr4k_container_name }}:7878/?apikey={{ r740xd_cross_seed_radarr4k_apikey }}"
    cross_seed_search_delay: "60"
    cross_seed_season_from_episode: null
    cross_seed_sonarr_urls:
      - "http://{{ r740xd_sonarr1080_container_name }}:8989/?apikey={{ r740xd_cross_seed_sonarr1080_apikey }}"
      - "http://{{ r740xd_sonarr4k_container_name }}:8989/?apikey={{ r740xd_cross_seed_sonarr4k_apikey }}"
    cross_seed_torznab_urls: "{{ _r740xd_cross_seed_torznab_urls }}"
