---
- name: "tautulli | Setup Tautulli container"
  ansible.builtin.import_role:
    name: "tautulli_docker"
  vars:
    tautulli_docker_available_externally: true
    tautulli_docker_extra_networks:
      - name: "{{ docker_networks.ingressproxy.name }}"
    tautulli_docker_gid: "{{ user_ids.tautulli.gid }}"
    tautulli_docker_host_domain: "{{ r740xd_tautulli_host_domain }}"
    tautulli_docker_host_name: "{{ r740xd_tautulli_hostname }}"
    tautulli_docker_name: "{{ r740xd_tautulli_container_name }}"
    tautulli_docker_network_name: "{{ docker_networks.plex.name }}"
    tautulli_docker_timezone: "{{ r740xd_timezone }}"
    tautulli_docker_uid: "{{ user_ids.tautulli.uid }}"
    tautulli_docker_webui_port: "{{ r740xd_tautulli_webui_port }}"
