---
- name: "time-machine | Create TimeMachine group"
  ansible.builtin.group:
    name: "{{ r740xd_time_machine_groupname }}"
    gid: "{{ r740xd_time_machine_gid | default(r740xd_time_machine_uid) }}"
    state: "present"

- name: "time-machine | Create TimeMachine user"
  ansible.builtin.user:
    name: "{{ r740xd_time_machine_username }}"
    password: "*"
    shell: "/bin/false"
    system: false
    uid: "{{ r740xd_time_machine_uid }}"
    group: "{{ r740xd_time_machine_groupname }}"
    password_lock: true

- name: "time-machine | Create ZFS dataset"
  community.general.zfs:
    name: "{{ r740xd_time_machine_zfs_dataset }}"
    state: present
  when: "r740xd_time_machine_zfs_dataset"

- name: "time-machine | Create data folder"
  ansible.builtin.file:
    path: "{{ r740xd_time_machine_data_directory }}"
    mode: "770"
    recurse: true
    state: "directory"
    owner: "{{ r740xd_time_machine_username }}"
    group: "{{ r740xd_time_machine_groupname }}"

- name: "time-machine | Setup TimeMachine container"
  ansible.builtin.import_role:
    name: "time_machine_docker"
  vars:
    time_machine_docker_name: "{{ r740xd_time_machine_docker_name }}"
    time_machine_docker_user: "{{ r740xd_time_machine_username }}"
    time_machine_docker_group: "{{ r740xd_time_machine_groupname }}"
    time_machine_docker_uid: "{{ r740xd_time_machine_uid }}"
    time_machine_docker_gid: "{{ r740xd_time_machine_gid }}"
    time_machine_docker_data_directory: "{{ r740xd_time_machine_data_directory }}"
    time_machine_docker_password: "{{ r740xd_time_machine_password }}"
    time_machine_docker_network: "{{ r740xd_time_machine_network_name }}"
    time_machine_docker_advertised_hostname: "{{ r740xd_time_machine_hostname }}"
    time_machine_docker_network_ipv4_addr: "{{ r740xd_time_machine_network_ipv4 }}"
    time_machine_docker_workgroup: "{{ r740xd_time_machine_workgroup }}"
