---
- name: "traefik3 | Define fqdn"
  ansible.builtin.set_fact:
    _nas_traefik3_fqdn: "traefik3.{{ veggie_nas_domain_name }}"

- name: "traefik3 | Setup Docker network"
  community.docker.docker_network:
    name: "{{ nas_docker_networks.traefik3.name }}"
    driver: "bridge"
    enable_ipv6: "no"
    internal: "no"
    scope: "local"
    ipam_config:
      - subnet: "{{ nas_docker_networks.traefik3.subnet }}"
        gateway: "{{ nas_docker_networks.traefik3.gateway }}"

###
### Configure additional networks, ports, and entrypoints
###
- name: "traefik3 | Process extra networks"
  ansible.builtin.include_tasks:
    file: "traefik_network.yml"
  loop:
    - "{{ nas_docker_networks.traefik3.name }}"
    - "{{ nas_docker_networks.calibre_web.name }}"
    - "{{ nas_docker_networks.glances.name }}"
    - "{{ nas_docker_networks.hass.name }}"
    - "{{ nas_docker_networks.influxdb.name }}"
    - "{{ nas_docker_networks.navidrome.name }}"
    - "{{ nas_docker_networks.node_red.name }}"
    - "{{ nas_docker_networks.overseerr.name }}"
    - "{{ nas_docker_networks.portainer.name }}"
    - "{{ nas_docker_networks.tautulli.name }}"
  vars:
    "_traefik_role_name": "traefik3"

- name: "traefik3 | Process Servarr network"
  when: "nas_docker_networks.servarr.name | default('') | trim | length > 0"
  block:
    - name: "traefik3 | Check if Servarr network exists"
      community.docker.docker_network_info:
        name: "{{ nas_docker_networks.servarr.name }}"
      register: "_nas_traefik_servarr_network_info"

    - name: "traefik3 | Configure for Servarr tools"
      when: "_nas_traefik_servarr_network_info.exists"
      block:
        - name: "traefik3 | Enable Servarr extra network"
          ansible.builtin.set_fact:
            _nas_traefik3_extra_networks: >
              {{ _nas_traefik3_extra_networks | default([]) + [_nas_traefik3_network_servarr] }}
          vars:
            _nas_traefik3_network_servarr:
              name: "{{ nas_docker_networks.servarr.name }}"

        - name: "traefik3 | Enable SyncThings (Servarr) ports"
          ansible.builtin.set_fact:
            _nas_traefik3_extra_ports: >
              {{ _nas_traefik3_extra_ports | default([]) + nas_traefik_syncthings_ports }}
        
        - name: "traefik3 | Enable SyncThings (Servarr) entrypoints"
          ansible.builtin.set_fact:
            _nas_traefik3_entrypoints: >
              {{ _nas_traefik3_entrypoints | default({}) | combine(nas_traefik_syncthings_entrypoints) }}

- name: "traefik3 | Process UniFi Controller network"
  when: "nas_docker_networks.unific.name | default('') | trim | length > 0"
  block:
    - name: "traefik3 | Check if UniFi Controller network exists"
      community.docker.docker_network_info:
        name: "{{ nas_docker_networks.unific.name }}"
      register: "_nas_traefik_unific_network_info"

    - name: "traefik3 | Configure Traefik for UniFi Controller"
      when: "_nas_traefik_unific_network_info.exists"
      block:
        - name: "traefik3 | Enable UniFi extra network"
          ansible.builtin.set_fact:
            _nas_traefik3_extra_networks: >
              {{ _nas_traefik3_extra_networks | default([]) + [_nas_traefik3_network_unific] }}
          vars:
            _nas_traefik3_network_unific:
              name: "{{ nas_docker_networks.unific.name }}"

        - name: "traefik3 | Enable UniFi Controlller ports"
          ansible.builtin.set_fact:
            _nas_traefik3_extra_ports: >
              {{ _nas_traefik3_extra_ports | default([]) + nas_traefik_unific_ports }}
        
        - name: "traefik3 | Enable UniFi Controller entrypoints"
          ansible.builtin.set_fact:
            _nas_traefik3_entrypoints: >
              {{ _nas_traefik3_entrypoints | default({}) | combine(nas_traefik_unific_entrypoints) }}

- name: "traefik3 | Define all ports"
  ansible.builtin.set_fact:
    _nas_traefik3_all_ports: >
      {{ _nas_traefik3_extra_ports | default([]) | sort }}

- ansible.builtin.debug:
    msg:
      - "Entrypoints: {{ _nas_traefik3_entrypoints | default({}) }}"
      - "Extra networks: {{ _nas_traefik3_extra_networks | default([]) }}"
      - "Entrypoint ports: {{ _nas_traefik3_all_ports | default([]) }}"

- name: "traefik3 | Setup Traefik"
  ansible.builtin.import_role:
    name: "traefik3"
  vars:
    traefik3_conf_access_log_enabled: false
    traefik3_conf_cert_resolvers:
      letsencrypt:
        acme:
          caServer: "{{ letsencrypt_ca_server_staging }}"
          email: "{{ nas_traefik_letsencrypt_email }}"
          dnsChallenge:
            delayBeforeCheck: "10"
            provider: "route53"
            propagation:
              delayBeforeChecks: "10s"
              disableChecks: true
            resolvers:
              - "8.8.8.8:53" # Use external DNS to verify TXT record changes
    traefik3_conf_entrypoints: "{{ _nas_traefik3_entrypoints }}"
    traefik3_conf_logging_level: "DEBUG"
    traefik3_conf_providers: "{{ nas_traefik3_conf_providers }}"
    traefik3_cpus: "2"
    traefik3_dashboard_api_insecure: "false"
    traefik3_dashboard_fqdn: "{{ _nas_traefik3_fqdn }}"
    traefik3_dashboard_middleware_labels: "{{ nas_traefik3_dashboard_middleware_labels }}"
    traefik3_dashboard_middleware_names: "{{ nas_traefik3_dashboard_middleware_names }}"
    traefik3_extra_env_vars:
      AWS_ACCESS_KEY_ID: "{{ nas_aws_route53_access_key_id }}"
      AWS_SECRET_ACCESS_KEY: "{{ nas_aws_route53_secret_access_key }}"
      AWS_REGION: "{{ nas_aws_route53_region }}"
      AWS_POLLING_INTERVAL: "15"
      AWS_PROPAGATION_TIMEOUT: "300"
      AWS_TTL: "60"
    traefik3_extra_networks: "{{ _nas_traefik_extra_networks }}"
    traefik3_redirect_http: "{{ nas_traefik3_redirect_http }}"
    traefik3_memory: "1G"
    traefik3_timezone: "{{ nas_timezone }}"
