---
- name: Create PostgreSQL Docker Container
  community.docker.docker_container:
    name: "postgres"
    image: "{{ postgresql_docker_image }}"
    volumes:
      - "{{ postgresql_docker_conf_dir }}:/etc/postgresql"
      - "{{ postgresql_docker_data_dir }}:/var/lib/postgresql/data"
      - "/etc/passwd:/etc/passwd:ro"
    shm_size: "{{ postgresql_docker_shm_size | default(omit) }}"
    env:
      POSTGRES_PASSWORD: "{{ postgresql_docker_admin_password }}"
      POSTGRES_USER: "{{ postgresql_docker_admin_user }}"
      # POSTGRES_INITDB_WALDIR: "{{ postgresql_docker_wal_dir | default(omit) }}"
      # PGDATA: "{{ postgresql_docker_pgdata | default(omit) }}"
    network_mode: "{{ postgresql_docker_network_mode | default(omit) }}"
    networks: "{{ postgresql_docker_networks | default(omit) }}"
    restart_policy: unless-stopped
    memory: "{{ postgresql_docker_memory }}"
    cpus: "{{ postgresql_docker_cpu }}"
    container_default_behavior: no_defaults
    auto_remove: no
    detach: yes
    init: yes
    interactive: no
    paused: no
    privileged: no
    read_only: no
    tty: no
    labels:
      traefik.enable: "{{ postgresql_docker_available_externally }}"
      traefik.postgres.routers.postgres.rule: "*"
      traefik.postgres.services.postgres.loadbalancer.server.port: "5432"
