---
- name: Plex Docker Volumes
  community.docker.docker_volume:
    name: "{{ item }}"
  with_items:
    - "{{ plex_docker_volume_name_home }}"  
    - "{{ plex_docker_volume_name_transcode }}"

- name: Create Plex Docker Container
  community.docker.docker_container:
    name: plex
    image: plexinc/pms-docker
    pull: true
    network_mode: host
    mounts:
      - source: "{{ plex_docker_volume_name_home }}"
        target: "/config"
        type: "volume"
      - source: "{{ plex_docker_volume_name_transcode }}"
        target: "/transcode"
        type: "volume"
      - source: "{{ plex_docker_media_path }}/music"
        target: "/media/music"
        type: "bind"
      - source: "{{ plex_docker_media_path }}/videos/anime"
        target: "/media/anime"
        type: "bind"
      - source: "{{ plex_docker_media_path }}/videos/exercise"
        target: "/media/exercise"
        type: "bind"
      - source: "{{ plex_docker_media_path }}/videos/movies"
        target: "/media/movies"
        type: "bind"
      - source: "{{ plex_docker_media_path }}/videos/tv"
        target: "/media/tv"
        type: "bind"
    env:
      TZ: "{{ plex_docker_timezone }}"
      PLEX_CLAIM: "{{ plex_docker_claim }}"
      PLEX_UID: "{{ plex_docker_uid }}"
      PLEX_GID: "{{ plex_docker_gid }}"
    restart_policy: unless-stopped
    cpus: "{{ plex_docker_cpus }}"
    memory: "{{ plex_docker_memory }}"
    container_default_behavior: no_defaults
    auto_remove: no
    detach: yes
    init: yes
    interactive: no
    paused: no
    privileged: no
    read_only: no
    labels:
      traefik.enable: "false"
