---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/docker_networks/requirements.yml
    role-file: molecule/docker_networks/requirements.yml

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
