template:
  - sensor:
    - name: "SolarEdge Yearly Energy Template"
      state: "{{ (states('sensor.solaredge_energy_this_year') | float / 1000) | round(2) }}"
      unique_id: "solaredge_energy_this_year_template"
      unit_of_measurement: 'kW'
      icon: mdi:solar-power
      device_class: 'power'
      state_class: 'measurement'
      # attributes:
        # last_reset: '{{ now().replace(hour=0).replace(minute=10).replace(second=0).replace(microsecond=0).isoformat() }}'
        # last_reset: '1970-01-01T00:00:00+00:00'
