views:
  - panel: true
    cards:
      - title: Weather
        type: custom:layout-card
        layout: horizontal
        column_width: [33%, 34%, 33%]
        column_num: 3
        cards:
          - type: custom:mini-graph-card
            name: Outside
            entities:
              - entity: sensor.outdoor_temperature
                name: Temp
                show_state: true
              - entity: sensor.humidity
                name: Humidity
                show_state: true
                y_axis: secondary
            show:
              labels: true
              labels_secondary: true
          - type: custom:mini-graph-card
            name: Garage
            entities:
              - entity: sensor.temperature_1
                name: Temp
                show_state: true
              - entity: sensor.humidity_1
                name: Humidity
                show_state: true
                y_axis: secondary
            show:
              labels: true
              labels_secondary: true
          - type: custom:mini-graph-card
            name: Wine
            entities:
              - entity: sensor.temperature_2
                name: Temp
                show_state: true
              - entity: sensor.humidity_2
                name: Humidity
                show_state: true
                y_axis: secondary
            show:
              labels: true
              labels_secondary: true
          - type: custom:layout-break
          - type: custom:mini-graph-card
            name: Atrium
            entities:
              - entity: sensor.indoor_temperature
                name: Temp
                show_state: true
              - entity: sensor.indoor_humidity
                name: Humidity
                show_state: true
                y_axis: secondary
            show:
              labels: true
              labels_secondary: true
          - type: custom:mini-graph-card
            name: Kitchen
            entities:
              - entity: sensor.temperature_3
                name: Temp
                show_state: true
              - entity: sensor.humidity_3
                name: Humidity
                show_state: true
                y_axis: secondary
            show:
              labels: true
              labels_secondary: true
          - type: custom:mini-graph-card
            name: Master Bedroom
            entities:
              - entity: sensor.temperature_4
                name: Temp
                show_state: true
              - entity: sensor.humidity_4
                name: Humidity
                show_state: true
                y_axis: secondary
            show:
              labels: true
              labels_secondary: true
          - type: custom:layout-break
          - type: vertical-stack
            cards:
              - type: markdown
                content: >
                  Rainfall
              - type: horizontal-stack
                cards:
                  - type: button
                    icon: mdi:water
                  - type: markdown
                    content: >
                      Rate / hr
                  - type: markdown
                    content: >
                      {{ states('sensor.hourly_rain_rate') }} in
              - type: horizontal-stack
                cards:
                  - type: button
                    icon: mdi:water
                  - type: markdown
                    content: >
                      Daily
                  - type: markdown
                    content: >
                      {{ states('sensor.daily_rain_rate') }} in
              - type: horizontal-stack
                cards:
                  - type: button
                    icon: mdi:water
                  - type: markdown
                    content: >
                      Weekly
                  - type: markdown
                    content: >
                      {{ states('sensor.weekly_rain_rate') }} in
          - type: vertical-stack
            cards:
              - type: markdown
                content: >
                  Wind
              - type: horizontal-stack
                cards:
                  - type: button
                    icon: mdi:weather-windy
                  - type: markdown
                    content: >
                      Direction
                  - type: markdown
                    content: >
                      {{ states('sensor.weather_wind_direction') }}
              - type: horizontal-stack
                cards:
                  - type: button
                    icon: mdi:weather-windy
                  - type: markdown
                    content: >
                      Speed
                  - type: markdown
                    content: >
                      {{ states('sensor.wind_speed') }} mph
              - type: horizontal-stack
                cards:
                  - type: button
                    icon: mdi:weather-windy
                  - type: markdown
                    content: >
                      Gust
                  - type: markdown
                    content: >
                      {{ states('sensor.wind_gust') }} mph
          - type: vertical-stack
            cards:
              - type: markdown
                content: >
                  Soil
              - type: horizontal-stack
                cards:
                  - type: button
                    icon: mdi:water-percent
                  - type: markdown
                    content: >
                      Lime tree
                  - type: markdown
                    content: >
                      {{ states('sensor.soil_moisture_1') }} %
              - type: horizontal-stack
                cards:
                  - type: button
                    icon: mdi:water-percent
                  - type: markdown
                    content: >
                      Mandarin tree
                  - type: markdown
                    content: >
                      {{ states('sensor.soil_moisture_2') }} %
