---
# defaults file
# Setup vars
traefik2_dir: "/etc/traefik"
traefik2_hostname: "{{ inventory_hostname }}"
traefik2_network: "traefik2_proxy"

# quicksetup vars
traefik2_qs_send_anonymous_usage: "{{ traefik2_sendanonymoususage | default(false) }}"
traefik2_qs_https: "{{ traefik2_https | default(false) }}"
traefik2_qs_https_redirect: "{{ traefik2_https_redirect | default(false) }}"
traefik2_qs_https_le: false
traefik2_qs_log_level: "{{ traefik2_log_level | default('ERROR') }}"

# service vars
traefik2_container_name: "traefik"
traefik2_network_name: "{{ traefik2_network }}"
traefik2_network_ipam_temp: "{{ traefik2_network_ipam | default({}) }}"
traefik2_network_ipam_subnet: "{{ traefik2_network_ipam_temp.subnet | default('172.16.1.0/24') }}"
traefik2_network_ipam_gateway: "{{ traefik2_network_ipam_temp.gateway | default('172.16.1.1') }}"
traefik2_network_ipam_iprange: "{{ traefik2_network_ipam_temp.iprange | default('172.16.1.0/24') }}"
traefik2_image: "traefik"
traefik2_add_volumes: []
traefik2_ports:
  - "80:80"
  - "443:443"
traefik2_labels: {}
traefik2_container_environment: []

# traefik2_confkey_global: {}
# traefik2_confkey_serversTransport: {}
# traefik2_confkey_entryPoints: {}
# traefik2_confkey_providers: {}
# traefik2_confkey_api: {}
# traefik2_confkey_metrics: {}
# traefik2_confkey_ping: {}
# traefik2_confkey_log: {}
# traefik2_confkey_accessLog: {}
# traefik2_confkey_tracing: {}
# traefik2_confkey_hostResolver: {}
# traefik2_confkey_certificatesResolvers: {}
