---
- name: "{{ mosquitto_docker_role_label }} | Add client {{ __item.username }}"
  community.docker.docker_container_exec:
    container: "{{ mosquitto_docker_name }}"
    command: >
      {{ mosquitto_docker_shell }} -c "echo -e '{{ __item.password }}\n{{ __item.password }}' | 
      {{ mosquitto_docker_ctrl_bin }} -u admin -P '{{ mosquitto_docker_dynamic_security_admin_passwd }}' 
      dynsec createClient {{ __item.username }}"
  register: __mosquitto_docker_user
  failed_when:
    - __mosquitto_docker_user.rc != 0
    - "'already exists' not in __mosquitto_docker_user.stderr"
    - "'AlreadyExists' not in __mosquitto_docker_user.stdout"

- name: "{{ mosquitto_docker_role_label }} | Add roles to client {{ __item.username }}"
  community.docker.docker_container_exec:
    container: "{{ mosquitto_docker_name }}"
    command: >
      {{ mosquitto_docker_shell }} -c "{{ mosquitto_docker_ctrl_bin }}
      -u admin -P '{{ mosquitto_docker_dynamic_security_admin_passwd }}' 
      dynsec addClientRole 
      {{ __item.username }} 
      {{ __role }}"
  loop: "{{ __item.roles | default([]) }}"
  loop_control:
    loop_var: __role
  register: __mosquitto_docker_user_role
  failed_when:
    - __mosquitto_docker_user_role.rc != 0
    - "'already exists' not in __mosquitto_docker_user_role.stderr"
    - "'AlreadyExists' not in __mosquitto_docker_user_role.stdout"

