---
- name: "{{ mosquitto_docker_role_label }} | Get info on volume {{ __volume_name }}"
  community.docker.docker_volume_info:
    name: "{{ __volume_name }}"
  register: "__mosquitto_docker_volume_info"

- name: "{{ mosquitto_docker_role_label }} | Set ownership for {{ __volume_name }}"
  ansible.builtin.file:
    path: "{{ __mosquitto_docker_volume_info.volume.Mountpoint }}"
    owner: "{{ mosquitto_docker_user }}"
    group: "{{ mosquitto_docker_group }}"
    recurse: false
    state: "directory"
    mode: "0770"
