---
traefik2_int_conf_global:
    sendAnonymousUsage: "{{ traefik2_qs_send_anonymous_usage }}"

traefik2_int_conf_entrypoints:
    http:
        address: ":80"

traefik2_int_conf_entrypoints_https:
    https:
        address: ":443"

traefik2_int_conf_entrypoints_https_redirect:
    http:
        http:
            redirections:
                entryPoint:
                    to: "https"
                    scheme: "https"

traefik2_int_conf_providers:
    docker: {}

traefik2_int_conf_log:
    level: "{{ traefik2_qs_log_level }}"

traefik2_int_conf_certificatesresolvers_le:
    letsencrypt:
        acme:
            email: "{{ traefik2_qs_https_le_mail }}"
            tlsChallenge: {}
            storage: "/letsencrypt/acme.json"

traefik2_conf_global: "{{ traefik2_int_conf_global
    | combine(traefik2_confkey_global | default({})) }}"
traefik2_conf_entrypoints: "{{ traefik2_int_conf_entrypoints
    | combine(traefik2_confkey_entryPoints
    | default({})) }}"
traefik2_conf_providers: "{{ traefik2_int_conf_providers
    | combine(traefik2_confkey_providers | default({})) }}"
traefik2_conf_log: "{{ traefik2_int_conf_log | combine(traefik2_confkey_log | default({})) }}"
# traefik2_conf_certificatesresolvers: "{{
#   traefik2_int_conf_certificatesresolvers
#   | combine(traefik2_confkey_certificatesresolvers
#     | default({})
#   )
# }}"

traefik2_volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "{{ traefik2_dir }}/traefik.yml:/etc/traefik/traefik.yml"
    - "{{ traefik2_dir }}/letsencrypt/:/letsencrypt/:rw"
    - "traefik-data:/etc/traefik"

#####
# Ansible
#####

traefik2_role_label: "traefik2"
