---
- name: "Create sabnzbd Docker config volume"
  community.docker.docker_volume:
    name: "{{ sabnzbd_docker_volume_config_name }}"

- name: "Set Docker mount list for volume mounts"
  ansible.builtin.set_fact:
    _sabnzbd_docker_mount_list:
      - source: "{{ sabnzbd_docker_volume_config_name }}"
        target: "/config"
        type: "volume"
      - source: "{{ sabnzbd_docker_data_source_path }}"
        target: "/data"
        type: "bind"

- name: "Build container FQDN"
  ansible.builtin.set_fact:
    _sabnzbd_docker_fqdn: "{{ sabnzbd_docker_host_name }}.{{ sabnzbd_docker_host_domain }}"

- name: "Create placeholder array for default network"
  ansible.builtin.set_fact:
    _sabnzbd_docker_default_networks:
      - name: "{{ sabnzbd_docker_network }}"
        aliases: "{{ sabnzbd_docker_network_aliases | default(omit) }}"

- name: "Define all Docker networks for this container"
  ansible.builtin.set_fact:
    _sabnzbd_docker_all_networks: >
      {{ _sabnzbd_docker_default_networks + sabnzbd_docker_extra_networks }}

- name: "Define Docker labels with Traefik disabled"
  ansible.builtin.set_fact:
    _sabnzbd_docker_labels: "{{ _sabnzbd_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  with_items:
    - key: "traefik.enable"
      value: "{{ sabnzbd_available_externally }}"
  when: "not sabnzbd_available_externally"

- name: "Define Docker labels with Traefik enabled"
  ansible.builtin.set_fact:
    _sabnzbd_docker_labels: "{{ _sabnzbd_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  with_items:
    - key: "traefik.enable"
      value: "{{ sabnzbd_available_externally }}"
    - key: "traefik.docker.network"
      value: "{{ servarr_docker_network }}"
    - key: "traefik.http.routers.sabnzbd.rule"
      value: "Host(`{{ _sabnzbd_docker_fqdn }}`)"
    - key: "traefik.http.routers.sabnzbd.entrypoints"
      value: "http,https"
    - key: "traefik.http.routers.sabnzbd.tls.certresolver"
      value: "letsencrypt"
    - key: "traefik.http.routers.sabnzbd.tls.domains[0].main"
      value: "*.{{ sabnzbd_docker_host_domain }}"
    - key: "traefik.http.services.sabnzbd.loadbalancer.server.port"
      value: "{{ sabnzbd_docker_web_port }}"
  when: "sabnzbd_available_externally"

- name: "Define user-supplied extra Docker labels"
  ansible.builtin.set_fact:
    _sabnzbd_docker_labels: "{{ _sabnzbd_docker_labels | default({}) |
      combine({item.key: item.value}) }}"
  loop: "{{ sabnzbd_docker_extra_labels | dict2items }}"

- name: "sabnzbd Docker Container"
  community.docker.docker_container:
    name: "{{ sabnzbd_docker_name }}"
    image: "{{ sabnzbd_docker_image }}:{{ sabnzbd_docker_image_version }}"
    pull: true
    env:
      "PUID": "{{ sabnzbd_docker_uid }}"
      "PGID": "{{ sabnzbd_docker_gid }}"
      "TZ": "{{ sabnzbd_docker_timezone }}"
    mounts: "{{ _sabnzbd_docker_mount_list }}"
    network_mode: "{{ sabnzbd_docker_network }}"
    networks: "{{ _sabnzbd_docker_all_networks }}"
    restart_policy: unless-stopped
    memory: "{{ sabnzbd_docker_memory }}"
    cpus: "{{ sabnzbd_docker_cpus }}"
    container_default_behavior: no_defaults
    auto_remove: no
    detach: yes
    init: no
    interactive: no
    paused: no
    privileged: no
    read_only: no
    tty: no
    labels: "{{ _sabnzbd_docker_labels }}"
