---
- name: InfluxDB Docker Container
  community.docker.docker_container:
    name: influxdb
    image: "influxdb:{{influxdb_docker_image_version}}"
    pull: true
    volumes:
      - "{{ influxdb_docker_conf_dir }}:/etc/influxdb2"
      - "{{ influxdb_docker_data_dir }}:/var/lib/influxdb2"
    user: "{{ influxdb_docker_uid }}"
    network_mode: "{{ influxdb_network_name }}"
    restart_policy: unless-stopped
    memory: 1g
    container_default_behavior: "no_defaults"
    auto_remove: "no"
    detach: "yes"
    cleanup: "yes"
    init: "yes"
    interactive: "no"
    paused: "no"
    privileged: "no"
    read_only: "no"
    tty: "no"
    env:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "{{ influxdb_docker_superuser_name }}"
      DOCKER_INFLUXDB_INIT_PASSWORD: "{{ influxdb_docker_superuser_password }}"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "{{ influxdb_docker_superuser_token }}"
      DOCKER_INFLUXDB_INIT_ORG: "{{ influxdb_docker_superuser_org }}"
      DOCKER_INFLUXDB_INIT_BUCKET: "{{ influxdb_docker_init_bucket }}"
      DOCKER_INFLUXDB_INIT_RETENTION: "{{ influxdb_docker_init_bucket_retention | default(omit) }}"
    labels:
      traefik.enable: "{{ influxdb_available_externally }}"
      traefik.http.routers.influxdb.rule: "Host(`{{ influxdb_docker_hostname }}.{{ influxdb_docker_host_domain }}`)"
      traefik.http.routers.influxdb.entrypoints: "http,https"
      traefik.http.routers.influxdb.tls.certresolver: "letsencrypt"
      traefik.http.routers.influxdb.tls.domains[0].main: "*.{{ influxdb_docker_host_domain }}"
      traefik.http.services.influxdb.loadbalancer.server.port: "{{ influxdb_docker_port }}"
  