---
- name: Install msmtp
  ansible.builtin.apt:
    name: "{{ __item }}"
    state: present
  loop:
    - "msmtp"
    - "msmtp-mta"
    - "mailutils"
    - "bsd-mailx"
  loop_control:
    loop_var: __item
