- name: Disable default virtualhosts
  ansible.builtin.command:
    cmd: a2dissite "{{ item }}"
    removes: /etc/apache2/sites-enabled/"{{ item }}".conf
  loop:
    - 000-default
    - default-ssl

- name: Create Grafana virtualhost config
  ansible.builtin.template:
    src: ../templates/virtualhost.conf.j2
    dest: /etc/apache2/sites-available/grafana.conf
  notify:
    - Restart Apache

- name: Enable Grafana virtualhost
  ansible.builtin.command:
    cmd: a2ensite grafana
    creates: /etc/apache2/sites-enabled/grafana.conf
  notify:
    - Restart Apache

- name: Check that our config is valid
  ansible.builtin.command: apache2ctl configtest
  register: result
  ignore_errors: True

####################
# Roll back
####################
- name: Roll back - Removing virtualhost
  ansible.builtin.command:
    cmd: a2dissite grafana
    removes: /etc/apache2/sites-enabled/grafana.conf
  when: result is failed

- name: Roll back - Re-enable default virtualhost
  ansible.builtin.command:
    cmd: a2dissite 000-default
    creates: /etc/apache2/sites-enabled/000-default.conf
  when: result is failed

- name: Roll back - Ending playbook
  fail:
    msg: "Configuration file is not valid. Please check that before re-running the playbook."
  when: result is failed
