- name: Install Apache packages
  ansible.builtin.apt:
    name: apache2

- name: Enable Apache modules
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  loop:
    - proxy
    - proxy_http
    - rewrite
    - ssl

- name: Disable mod_status
  community.general.apache2_module:
    state: absent
    name: status
