#####
# InfluxDB Configuration Options
#####

# HTTP port for InfluxDB.
influxdb_docker_web_port: "8086"

# Dictionary of extra environment variables, such as configuration options
# (https://docs.influxdata.com/influxdb/v2/reference/config-options/).
#
# Example:
#   influxdb_docker_extra_env_vars:
#     "INFLUXD_LOG_LEVEL": "debug"
#     "VAULT_ADDR": "https://vault.example.com:8200/"
#
influxdb_docker_extra_env_vars: {}

#####
# Container settings
#####

# Name of the Docker container.
influxdb_docker_name: "influxdb"

# Base name of the Docker image to use for the container.
influxdb_docker_image_name: "influxdb"

# Specific Docker image version to use for the container.
influxdb_docker_image_version: "2"

# Number of vCPUs to allocate to the container.
influxdb_docker_cpus: "1"

# Amount of memory to allocate to the container.
influxdb_docker_memory: "512M"

# Dictionary of extra key value pairs to set as labels on the Docker container.
influxdb_docker_extra_labels: {}

#####
# Docker networks
#####

# Name of the default Docker network for the container. The container will *always* attach to this
# network.
influxdb_docker_network: "influxdb"

# List of additional networks the container should attach to. Elements should be dictionaries like
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-networks.
influxdb_docker_extra_networks: []

# List of aliases for this container in the default network. These names can be used in the default
# network to reach this container.
influxdb_docker_network_aliases: []

# The container’s IPv4 address in the default network. Defaults to using DHCP.
influxdb_docker_network_ipv4: null

# The container’s IPv6 address in the default network. Defaults to using DHCP. Only applies if
# IPv6 is enabled in the default network.
influxdb_docker_network_ipv6: null

#####
# Docker volumes and folders
#####

# Name of the Docker volume to use to store config files. Will be created if
# it does not already exist.
influxdb_docker_config_volume_name: "influxdb-config"

# Name of the Docker volume to use to store data files. Will be created if it
# does not already exist.
influxdb_docker_data_volume_name: "influxdb-data"

#####
# Traefik
#####

influxdb_docker_available_externally: true
influxdb_docker_hostname: "influxdb"
influxdb_docker_host_domain: "example.com"
