###
### Common
###
real_hostname: "{{ vault_real_hostname }}"
real_hostname_short: "{{ vault_real_hostname_short }}"

###
### Restic
###
restic_client_user: "{{ restic_user_desktop }}"
restic_client_passwd: "{{ restic_passwd_desktop }}"
restic_server_name: "{{ veggie_desktop_restic_server }}"
restic_repo_password: "{{ veggie_desktop_restic_password }}"
restic_client_exclude_paths: "{{ vault_restic_client_exclude_paths }}"
restic_client_include_paths: "{{ vault_restic_client_include_paths }}"

###
### Telegraf
###
telegraf_influxdb_url: "{{ influxdb_url }}"
telegraf_influxdb_token: "{{ influxdb_telegraf_token }}"
telegraf_influxdb_org: "{{ influxdb_admin_org }}"
telegraf_plugin_zfs_pool_sizes: true
telegraf_plugins_extra:
  - name: "systemd_units"
    options:
      unittype: "service"
      pattern: "restic-*"
  - name: "systemd_units"
    options:
      unittype: "timer"
      pattern: "restic-*"
  - name: zfs
    options:
      poolMetrics: true

###
### Wally
###
wally_plugdev_users: "{{ vault_wally_plugdev_users }}"