---
- name: "{{ _traefik3_role_name | default('traefik3', true) }} | network"
  when: "__r720xd_traefik3_docker_network | default('', true) | trim | length > 0"
  block:
    - name: "{{ _traefik3_role_name | default('traefik3', true) }} | network | Check if {{ __r720xd_traefik3_docker_network }} network exists"
      community.docker.docker_network_info:
        name: "{{ __r720xd_traefik3_docker_network }}"
      register: "_network_info"

    - name: "{{ _traefik3_role_name | default('traefik3', true) }} | network | Enable {{ __r720xd_traefik3_docker_network }} extra network"
      ansible.builtin.set_fact:
        _r720xd_traefik3_extra_networks: >-
          {{ _r720xd_traefik3_extra_networks | default([]) + [{'name': __r720xd_traefik3_docker_network}] }}
      when: "_network_info.exists"
