---
- sensor:
  - name: "Day of the week"
    state: "{{ now().weekday() }}"
  - name: "Is Commute Day"
    state: "{{ now().weekday() in [2,3]}}"
  - name: "Is Weekend"
    state: "{{ now().weekday() in [5,6]}}"
  - name: "Is Weekday"
    state: "{{ now().weekday() in [0,1,2,3,4]}}"
