---
- sensor:
  - name: "Day of the week"
    state: "{{ now().weekday() }}"

- binary_sensor:
  - name: "Is Commute Day"
    state: "{{ bool(now().weekday() in [2,3]) }}"
  - name: "Is Weekend"
    state: "{{ bool(now().weekday() in [5,6]) }}"
  - name: "Is Weekday"
    state: "{{ bool(now().weekday() in [0,1,2,3,4]) }}"
