---
#####
# Container settings
#####

# Name of the Docker container.
sonarr_docker_name: "sonarr"

# Base name of the Docker image to use for the container.
sonarr_docker_image: "lscr.io/linuxserver/sonarr"

# Specific Docker image version to use for the container.
sonarr_docker_image_version: "latest"

# Group ID to use inside the container.
sonarr_docker_gid: "1000"

# User ID to use inside the container.
sonarr_docker_uid: "1000"

# Timezone to use inside the container.
sonarr_docker_timezone: "America/New_York"

sonarr_docker_data_source_path: "/data"
sonarr_docker_tv_source_path: "/data/media/tv"

sonarr_docker_volume_config_name: "sonarr-config"

# Number of vCPUs to allocate to the container.
sonarr_docker_cpus: "2"

# Amount of memory to allocate to the container.
sonarr_docker_memory: "2GB"

# TCP port number to expose to handle HTTP traffic for Sonarr desktop gui.
sonarr_docker_web_port: "8989"

# Dictionary of extra key value pairs to set as labels on the Docker container.
sonarr_docker_extra_labels: {}

# List of additional container mounts. Elements should be dictionaries like
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-mounts.
radarr_docker_extra_mounts: []

# Default Docker network.
sonarr_docker_network: "servarr"

# List of additional networks the container should attach to. Elements should be dictionaries like
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-networks.
sonarr_docker_extra_networks: []

# List of aliases for this container in the default network. These names can be used in the default
# network to reach this container.
sonarr_docker_network_aliases: []

#####
# Traefik
#####

# Enable use of Traefik as a proxy.
sonarr_docker_available_externally: "true"

# Host name to use for the Traefik endpoint. Combined with [sonarr_docker_host_domain] to form the
# FQDN for the endpoint.
sonarr_docker_host_name: "sonarr"

# Domain name to use for the Traefik endpoint. Combined with [sonarr_docker_host_name] to form the
# FQDN for the endpoint. Also used by Traefik to create the necessary Let's Encrypt certificate.
sonarr_docker_host_domain: "example.com"

#####
# Ansible
#####

sonarr_docker_role_label: "sonarr-docker"