---
#####
# Kometa settings
#####

# Timezone code for the container. Timezone codes can be found at:
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
kometa_docker_timezone: "America/New_York"

# Tells the Kometa container to run immediately and then exit.
kometa_docker_run_once_only: true

# Specify the time of day that Kometa will run. Will default to 05:00 when not specified.
# Comma-separated list in HH:MM format.
# Examples:
#   "03:00" ==> 3AM
#   "02:00,18:00" ==> 3AM and 6PM
kometa_docker_run_time: null

#####
# Config settings
#####
kometa_docker_libraries: |2
    Movies:
      metadata_path:
        - pmm: "basic"
        - pmm: "imdb"
      overlay_path:
        - remove_overlays: false
        - pmm: "ribbon"
    TV Shows:
      metadata_path:
        - pmm: "basic"
        - pmm: "imdb"
      overlay_path:
        - remove_overlays: false
        - pmm: "ribbon"
    Anime:
      metadata_path:
        - pmm: "basic"
        - pmm: "anilist"
    Music:
      metadata_path:
        - file: "config/Music.yml"

kometa_docker_playlist_files:
  - "pmm: playlist"

# Required
kometa_docker_plex_url: "http://192.168.1.2:32400"
kometa_docker_plex_token: null
kometa_docker_plex_timeout: "60"
kometa_docker_plex_clean_bundles: true
kometa_docker_plex_empty_trash: true
kometa_docker_plex_optimize: false

# Optional. Default is something absurd like 40MB.
kometa_docker_plex_db_cache: null

# Required
kometa_docker_tmdb_apikey: null
kometa_docker_tmdb_language: "en"
kometa_docker_tmdb_region: "us"
kometa_docker_tmdb_cache_expiration: "60"

# Tautulli (Optional)
kometa_docker_tautulli_url: null  # e.g. http://192.168.1.12:8181
kometa_docker_tautulli_apikey: null

# Omdb (Optional)
kometa_docker_omdb_apikey: null
kometa_docker_omdb_cache_expiration: "60"

# mdblist (Optional)
kometa_docker_mdblist_apikey: null
kometa_docker_mdblist_cache_expiration: "60"

# Notifiarr (Optional)
kometa_docker_notifiarr_apikey: null

# AniDB (Optional)
kometa_docker_anidb_client: null
kometa_docker_anidb_version: "1"
kometa_docker_anidb_language: "en"
kometa_docker_anidb_cache_expiration: "60"
kometa_docker_anidb_username: ""
kometa_docker_anidb_password: ""

# Radarr (Optional)
kometa_docker_radarr: null

# kometa_docker_radarr: |2
#   url: http://192.168.1.12:7878
#   token: ################################
#   add_missing: false
#   add_existing: false
#   root_folder_path: /media/videos/movies
#   monitor: true
#   availability: announced
#   quality_profile: HD-1080p
#   tag:
#   search: false
#   radarr_path: /media/radarr
#   plex_path: /var/lib/plex/media/movies

# Sonarr (Optional)
kometa_docker_sonarr: null

# kometa_docker_sonarr: |2
#   url: http://192.168.1.12:8989
#   token: ################################
#   add_missing: false
#   add_existing: false
#   root_folder_path: "/media/videos/tv"
#   monitor: all
#   quality_profile: HD-1080p
#   language_profile: English
#   series_type: standard
#   season_folder: true
#   tag:
#   search: false
#   cutoff_search: false
#   sonarr_path: /media/sonarr
#   plex_path: /var/lib/plex/media/tv

# Trakt (Optional)
# See https://replit.com/@chazlarson/TraktAuth to generate the auth data.
kometa_docker_trakt: null

# kometa_docker_trakt: |2
#   client_id: ##########
#   client_secret: ##########
#   pin:

# MyAnimeList (Optional)
kometa_docker_mal: null

# kometa_docker_mal: |2
#   client_id: ####################
#   client_secret: ####################
#   authorization:
#     # everything below is autofilled by the script
#     access_token:
#     token_type:
#     expires_in:
#     refresh_token:

#####
# Container settings
#####

# Name of the Docker container.
kometa_docker_name: "kometa"

# Base name of the Docker image to use for the container.
kometa_docker_image_name: "kometateam/kometa"

# Specific Docker image version to use for the container.
kometa_docker_image_version: "latest"

# Number of vCPUs to allocate to the container.
kometa_docker_cpus: "1"

# Amount of memory to allocate to the container.
kometa_docker_memory: "512M"

# Override DNS servers.
# kometa_docker_dns_servers: null

# Prevent Kometa from modifying the config.yml.
kometa_docker_config_read_only: "true"

# Extra environment variables to pass to Kometa
kometa_docker_extra_env_vars: {}

#####
# Docker volumes and folders
#####

# Name of the Docker volume to create to store data files. Only used when
# [kometa_docker_use_volumes] is true.
kometa_docker_volume_name: "kometa"
