---
- name: "{{ prometheus_docker_role_label }} | Create Prometheus Docker data volume"
  community.docker.docker_volume:
    name: "{{ prometheus_docker_volume_name_data }}"

- name: "{{ prometheus_docker_role_label }} | Get info on data volume"
  community.docker.docker_volume_info:
    name: "{{ prometheus_docker_volume_name_data }}"
  register: "_prometheus_docker_data_volume_info"

- name: "{{ prometheus_docker_role_label }} | Set permissions on data volume mount point"
  ansible.builtin.file:
    path: "{{ _prometheus_docker_data_volume_info.volume.Mountpoint }}"
    state: "directory"
    mode: "0750"
    owner: "{{ prometheus_docker_uid }}"
    group: "{{ prometheus_docker_gid }}"

- name: "{{ prometheus_docker_role_label }} | Create folder for config file and set permissions"
  ansible.builtin.file:
    path: "{{ prometheus_docker_config_file_path | dirname }}"
    state: "directory"
    mode: "0755"
    owner: "{{ prometheus_docker_uid }}"
    group: "{{ prometheus_docker_gid }}"

- name: "{{ prometheus_docker_role_label }} | Create Prometheus config file from template"
  ansible.builtin.template:
    src: "prometheus.yml.j2"
    dest: "{{ prometheus_docker_config_file_path }}"
    mode: "0640"
    owner: "{{ prometheus_docker_uid }}"
    group: "{{ prometheus_docker_gid }}"
  register: "_prometheus_docker_config_file"

- name: "{{ prometheus_docker_role_label }} | Set Docker mount list"
  ansible.builtin.set_fact:
    _prometheus_docker_mount_list:
      - "source": "{{ prometheus_docker_volume_name_data }}"
        "target": "/prometheus"
        "type": 'volume'
      - "source": "{{ prometheus_docker_config_file_path }}"
        "target": "/etc/prometheus/prometheus.yml"
        "type": 'bind'
        "read_only": true

- name: "{{ prometheus_docker_role_label }} | Mount Docker socket if enabled"
  ansible.builtin.set_fact:
    _prometheus_docker_mount_list: "{{ _prometheus_docker_mount_list + [ { 'source': '/var/run/docker.sock', 'target': '/var/run/docker.sock', 'type': 'bind' } ] }}"
  when: "prometheus_docker_mount_docker_socket"

- name: "{{ prometheus_docker_role_label }} | Build container FQDN"
  ansible.builtin.set_fact:
    _prometheus_docker_fqdn: "{{ prometheus_docker_host_name }}.{{ prometheus_docker_host_domain }}"

- name: "{{ prometheus_docker_role_label }} | Create placeholder array for default network"
  ansible.builtin.set_fact:
    _prometheus_docker_default_networks:
      - name: "{{ prometheus_docker_network_name }}"
        aliases: "{{ prometheus_docker_network_aliases | default(omit) }}"

- name: "{{ prometheus_docker_role_label }} | Define all Docker networks for this container"
  ansible.builtin.set_fact:
    _prometheus_docker_all_networks: >
      {{ _prometheus_docker_default_networks + prometheus_docker_extra_networks }}

- name: "{{ prometheus_docker_role_label }} | Define Docker labels with Traefik disabled"
  ansible.builtin.set_fact:
    _prometheus_docker_labels: "{{ _prometheus_docker_labels | default({}) |
      combine({__item.key: __item.value}) }}"
  with_items:
    - key: "traefik.enable"
      value: "{{ prometheus_docker_available_externally | lower | ternary('false', 'true') }}"
  loop_control:
    loop_var: __item
  when: "not prometheus_docker_available_externally"

- name: "{{ prometheus_docker_role_label }} | Define Docker labels with Traefik enabled"
  ansible.builtin.set_fact:
    _prometheus_docker_labels: "{{ _prometheus_docker_labels | default({}) |
      combine({__item.key: __item.value}) }}"
  with_items:
    - key: "traefik.enable"
      value: "{{ prometheus_docker_available_externally | string | lower }}"
    - key: "traefik.docker.network"
      value: "{{ prometheus_docker_network_name }}"
    - key: "traefik.http.routers.prometheus.rule"
      value: "Host(`{{ _prometheus_docker_fqdn }}`)"
    - key: "traefik.http.routers.prometheus.entrypoints"
      value: "http,https"
    - key: "traefik.http.routers.prometheus.tls.certresolver"
      value: "letsencrypt"
    - key: "traefik.http.routers.prometheus.tls.domains[0].main"
      value: "*.{{ prometheus_docker_host_domain }}"
    - key: "traefik.http.services.prometheus.loadbalancer.server.port"
      value: "{{ prometheus_docker_http_api_port }}"
  loop_control:
    loop_var: __item
  when: "prometheus_docker_available_externally"

- name: "{{ prometheus_docker_role_label }} | Define user-supplied extra Docker labels"
  ansible.builtin.set_fact:
    _prometheus_docker_labels: "{{ _prometheus_docker_labels | default({}) |
      combine({__item.key: __item.value}) }}"
  loop: "{{ prometheus_docker_extra_labels | dict2items }}"
  loop_control:
    loop_var: __item

- name: "{{ prometheus_docker_role_label }} | Define default Docker environment variables"
  ansible.builtin.set_fact:
    _prometheus_docker_env_vars: {}

- name: "{{ prometheus_docker_role_label }} | Define user-supplied extra Docker environment variables"
  ansible.builtin.set_fact:
    _prometheus_docker_env_vars: "{{ _prometheus_docker_env_vars | default({}) |
      combine({__item.key: __item.value}) }}"
  loop: "{{ prometheus_docker_extra_env | dict2items }}"
  loop_control:
    loop_var: __item

- name: "{{ prometheus_docker_role_label }} | Create Docker Container"
  community.docker.docker_container:
    name: "{{ prometheus_docker_name }}"
    image: "{{ prometheus_docker_image_name }}:{{ prometheus_docker_image_version }}"
    pull: true
    env: "{{ _prometheus_docker_env_vars }}"
    mounts: "{{ _prometheus_docker_mount_list }}"
    network_mode: "{{ prometheus_docker_network_name }}"
    networks: "{{ _prometheus_docker_all_networks }}"
    etc_hosts: "{{ prometheus_docker_extra_hosts | default(omit) }}"
    restart_policy: unless-stopped
    restart: "{{ _prometheus_docker_config_file.changed | default(false) }}"
    memory: "{{ prometheus_docker_memory }}"
    cpus: "{{ prometheus_docker_cpus }}"
    container_default_behavior: no_defaults
    auto_remove: no
    detach: yes
    init: yes
    interactive: no
    paused: no
    privileged: no
    read_only: no
    user: "{{ prometheus_docker_uid }}:{{ prometheus_docker_gid }}"
    tty: no
    labels: "{{ _prometheus_docker_labels }}"
