---
- name: Create Glances Docker network
  community.docker.docker_network:
    name: "{{ glances_network_name }}"
    driver: "bridge"
    enable_ipv6: "no"
    internal: "yes"
    scope: "local"
    ipam_config:
      - subnet: 172.18.0.0/16
        gateway: 172.18.0.1
  when: glances_network_name is defined

- name: Create Portainer Docker network
  community.docker.docker_network:
    name: "{{ portainer_network_name }}"
    driver: "bridge"
    enable_ipv6: "no"
    internal: "yes"
    scope: "local"
    ipam_config:
      - subnet: 172.20.0.0/16
        gateway: 172.20.0.1
  when: portainer_network_name is defined

- name: Create InfluxDB Docker network
  community.docker.docker_network:
    name: "{{ influxdb_network_name }}"
    driver: "bridge"
    enable_ipv6: "no"
    internal: "no"
    scope: "local"
    ipam_config:
      - subnet: 172.21.0.0/16
        gateway: 172.21.0.1
  when: influxdb_network_name is defined

- name: Create restic rest-server Docker network
  community.docker.docker_network:
    name: "{{ restic_rest_server_network_name }}"
    driver: "bridge"
    enable_ipv6: "no"
    internal: "no"
    scope: "local"
    ipam_config:
      - subnet: 172.22.0.0/16
        gateway: 172.22.0.1
  when: restic_rest_server_network_name is defined

- name: Build Traefik traefik_extra_networks
  ansible.builtin.set_fact:
    traefik_extra_networks: "{{ traefik_extra_networks | default([]) }} + [{ 'name': '{{ item }}' }]"
  loop:
    - "{{ glances_network_name | default('') }}"
    - "{{ portainer_network_name | default('') }}"
    - "{{ influxdb_network_name | default('') }}"
    - "{{ restic_rest_server_network_name | default('') }}"
  when: item != ''
