---
- name: Set login banner
  ansible.builtin.copy:
    src: motd.txt
    dest: /etc/motd

- name: Enable Universe repository
  ansible.builtin.raw: apt-add-repository universe
  register: add_repo_result
  changed_when: "'distribution component enabled for all sources' in add_repo_result.stdout"
  until: add_repo_result.rc == 0
  retries: 3
  delay: 1

- name: Update apt-cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  register: result
  until: result is succeeded

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: yes
    state: latest
  when: keep_packages_updated
  tags:
    - skip_ansible_lint

- name: Install some packages
  ansible.builtin.apt:
    name: "{{ veggie_nas_extra_packages }}"
    state: present
  register: result
  until: result is succeeded

- name: "Set hostname to {{ veggie_nas_hostname }}"
  ansible.builtin.hostname:
    name: "{{ veggie_nas_hostname }}"

- name: "Set timezone to {{ veggie_nas_timezone }}"
  community.general.timezone:
    name: "{{ veggie_nas_timezone }}"

- name: Create admin user
  ansible.builtin.user:
    name: "{{ veggie_nas_admin_username }}"
    shell: /bin/bash
    state: present
    password: "{{ veggie_nas_admin_passwd }}"
    update_password: on_create

- name: Create additional users
  ansible.builtin.user:
    name: "{{ item.key }}"
    shell: /usr/bin/false
    state: present
    password: "{{ item.value }}"
    update_password: always
  loop: "{{ veggie_nas_users_passwords | dict2items }}"
