- import_tasks: general.yml
  tags:
    - veggie_nas
    - veggie_nas:general

- import_tasks: samba.yml
  tags:
    - veggie_nas
    - veggie_nas:samba

- import_tasks: docker.yml
  tags:
    - veggie_nas
    - veggie_nas:docker