---
###
### Container settings
###

# Name of the Docker container.
traefik3_name: "traefik3"

# Base name of the Docker image to use for the container.
traefik3_image_name: "traefik"

# Specific Docker image version to use for the container.
traefik3_image_version: "v3"

# Number of vCPUs to allocate to the container.
traefik3_cpus: "1"

# Amount of memory to allocate to the container.
traefik3_memory: "1GB"

traefik3_restart_policy: "unless-stopped"

# Extra environment variables to pass to Traefik.
traefik3_extra_env_vars: {}

# Dictionary of extra key value pairs to set as labels on the Docker container.
traefik3_extra_labels: {}

# Name of the default network.
traefik3_network_name: "traefik3"

# Container aliases on the default network.
traefik3_network_aliases: null

# List of additional networks to join.
traefik3_extra_networks: []

# Host name to use for the Traefik endpoint. Combined with [traefik3_host_domain] to form the
# FQDN for the endpoint.
traefik3_host_name: "traefik3"

# Domain name to use for the Traefik endpoint. Combined with [traefik3_host_name] to form the
# FQDN for the endpoint. Also used by Traefik to create the necessary Let's Encrypt certificate.
traefik3_host_domain: "example.com"

traefik3_timezone: "America/New_York"

traefik3_port_map_list:
  - '80:80'
  - '443:443'

###
### Docker volumes and folders
###

# Name of the Docker volume to create to store config files.
traefik3_config_volume_name: "traefik3"

# Name of the Docker volume to create to store log files.
traefik3_log_volume_name: "traefik3-logs"

###
### Traefik configuration
###

# traefik3_conf_access_log_buffering_size: 500

# True to enable Traefik access logs.
traefik3_conf_access_log_enabled: false

traefik3_conf_access_log_fields_default_mode: "drop"
traefik3_conf_access_log_fields_extras: {}
traefik3_conf_access_log_fields_names:
  ClientHost: "keep"
  RequestHost: "keep"
  RequestLine: "keep"
  RequestMethod: "keep"
  RequestPath: "keep"
  RequestProtocol: "keep"
  RequestScheme: "keep"
  RouterName: "keep"
  ServiceName: "keep"
  StartLocal: "keep"

traefik3_conf_access_log_headers_default_mode: "keep"
traefik3_conf_access_log_headers_extras: {}
traefik3_conf_access_log_headers_names:
  # Redact the User-Agent header value
  User-Agent: redact
  # Drop the Authorization header value
  Authorization: drop

# Pathname to the Traefik access log file.
traefik3_conf_access_log_file: "/var/log/traefik/access.log"

traefik3_conf_access_log_filters: {}

# Logfile format for the access logs. One of "common" or "json".
traefik3_conf_access_log_format: "common"
traefik3_conf_access_log_extra_options: {}

# Path to the main Traefik log file.
traefik3_conf_logging_file: "/var/log/traefik/traefik.log"

# common or json
traefik3_conf_logging_format: "common"
traefik3_conf_logging_level: "ERROR"
traefik3_conf_logging_extra_options: {}

traefik3_conf_metrics: {}

# Dictionary of entrypoint configuration options.
# https://doc.traefik.io/traefik/reference/install-configuration/entrypoints/
traefik3_conf_entrypoints: null

# Dictionary of Provider options.
# https://doc.traefik.io/traefik/reference/install-configuration/providers/overview/
traefik3_conf_providers: null

# Dictionary of certificate resolver options.
# https://doc.traefik.io/traefik/reference/install-configuration/tls/certificate-resolvers/overview/
traefik3_conf_cert_resolvers: null

traefik3_conf_tracing_enabled: false
traefik3_conf_tracing_options: {}

###
### Dashboard
###

traefik3_dashboard_entrypoint_observability:
  accessLogs: false
  metrics: false
  tracing: false

# Make the insecure (HTTP) to secure (HTTPS) redirect for the dashboard permanent.
traefik3_dashboard_entrypoint_permanent_redirect: true

# Enable the API in insecure mode, which means that the API will be available directly on the
# entryPoint named traefik, on path /api.
traefik3_dashboard_api_insecure: false

# Enable the dashboard and api.
traefik3_dashboard_enabled: true

# FQDN to use for the dashboard. Default is {{ traefik3_host_name }}.{{ traefik3_host_domain }}
traefik3_dashboard_fqdn: null

# List of middleware names 
traefik3_dashboard_middleware_names: null

# Map of label names to values
traefik3_dashboard_middleware_labels: {}

# Name of HTTP entrypoint for the dashboard
# traefik3_dashboard_entrypoint_insecure: "http"

# # HTTP port for the dashboard.
# traefik3_dashboard_entrypoint_insecure_port: "80"

# # Name of the HTTPS entrypoint for the dashboard
# traefik3_dashboard_entrypoint_secure: "https"

# # HTTPS port for the dashboard.
# traefik3_dashboard_entrypoint_secure_port: "443"

###
### Entrypoints
###

# Name of the HTTP entrypoint
traefik3_entrypoint_insecure: "http"

# Port for the HTTP entrypoint
traefik3_entrypoint_insecure_port: "80"

# Name of the HTTPS entrypoint
traefik3_entrypoint_secure: "https"

# Port for the HTTPS entrypoint
traefik3_entrypoint_secure_port: "443"

traefik3_trusted_ips: null

# Include a global redirect to https for every http endpoint.
traefik3_redirect_http: true
