---
netplan_folder: "/etc/netplan"
netplan_cloudinit_yaml: "50-cloud-init.yaml"

netplan_cloudinit_folder: "/etc/cloud/cloud.cfg.d"
netplan_disable_cloudinit: true

netplan_new_config_name: "01-netcfg.yaml"

# List of interface names.
# e.g. ["eno1", "eno2", "eno3"]
netplan_interfaces: []

netplan_bonds: []

# Dictionary mapping vlan names to vlan details. Each entry should be a dictionary containg valid
# keys for a netplan config. At a minimum, needs to include: id and link.
#
# Example 1
# netplan_vlans:
#   mgmt:
#     id: 10
#     link: bond0
#   iot:
#     id: 20
#     link: eth1
#     nameservers:
#       addresses: ["8.8.8.8", "8.8.4.4"]
netplan_vlans: {}