---
- name: "Create required letsencrypt directories"
  ansible.builtin.file:
    path: "{{ letsencrypt_dir }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - account
    - certs
    - csrs
    - keys

- name: Generate letsencrypt private account key
  community.crypto.openssl_privatekey:
    path: "{{ letsencrypt_account_dir }}/{{ letsencrypt_domain_name }}.pem"

- name: Generate private key
  community.crypto.openssl_privatekey:
    path: "{{ letsencrypt_dir }}/keys/{{ letsencrypt_domain_name }}.pem"

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: "{{ letsencrypt_dir }}/csrs/{{ letsencrypt_domain_name }}.csr"
    privatekey_path: "{{ letsencrypt_dir }}/keys//{{ letsencrypt_domain_name }}.pem"
    common_name: "{{ letsencrypt_domain_name }}"

- name: "Begin Let's Encrypt challenges"
  community.crypto.acme_certificate:
    acme_directory: "{{ acme_directory }}"
    acme_version: "{{ acme_version }}"
    account_key_src: "{{ letsencrypt_account_dir }}/{{ letsencrypt_domain_name }}.pem"
    account_email: "{{ acme_email }}"
    terms_agreed: 1
    challenge: "{{ acme_challenge_type }}"
    csr: "{{ letsencrypt_csrs_dir }}/{{ letsencrypt_domain_name }}.csr"
    dest: "{{ letsencrypt_certs_dir }}/{{ letsencrypt_domain_name }}.crt"
    fullchain_dest: "{{ letsencrypt_certs_dir }}/fullchain_{{ letsencrypt_domain_name }}.crt"
    remaining_days: "{{ letsencrypt_remaining_days }}"
  register: acme_challenge

- name: "Update Route53"
  community.aws.route53:
    zone: "{{ acme_route53_domain }}"
    aws_access_key: "{{ letsencrypt_aws_access_key }}"
    aws_secret_key: "{{ letsencrypt_aws_secret_key }}"
    record: "{{ acme_challenge.challenge_data[letsencrypt_domain_name]['dns-01'].record }}"
    type: TXT
    ttl: 60
    state: present
    wait: yes
    # Note: route53 requires TXT entries to be enclosed in quotes
    # requires every entry to be enclosed in quotes
    value: "{{ acme_challenge.challenge_data[letsencrypt_domain_name]['dns-01'].resource_value | regex_replace('^(.*)$', '\"\\1\"') }}"
  when: acme_challenge is changed and letsencrypt_domain_name in acme_challenge.challenge_data

- name: Let the challenge be validated and retrieve the cert and intermediate certificate
  community.crypto.acme_certificate:
    account_key_src: "{{ letsencrypt_account_dir }}/{{ letsencrypt_domain_name }}.pem"
    account_email: "{{ acme_email }}"
    src: "{{ letsencrypt_csrs_dir }}/{{ letsencrypt_domain_name }}.csr"
    cert: "{{ letsencrypt_certs_dir }}/{{ letsencrypt_domain_name }}.crt"
    fullchain: "{{ letsencrypt_certs_dir }}/fullchain_{{ letsencrypt_domain_name }}.crt"
    chain: "{{ letsencrypt_certs_dir }}/{{ letsencrypt_domain_name }}-intermediate.crt"
    challenge: dns-01
    acme_directory: https://acme-v01.api.letsencrypt.org/directory
    remaining_days: "{{ letsencrypt_remaining_days }}"
    data: "{{ acme_challenge }}"
  when: acme_challenge is changed and letsencrypt_domain_name in acme_challenge.challenge_data
