---
- ansible.builtin.import_tasks: letsencrypt-deps.yml
  tags:
    - letsencrypt
    - letsencrypt:deps

- ansible.builtin.import_tasks: letsencrypt-issue.yml
  tags:
    - letsencrypt
    - letsencrypt:issue
