---
- name: "Setup Diun"
  hosts: "veggie_nas"
  remote_user: "sean"
  become: yes

  pre_tasks:
    - name: "Setup Diun Docker network"
      community.docker.docker_network:
        name: "{{ diun_docker_network_name }}"
        driver: "bridge"
        enable_ipv6: "no"
        internal: "no"
        scope: "local"
        ipam_config:
          - subnet: "{{ diun_docker_network_subnet }}"
            gateway: "{{ diun_docker_network_gateway }}"
      tags: ["docker", "network", "networks"]

  roles:
    - role: "diun"
      tags: ["diun"]
