---
- name: "Setup Glances"
  hosts: "veggie_nas"
  remote_user: "sean"
  become: yes

  pre_tasks:
    - name: "Setup Glances Docker network"
      community.docker.docker_network:
        name: "{{ glances_network_name }}"
        driver: "bridge"
        enable_ipv6: "no"
        internal: "no"
        scope: "local"
        ipam_config:
          - subnet: "{{ glances_network_subnet }}"
            gateway: "{{ glances_network_gateway }}"
      tags: ["docker", "network", "networks"]

  roles:
    - role: "glances"
      vars:
        glances_docker_host_domain: "{{ glances_host_domain_name }}"
        glances_docker_network_gateway: "{{ glances_network_gateway }}"
        glances_docker_network_subnet: "{{ glances_network_subnet }}"        
        glances_docker_config: "{{ glances_config_data }}"
        glances_docker_extra_bind_mounts: "{{ glances_extra_bind_mounts }}"
      tags: ["glances"]
