---
- name: "Setup Node-RED"
  hosts: nas
  remote_user: sean
  become: yes

  roles:
    - role: "docker_networks"
      vars:
        organicveggie_docker_networks:
          - name: "{{ nodered_docker_network_name }}"
            enable_ipv6: "no"
            internal: "no"
            scope: "local"
            subnet: "{{ nodered_docker_network_subnet }}"
            gateway: "{{ nodered_docker_network_gateway }}"
      tags: ["docker", "network", "networks"]

    - role: "nodered"
      tags: ["nodered"]