- name: "Setup Plex containers"
  hosts: "veggie_nas"
  remote_user: "sean"
  become: yes

  pre_tasks:
    - name: "Create plex group"
      ansible.builtin.group:
        name: "{{ plex_groupname }}"
        gid: "{{ plex_gid }}"

    - name: "Create plex user"
      ansible.builtin.user:
        name: "{{ plex_username }}"
        uid: "{{ plex_uid }}"
        create_home: "false"
        password: "!"
        groups:
            - "{{ plex_groupname }}"
            - "media_writer"
            - "music_writer"

  roles:
    - role: "plex_docker"
      vars:
        # TODO: plex_docker_port: "{{ nas_plex_port }}"
        plex_docker_claim: "{{ vault_plex_docker_claim }}"
        plex_docker_cpus: "{{ plex_cpus }}"
        plex_docker_gid: "{{ plex_gid }}"
        plex_docker_groupname: "{{ plex_groupname }}"
        plex_docker_memory: "{{ plex_memory  }}"
        plex_docker_uid: "{{ plex_uid }}"
        plex_docker_username: "{{ plex_username }}"
        plex_docker_additional_bind_mounts:
          - source: "{{ plex_media_path }}/music"
            target: "/media/music"
          - source: "{{ servarr_data_source_path }}/music/albums"
            target: "/media/music-albums"
          - source: "{{ servarr_data_source_path }}/music/live"
            target: "/media/music-live"
          - source: "{{ plex_media_path }}/videos/anime"
            target: "/media/anime"
          - source: "{{ plex_media_path }}/videos/exercise"
            target: "/media/exercise"
          - source: "{{ plex_media_path }}/videos/movies"
            target: "/media/movies"
          - source: "{{ plex_media_path }}/videos/tv"
            target: "/media/tv"
