- name: "Setup Plex Media Manager"
  hosts: nas
  remote_user: sean
  become: yes

  roles:
    - role: "docker_networks"
      vars:
        organicveggie_docker_networks:
          - name: "{{ pmm_network_name }}"
            enable_ipv6: "no"
            internal: "no"
            scope: "local"
            subnet: "{{ pmm_network_subnet }}"
            gateway: "{{ pmm_network_gateway }}"
      tags: ["docker", "network", "networks"]

    - role: "organicveggie.pmm_docker"
      vars:
        pmm_docker_network: "{{ pmm_network_name }}"
        pmm_docker_network_subnet: "{{ pmm_network_subnet }}"
        pmm_docker_network_gateway: "{{ pmm_network_gateway }}"
        pmm_docker_extra_networks:
          - name: "{{ pmm_network_name }}"
          - name: "{{ tautulli_network }}"
      tags: ["pmm", "pmm-docker", "plex-meta-manager", "plexmetamanager"]
