---
- name: "Setup r720 servers"
  hosts: "r720"
  remote_user: "sean"
  become: true

  roles:
    - role: "r720xd"
      vars:
        # Docker
        r720xd_docker_home: "{{ vault_r720xd_docker_home }}"
        r720xd_docker_users: "{{ docker_users }}"
        # Host
        r720xd_fqdn: "{{ vault_r720xd_fqdn }}"
        r720xd_site_domain: "{{ server_site_domain }}"
        r720xd_timezone: "{{ server_timezone }}"
        r720xd_users: []
        # Route53
        r720xd_route53_access_key_id: "{{ server_aws_route53_access_key_id }}"
        r720xd_route53_secret_access_key: "{{ server_aws_route53_secret_access_key }}"
        r720xd_route53_region: "{{ server_aws_route53_region }}"
        r720xd_route53_hosted_zone_id: "{{ server_aws_route53_hosted_zone_id }}"
        # Traefik
        r720xd_traefik_https_redirect: false
        r720xd_traefik_letsencrypt_email: "{{ primary_email_address }}"
        r720xd_traefik_letsencrypt_use_prod: false
        r720xd_traefik_trusted_ips: "{{ server_traefik_trusted_ips }}"