---
- name: "Setup r720xd"
  hosts: "veggie_nas"
  remote_user: "sean"
  become: true

- ansible.builtin.import_playbook: "docker.yml"
  tags: ["docker"]

    - name: "Install Portainer"
      ansible.builtin.import_tasks: "portainer.yml"
      tags: ["portainer"]
