---
- name: "Setup *arr containers"
  hosts: nas
  remote_user: "sean"
  become: yes

  pre_tasks:
    - name: "Create servarr group"
      ansible.builtin.group:
        name: "{{ servarr_groupname }}"
        gid: "{{ servarr_gid }}"

    - name: "Create servarr user"
      ansible.builtin.user:
        name: "{{ servarr_username }}"
        uid: "{{ servarr_uid }}"
        create_home: "false"
        groups: "{{ servarr_groupname }}"
        password: "!"

    - name: "Create top-level ZFS datasets"
      community.general.zfs:
        name: "{{ item }}"
        state: present
      loop:
        - "nas/data/servarr"
        - "nas/data/servarr/books"
        - "nas/data/servarr/downloads"
        - "nas/data/servarr/downloads/torrents"
        - "nas/data/servarr/downloads/usenet"
        - "nas/data/servarr/music"

    - name: "Set owner/group for datasets"
      ansible.builtin.file:
        path: "{{ item }}"
        state: "directory"
        owner: "{{ servarr_username }}"
        group: "{{ servarr_groupname }}"
        mode: "775"
      loop:
        - "/mnt/nas/data/servarr"
        - "/mnt/nas/data/servarr/books"
        - "/mnt/nas/data/servarr/downloads/torrents"
        - "/mnt/nas/data/servarr/downloads/usenet"
        - "/mnt/nas/data/servarr/music"

    - name: "Create folders for completed downloads"
      ansible.builtin.file:
        path: "{{ item }}"
        state: "directory"
        owner: "{{ servarr_username }}"
        group: "{{ servarr_groupname }}"
        mode: "775"
      loop:
        - "/mnt/nas/data/servarr/downloads/torrents/completed"
        - "/mnt/nas/data/servarr/downloads/usenet/completed"

  roles:
    - role: "docker_networks"
      vars:
        organicveggie_docker_networks:
          - name: "{{ servarr_docker_network }}"
            enable_ipv6: "no"
            internal: "no"
            scope: "local"
            subnet: "{{ servarr_docker_network_subnet }}"
            gateway: "{{ servarr_docker_network_gateway }}"
      tags: ["docker", "network", "networks"]

    - role: "calibre_docker"
      vars:
        calibre_docker_gid: "{{ servarr_gid }}"
        calibre_docker_uid: "{{ servarr_uid }}"
        calibre_docker_timezone: "{{ servarr_timezone }}"
        calibre_docker_network: "{{ servarr_docker_network }}"
        calibre_docker_data_source_path: "{{ servarr_data_source_path }}"
        calibre_docker_trusted_ips: "{{ servarr_docker_network_subnet }}"
      tags: ["calibre", "calibre-docker", "calibre_docker"]

    - role: "flaresolverr"
      vars:
        flaresolverr_docker_timezone: "{{ servarr_timezone }}"
        flaresolverr_docker_network: "{{ servarr_docker_network }}"
      tags: ["flaresolverr"]

    - role: "lidarr"
      vars:
        lidarr_docker_gid: "{{ servarr_gid }}"
        lidarr_docker_uid: "{{ servarr_uid }}"
        lidarr_docker_timezone: "{{ servarr_timezone }}"
        lidarr_docker_network: "{{ servarr_docker_network }}"
        lidarr_docker_data_source_path: "{{ servarr_data_source_path }}"
      tags: ["lidarr"]

    - role: "prowlarr"
      vars:
        prowlarr_docker_gid: "{{ servarr_gid }}"
        prowlarr_docker_uid: "{{ servarr_uid }}"
        prowlarr_docker_timezone: "{{ servarr_timezone }}"
        prowlarr_docker_network: "{{ servarr_docker_network }}"
      tags: ["prowlarr"]

    # radarr 1080
    - role: "radarr"
      vars:
        radarr_docker_host_name: "{{ radarr1080_docker_host_name }}"
        radarr_docker_name: "{{ radarr1080_docker_name }}"
        radarr_docker_volume_config_name: "{{ radarr1080_docker_volume_config_name }}"
        radarr_docker_network_aliases: "{{ radarr1080_docker_network_aliases }}"
        radarr_docker_gid: "{{ servarr_gid }}"
        radarr_docker_uid: "{{ servarr_uid }}"
        radarr_docker_timezone: "{{ servarr_timezone }}"
        radarr_docker_network: "{{ servarr_docker_network }}"
        radarr_docker_data_source_path: "{{ servarr_data_source_path }}"
      tags: ["radarr", "radarr1080"]

    # radarr 4K
    - role: "radarr"
      vars:
        radarr_docker_host_name: "{{ radarr4k_docker_host_name }}"
        radarr_docker_name: "{{ radarr4k_docker_name }}"
        radarr_docker_volume_config_name: "{{ radarr4k_docker_volume_config_name }}"
        radarr_docker_network_aliases: "{{ radarr4k_docker_network_aliases }}"
        radarr_docker_gid: "{{ servarr_gid }}"
        radarr_docker_uid: "{{ servarr_uid }}"
        radarr_docker_timezone: "{{ servarr_timezone }}"
        radarr_docker_network: "{{ servarr_docker_network }}"
        radarr_docker_data_source_path: "{{ servarr_data_source_path }}"
      tags: ["radarr", "radarr4k"]

    - role: "readarr"
      vars:
        readarr_docker_gid: "{{ servarr_gid }}"
        readarr_docker_uid: "{{ servarr_uid }}"
        readarr_docker_timezone: "{{ servarr_timezone }}"
        readarr_docker_network: "{{ servarr_docker_network }}"
        readarr_docker_data_source_path: "{{ servarr_data_source_path }}"
      tags: ["readarr"]

    - role: "sabnzbd"
      vars:
        sabnzbd_docker_gid: "{{ servarr_gid }}"
        sabnzbd_docker_uid: "{{ servarr_uid }}"
        sabnzbd_docker_timezone: "{{ servarr_timezone }}"
        sabnzbd_docker_network: "{{ servarr_docker_network }}"
        sabnzbd_docker_data_source_path: "{{ servarr_data_source_path }}"
      tags: ["sabnzbd"]

    # Sonarr 1080
    - role: "sonarr"
      vars:
        sonarr_docker_host_name: "{{ sonarr1080_docker_host_name }}"
        sonarr_docker_name: "{{ sonarr1080_docker_name }}"
        sonarr_docker_volume_config_name: "{{ sonarr1080_docker_volume_config_name }}"
        sonarr_docker_network_aliases: "{{ sonarr1080_docker_network_aliases }}"
        sonarr_docker_gid: "{{ servarr_gid }}"
        sonarr_docker_uid: "{{ servarr_uid }}"
        sonarr_docker_timezone: "{{ servarr_timezone }}"
        sonarr_docker_network: "{{ servarr_docker_network }}"
        sonarr_docker_data_source_path: "{{ servarr_data_source_path }}"
      tags: ["sonarr", "sonarr1080"]

    # Sonarr 4K
    - role: "sonarr"
      vars:
        sonarr_docker_host_name: "{{ sonarr4k_docker_host_name }}"
        sonarr_docker_name: "{{ sonarr4k_docker_name }}"
        sonarr_docker_volume_config_name: "{{ sonarr4k_docker_volume_config_name }}"
        sonarr_docker_network_aliases: "{{ sonarr4k_docker_network_aliases }}"
        sonarr_docker_gid: "{{ servarr_gid }}"
        sonarr_docker_uid: "{{ servarr_uid }}"
        sonarr_docker_timezone: "{{ servarr_timezone }}"
        sonarr_docker_network: "{{ servarr_docker_network }}"
        sonarr_docker_data_source_path: "{{ servarr_data_source_path }}"
      tags: ["sonarr", "sonarr4k"]

    - role: "syncthing"
      vars:
        syncthing_docker_gid: "{{ servarr_gid }}"
        syncthing_docker_uid: "{{ servarr_uid }}"
        syncthing_docker_timezone: "{{ servarr_timezone }}"
        syncthing_docker_network: "{{ servarr_docker_network }}"
        syncthing_docker_data_source_path: "{{ servarr_data_source_path }}"
      tags: ["syncthing"]
    
    - role: "unpackerr"
      vars:
        unpackerr_docker_gid: "{{ servarr_gid }}"
        unpackerr_docker_uid: "{{ servarr_uid }}"
        unpackerr_docker_timezone: "{{ servarr_timezone }}"
        unpackerr_docker_network: "{{ servarr_docker_network }}"
        unpackerr_docker_data_source_path: "{{ servarr_data_source_path }}"
        unpackerr_docker_web_upstreams:
          - "{{ servarr_docker_network_gateway }}"
          - "{{ servarr_docker_network_subnet }}"
        unpackerr_docker_radarr:
          - url: "http://{{ radarr1080_docker_host_name }}:{{ radarr_docker_web_port }}"
            api_key: "{{ vault_radarr1080_api_key }}"
            paths:
              - "/data/downloads"
            protocols: "torrent,usenet"
            timeout: "10s"
            delete_delay: "5m"
            delete_orig: false
            syncthing: true
          - url: "http://{{ radarr4k_docker_host_name }}:{{ radarr_docker_web_port }}"
            api_key: "{{ vault_radarr4k_api_key }}"
            paths:
              - "/data/downloads"
            protocols: "torrent,usenet"
            timeout: "10s"
            delete_delay: "5m"
            delete_orig: false
            syncthing: true
        unpackerr_docker_readarr:
          - url: "http://{{ readarr_docker_host_name }}:{{ readarr_docker_web_port }}"
            api_key: "{{ vault_readarr_api_key }}"
            paths:
              - "/data/downloads"
            protocols: "torrent,usenet"
            timeout: "10s"
            delete_delay: "5m"
            delete_orig: false
            syncthing: true
        unpackerr_docker_sonarr:
          - url: "http://{{ sonarr1080_docker_host_name }}:{{ sonarr_docker_web_port }}"
            api_key: "{{ vault_sonarr1080_api_key }}"
            paths:
              - "/data/downloads"
            protocols: "torrent,usenet"
            timeout: "10s"
            delete_delay: "5m"
            delete_orig: false
            syncthing: true
          - url: "http://{{ sonarr4k_docker_host_name }}:{{ sonarr_docker_web_port }}"
            api_key: "{{ vault_sonarr4k_api_key }}"
            paths:
              - "/data/downloads"
            protocols: "torrent,usenet"
            timeout: "10s"
            delete_delay: "5m"
            delete_orig: false
            syncthing: true
      tags: ["unpackerr", "unpackarr"]
    
    - role: "cloudflared_docker"
      vars:
        cloudflared_docker_name: "servarr-cloudflared"
        cloudflared_docker_tunnel_token: "{{ servarr_cloudflared_token }}"
        cloudflared_docker_network: "{{ servarr_docker_network  }}"
      tags: ["cloudflared", "cloudflare"]

    - role: "overseerr"
      vars:
        overseerr_docker_timezone: "{{ servarr_timezone }}"
        overseerr_docker_network: "{{ servarr_docker_network }}"
        overseerr_docker_extra_hosts:
          "host.docker.internal": "172.17.0.1"
          "plex": "172.17.0.1"
        overseerr_docker_extra_networks:
          - name: "{{ tautulli_docker_network }}"
      tags: ["overseerr"]
