---
- name: "Setup *arr containers"
  hosts: nas
  remote_user: "sean"
  become: yes

  pre_tasks:
    - name: "Create servarr group"
      ansible.builtin.group:
        name: "{{ servarr_groupname }}"
        gid: "{{ servarr_gid }}"

    - name: "Create servarr user"
      ansible.builtin.user:
        name: "{{ servarr_username }}"
        uid: "{{ servarr_uid }}"
        create_home: "false"
        groups: "{{ servarr_groupname }}"
        password: "!"

    - name: "Create top-level ZFS datasets"
      community.general.zfs:
        name: "{{ item }}"
        state: present
      loop:
        - "nas/data/servarr"
        - "nas/data/servarr/books"
        - "nas/data/servarr/downloads"
        - "nas/data/servarr/downloads/torrents"
        - "nas/data/servarr/downloads/usenet"

    - name: "Create ZFS datasets for torrents"
      community.general.zfs:
        name: "nas/data/servarr/downloads/torrents/{{ item }}"
        state: present
      loop:
        - "tv"
        - "movies"
        - "books"
        - "music"

    - name: "Create ZFS datasets for usenet"
      community.general.zfs:
        name: "nas/data/servarr/downloads/usenet/{{ item }}"
        state: present
      loop:
        - "tv"
        - "movies"
        - "books"
        - "music"

    - name: "Set owner/group for datasets"
      ansible.builtin.file:
        path: "{{ item }}"
        state: "directory"
        owner: "{{ servarr_username }}"
        group: "{{ servarr_groupname }}"
        mode: "775"
      loop:
        - "/mnt/nas/data/servarr"
        - "/mnt/nas/data/servarr/books"
        - "/mnt/nas/data/servarr/downloads/torrents"
        - "/mnt/nas/data/servarr/downloads/torrents/tv"
        - "/mnt/nas/data/servarr/downloads/torrents/movies"
        - "/mnt/nas/data/servarr/downloads/torrents/books"
        - "/mnt/nas/data/servarr/downloads/torrents/music"
        - "/mnt/nas/data/servarr/downloads/usenet"
        - "/mnt/nas/data/servarr/downloads/usenet/tv"
        - "/mnt/nas/data/servarr/downloads/usenet/movies"
        - "/mnt/nas/data/servarr/downloads/usenet/books"
        - "/mnt/nas/data/servarr/downloads/usenet/music"

  roles:
    - role: "docker_networks"
      vars:
        organicveggie_docker_networks:
          - name: "{{ servarr_docker_network }}"
            enable_ipv6: "no"
            internal: "no"
            scope: "local"
            subnet: "{{ servarr_docker_network_subnet }}"
            gateway: "{{ servarr_docker_network_gateway }}"
      tags: ["docker", "network", "networks"]

    - role: "calibre_docker"
      vars:
        calibre_docker_gid: "{{ servarr_gid }}"
        calibre_docker_uid: "{{ servarr_uid }}"
        calibre_docker_timezone: "{{ servarr_timezone }}"
        calibre_docker_network: "{{ servarr_docker_network }}"
        calibre_docker_data_source_path: "{{ servarr_data_source_path }}"
        calibre_docker_trusted_ips: "{{ servarr_docker_network_subnet }}"
      tags: ["calibre", "calibre-docker", "calibre_docker"]

    - role: "flaresolverr"
      vars:
        flaresolverr_docker_timezone: "{{ servarr_timezone }}"
        flaresolverr_docker_network: "{{ servarr_docker_network }}"
      tags: ["flaresolverr"]

    - role: "prowlarr"
      vars:
        prowlarr_docker_gid: "{{ servarr_gid }}"
        prowlarr_docker_uid: "{{ servarr_uid }}"
        prowlarr_docker_timezone: "{{ servarr_timezone }}"
        prowlarr_docker_network: "{{ servarr_docker_network }}"
      tags: ["prowlarr"]

    # radarr 1080
    - role: "radarr"
      vars:
        radarr_docker_host_name: "{{ radarr1080_docker_host_name }}"
        radarr_docker_name: "{{ radarr1080_docker_name }}"
        radarr_docker_volume_config_name: "{{ radarr1080_docker_volume_config_name }}"
        radarr_docker_network_aliases: "{{ radarr1080_docker_network_aliases }}"
        radarr_docker_gid: "{{ servarr_gid }}"
        radarr_docker_uid: "{{ servarr_uid }}"
        radarr_docker_timezone: "{{ servarr_timezone }}"
        radarr_docker_network: "{{ servarr_docker_network }}"
        radarr_docker_data_source_path: "{{ servarr_data_source_path }}"
      tags: ["radarr", "radarr1080"]

    # radarr 4K
    - role: "radarr"
      vars:
        radarr_docker_host_name: "{{ radarr4k_docker_host_name }}"
        radarr_docker_name: "{{ radarr4k_docker_name }}"
        radarr_docker_volume_config_name: "{{ radarr4k_docker_volume_config_name }}"
        radarr_docker_network_aliases: "{{ radarr4k_docker_network_aliases }}"
        radarr_docker_gid: "{{ servarr_gid }}"
        radarr_docker_uid: "{{ servarr_uid }}"
        radarr_docker_timezone: "{{ servarr_timezone }}"
        radarr_docker_network: "{{ servarr_docker_network }}"
        radarr_docker_data_source_path: "{{ servarr_data_source_path }}"
      tags: ["radarr", "radarr4k"]

    - role: "readarr"
      vars:
        readarr_docker_gid: "{{ servarr_gid }}"
        readarr_docker_uid: "{{ servarr_uid }}"
        readarr_docker_timezone: "{{ servarr_timezone }}"
        readarr_docker_network: "{{ servarr_docker_network }}"
        readarr_docker_data_source_path: "{{ servarr_data_source_path }}"
      tags: ["readarr"]

    - role: "sabnzbd"
      vars:
        sabnzbd_docker_gid: "{{ servarr_gid }}"
        sabnzbd_docker_uid: "{{ servarr_uid }}"
        sabnzbd_docker_timezone: "{{ servarr_timezone }}"
        sabnzbd_docker_network: "{{ servarr_docker_network }}"
        sabnzbd_docker_data_source_path: "{{ servarr_data_source_path }}"
      tags: ["sabnzbd"]

    # Sonarr 1080
    - role: "sonarr"
      vars:
        sonarr_docker_host_name: "{{ sonarr1080_docker_host_name }}"
        sonarr_docker_name: "{{ sonarr1080_docker_name }}"
        sonarr_docker_volume_config_name: "{{ sonarr1080_docker_volume_config_name }}"
        sonarr_docker_network_aliases: "{{ sonarr1080_docker_network_aliases }}"
        sonarr_docker_gid: "{{ servarr_gid }}"
        sonarr_docker_uid: "{{ servarr_uid }}"
        sonarr_docker_timezone: "{{ servarr_timezone }}"
        sonarr_docker_network: "{{ servarr_docker_network }}"
        sonarr_docker_data_source_path: "{{ servarr_data_source_path }}"
      tags: ["sonarr", "sonarr1080"]

    # Sonarr 4K
    - role: "sonarr"
      vars:
        sonarr_docker_host_name: "{{ sonarr4k_docker_host_name }}"
        sonarr_docker_name: "{{ sonarr4k_docker_name }}"
        sonarr_docker_volume_config_name: "{{ sonarr4k_docker_volume_config_name }}"
        sonarr_docker_network_aliases: "{{ sonarr4k_docker_network_aliases }}"
        sonarr_docker_gid: "{{ servarr_gid }}"
        sonarr_docker_uid: "{{ servarr_uid }}"
        sonarr_docker_timezone: "{{ servarr_timezone }}"
        sonarr_docker_network: "{{ servarr_docker_network }}"
        sonarr_docker_data_source_path: "{{ servarr_data_source_path }}"
      tags: ["sonarr", "sonarr4k"]

    - role: "syncthing"
      vars:
        syncthing_docker_gid: "{{ servarr_gid }}"
        syncthing_docker_uid: "{{ servarr_uid }}"
        syncthing_docker_timezone: "{{ servarr_timezone }}"
        syncthing_docker_network: "{{ servarr_docker_network }}"
        syncthing_docker_data_source_path: "{{ servarr_data_source_path }}"
      tags: ["syncthing"]

