---
- name: "Setup TimeMachine"
  hosts: all
  remote_user: "sean"
  become: true

  pre_tasks:
    - name: "Create Time Machine group"
      ansible.builtin.group:
        name: "{{ time_machine_groupname }}"
        gid: "{{ time_machine_gid | default(omit) }}"
        state: "present"

    - name: "Create Time Machine user"
      ansible.builtin.user:
        username: "{{ time_machine_username }}"
        password: "*"
        shell: "/bin/false"
        system: false
        uid: "{{ time_machine_uid }}"
        group: "{{ time_machine_groupname }}"
        password_lock: true

    - name: "Create Docker network"
      community.docker.docker_network:
        name: "{{ time_machine_network }}"
        driver: "macvlan"
        driver_options:
          parent: "{{ time_machine_network_parent }}"
        enable_ipv6: false
        internal: false
        scope: "local"
        ipam_config:
          - subnet: "{{ time_machine_network_subnet }}"
            gateway: "{{ time_machine_network_gateway }}"

    - name: "Create ZFS dataset"
      community.general.zfs:
        name: "{{ time_machine_zfs_dataset }}"
        state: present
      when: "{{ time_machine_zfs_dataset }}"

    - name: "Create data folder"
      ansible.builtin.file:
        path: "{{ time_machine_data_directory }}"
        mode: "770"
        recurse: true
        state: "directory"
        owner: "root"
        group: "root"

  roles:
    - role: "time_machine_docker"
      vars:
        time_machine_docker_name: "the-time-machine"
        time_machine_docker_uid: "1311"
        time_machine_docker_gid: "1311"
        time_machine_docker_data_directory: "{{ time_machine_data_directory }}"
        time_machine_docker_password: "{{ time_machine_password }}"
        time_machine_docker_network: "{{ time_machine_network }}"
        time_machine_docker_advertised_hostname: "{{ time_machine_hostname }}"
        time_machine_docker_network_ipv4_addr: "{{ time_machine_network_ipv4 }}"
      tags: ["time-machine", "timemachine"]
