---
- name: "Setup Traefik 3"
  hosts: "r720xd"
  remote_user: "sean"
  become: true

  pre_tasks:
    # Create Docker network
    - name: "Create Docker network"
      community.docker.docker_network:
        name: "{{ nas_docker_networks.traefik3.name }}"
        driver: "bridge"
        enable_ipv6: "no"
        internal: "no"
        scope: "local"
        ipam_config:
          - subnet: "{{ nas_docker_networks.traefik3.subnet }}"
            gateway: "{{ nas_docker_networks.traefik3.gateway }}"    

  roles:
    - role: "traefik3"
      vars:
        traefik3_docker_host_domain: "r720xd.350mva.xyz"
        traefik3_docker_extra_env_vars:
          AWS_HOSTED_ZONE_ID: "{{ route53_xyz_hosted_zone_id }}"
          AWS_ACCESS_KEY_ID: "{{ vault_nas_aws_route53_access_key_id }}"
          AWS_SECRET_ACCESS_KEY: "{{ vault_nas_aws_route53_secret_access_key }}"
          AWS_REGION: "{{ vault_nas_aws_route53_region }}"
        traefik3_docker_network: "{{ nas_docker_networks.traefik3.name }}"
        traefik3_docker_letsencrypt_email: "{{ letsencrypt_email }}"
