---
- name: Create groups
  ansible.builtin.group:
    name: "{{ __item.name }}"
    gid: "{{ __item.gid | default(omit) }}"
    system: "{{ __item.system | default(omit) }}"
    state: "{{ __item.state | default('present') }}"
  loop: "{{ user_groups }}"
  loop_control:
    loop_var: __item