---
- name: Create Telegraf environment variables
  ansible.builtin.template:
    src: ../templates/telegraf.default.j2
    dest: /etc/default/telegraf
    owner: root
    group: root
    mode: 0640
  register: t_env

- name: Create Docker input config
  ansible.builtin.template:
    src: ../templates/docker.conf.j2
    dest: /etc/telegraf/telegraf.d/docker.conf
    owner: telegraf
    group: telegraf
    mode: 0640
  when: telegraf_plugin_docker
  register: tp_docker

- name: Create Telegraf config
  ansible.builtin.template:
    src: ../templates/telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    owner: telegraf
    group: telegraf
    mode: 0640
  register: t_config

- name: Restart Telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted
  when: t_env.changed or tp_docker.changed or t_config.changed
  tags:
    - skip_ansible_lint