---
- name: Create Telegraf environment variables
  ansible.builtin.template:
    src: ../templates/telegraf.default.j2
    dest: /etc/default/telegraf
    owner: root
    group: root
    mode: 0640
  notify: Restart Telegraf

- name: Create Telegraf config
  ansible.builtin.template:
    src: ../templates/telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    owner: telegraf
    group: telegraf
    mode: 0640
  notify: Restart Telegraf
