- import_tasks: install.yml
  tags:
    - telegraf
    - telegraf:install

- import_tasks: config.yml
  tags:
    - telegraf
    - telegraf:config

- import_tasks: plugin_docker.yml
  tags:
    - telegraf
    - telegraf:plugins
    - telegraf:plugins:docker
  when: telegraf_plugin_smartctl == true

- import_tasks: plugin_smartctl.yml
  tags:
    - telegraf
    - telegraf:plugins
    - telegraf:plugins:smartctl
  when: telegraf_plugin_smartctl == true

- import_tasks: plugin_zfs_pool_sizes.yml
  tags:
    - telegraf
    - telegraf:plugins
    - telegraf:plugins:zfs_pool_sizes
  when: telegraf_plugin_zfs_pool_sizes == true
