bedtime_shutdown:
  alias: "Bedtime shutdown"
  description: "Reset HVAC setings and turn off lights"
  sequence:
    # Reset the HVAC system to normal heat/cool settings.
    - action: script.reset_hvac_heat_cool

    # Turn off all of the inside lights
    - action: light.turn_off
      metadata: {}
      data: {}
      target:
        area_id:
          - dining_room
          - garage
          - kitchen
          - living_room

    # Turn off the espresso machine
    - type: turn_off
      device_id: d94e677d5e0eadbce78ceb5b66116f66
      entity_id: switch.plug_in_appliance_module
      domain: switch
