bedtime_cleanup:
  sequence:
    # Turn the thermostat on and set it to Heat/Cool
    - action: climate.set_hvac_mode
      metadata: {}
      data:
        hvac_mode: heat_cool
      target:
        entity_id: climate.other_thermostat

    # Set the thermostat fan to run on a schedule
    - device_id: 2261a489df17ce2f6c6bf1b58cb582f4
      domain: select
      entity_id: select.other_thermostat_fan_speed
      type: select_last

    # Turn off all of the inside lights
    - action: light.turn_off
      metadata: {}
      data: {}
      target:
        area_id:
          - dining_room
          - garage
          - kitchen
          - living_room

    # Turn off the espresso machine
    - type: turn_off
      device_id: d94e677d5e0eadbce78ceb5b66116f66
      entity_id: switch.plug_in_appliance_module
      domain: switch
